### ISSUE TITLE
Deadlock on gracefull shutdown.

### ISSUE THREAD

**Issue by kworr** [jrmarino/synth#1]
"I don't know which key I pressed"(C) but it stopped with:

     Total 19      Built 14     Ignored 0      Load  2.50  Pkg/hour 103
      Left 5      Failed 0      skipped 0      swap  0.0%   Impulse 103   00:08:08
    ===============================================================================
            Graceful shutdown in progress, so no new tasks will be started.

The log says:

    00:07:49 [02] => devel/autoconf
    00:07:49 [03] => devel/libtool
    00:07:58 UNHANDLED EXCEPTION: raised CONSTRAINT_ERROR : s-wchcnv.adb:207 explicit raise
    00:07:58 UNHANDLED EXCEPTION: raised CONSTRAINT_ERROR : s-wchcnv.adb:207 explicit raise

**Comment by jrmarino** [comment]
You must have pressed the escape key.

This change should handle the exception: 555337c0288523fbc1fa2de0a752cf0d81102922 (untested, not sure how to reproduce)

Thanks!

**Comment by kworr** [comment]
Well, I'm pretty sure this wasn't the ESC, I pressed some letters and cursor keys trying to understand whether it has some UI. I think cursor keys do generate something starting from ESC...
I'll recheck.

**Comment by jrmarino** [comment]
That could explain it.

The only keypress it's looking for is escape.  There's no other UI at the moment.

**Comment by kworr** [comment]
Yep, that was cursor keys and yes, that fixed it.
