### ISSUE TITLE
Securelevel > 0 and schg flag

### ISSUE THREAD

**Issue by serge-vk** [jrmarino/synth#103]
I wonder if Synth absolutely has to remove schg flag from any objects. I run my system and jails with securelevel > 0 and therefore Synth fails when trying to remove schg flag from a 'home' folder in its tmpfs mount. Is there any way of running Synth without lowering securelevel? Thank you in advance.

**Comment by jrmarino** [comment]
the flag is not needed for most operations, but for some it is.  Not having it would result in occasional failure depending on the port.

**Comment by serge-vk** [comment]
Thank you for your clarification. I was looking forward to ditching portmaster in favour of Synth, but this circumstance essentially rules it out. I have always built ports in a jail with securelevel = 2, and I have yet to see a single one that fails because of that. Moreover, I would consider such a failure a bug, if it ever happened. Unfortunately, neither can securelevel of a jail be lower than that of the host system.

To me, it seems a hugely disproportionate requirement to drop the secure level of the entire system to zero, just for building ports. I believe that the whole idea of Synth is to make building and maintaining ports safe on a live server system. However, with this condition we are back to either having dedicated hardware or a full virtual instance for the sole purpose of building ports.

As much as portmaster is maligned (and I am well aware of its shortcomings), it never complained about running in a hardened environment. So, here it goes again.

**Comment by jrmarino** [comment]
ravenadm (spiritual successor to synth on ravenports) doesn't use schg, but settles for standard permissions.  It might be possible to mirror that in synth.

**Comment by Oclair** [comment]
> ravenadm (spiritual successor to synth on ravenports) doesn't use schg, but settles for standard permissions. It might be possible to mirror that in synth.

Hey thats really great to hear, I appreciate you looking into that!

**Comment by jrmarino** [comment]
okay, so it look like I created a "fallback" scheme for linux, which is basically "chmod 555 or chmod 755" which accomplishes the same thing on an empty directory.  The BSDs still use chflags there, but I'm considering just using the fallback for all systems on both synth and ravenadm.

**Comment by jrmarino** [comment]
Use of chflags removed in the latest release, so this should be resolved.
