### ISSUE TITLE
llvm40 build fails – force official repo pkg install?

### ISSUE THREAD

**Issue by mkastner** [jrmarino/synth#104]
I am referencing the official quaterly repositories in FreeBSD conf but the pkg version of llvm40 provided in quarterly does match the one in the ports tree.

So, synth is kicking off a build, which (goes without saying) fails. It's not a synth fault. The problem seems to be caused by the swap and disc reqirements of llvm40's build process. To be honest, I've never managed to build this gigantic monster even with make.conf. No matter how much swap and disc space I provide.

So I am wondering, is there any way to force an official pkg install on one or more ports in synth?

BTW: synth is awesome and I think there should be an option for donations.

**Comment by jrmarino** [comment]
On Ravenports on FreeBSD, I have to do the following to build llvm40:

   - Provide an additional swapfile to increase swap to something like 20G
   - Limit jobs on llvm to 2 (on Linux, it has to be limited to 1)

The reason for the last is a "freeze" that occurs during linking which is only avoidable if llvm isn't building with many multiple jobs.

as far as using "official" ports instead, there's an option on synth to "prefer" freebsd packages, but it's not quarterly packages, it's the trunk ports.  And it will affect all of them.

You could always "fool" synth by pre-downloading the package and putting it in the repository directory manually.  As long as the dependencies are in place, synth will assume good and won't touch it.

**Comment by mkastner** [comment]
Thank you so much your advice and help. I think I need to buy a box dedicated entirely to building llvm.

**Comment by mkastner** [comment]
Forgot to close the "issue".

**Comment by mkastner** [comment]
Got it to work now.

I ran

just-build lang/gcc6 first

Then I disabled the lldb-debugger for llvm40.

With this in place building of llvm40 worked.

**Comment by jrmarino** [comment]
interesting.
