### ISSUE TITLE
Symlink race vulnerability

### ISSUE THREAD

**Issue by melak** [jrmarino/synth#105]
```bash
$ ls -ld /etc
drwxr-xr-x  27 root  wheel  114 Dec  3 21:11 /etc
$ ls -l /etc/motd
-rw-r--r--  1 root  wheel  940 Dec  2 11:19 /etc/motd
$ ln -s /etc/motd /tmp/synth_status_results.txt
$ sudo synth status
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
Scanning existing packages.
These are the ports that would be built ([N]ew, [R]ebuild, [U]pgrade):
Total packages that would be built: 0
The complete build list can also be found at:
/tmp/synth_status_results.txt
$ cat /etc/motd

------------------------------
--  Statistics
------------------------------
 Ports scanned : 29237
  Elapsed time : 00:00:00
   Parallelism : 12 scanners
          ncpu : 4
```

**Comment by jrmarino** [comment]
This was a little difficult to follow (e.g. why is /etc/motd symlinked to synth status report)?
In any case, it was known that "synth status" had a problem with it, which should be rectified in v2.01 (just released).

**Comment by melak** [comment]
Sorry, my extremely bad, I guess I should have been more clear.

Synth suffers from a pathological case of the venerable [symlink race vulnerability](https://en.wikipedia.org/wiki/Symlink_race), as it writes to  predictably-named files in a world-writeable directory without proper checks applied.

How to reproduce: see above (2.01 does _not_ fix it).

You might want to tell the file creation things to `O_NOFOLLOW` (if that's at all possible from Ada), or put the log files in a non-world-writeable directory.

**Comment by jrmarino** [comment]
I didn't know about this "symlink race" thing.
The best I can do without a new file creation library is simply remove existing files before creating them.  That doesn't address the race, but it would be extremely difficult to insert a symlink in the unknown microsecond between the deletion and recreation of a new file (nobody can predict exactly when the log file is going to be written).

Coupled with the fact that this information simply isn't confidential (dumped to /tmp which is already world-readable), that should be good enough.

I suspect there are other logs like this.

**Comment by jrmarino** [comment]
i guess somebody could write a program to monitor directories for reads in realtime and try to create a symlink as soon as the read is detected.  writing to a random location and moving the closed file to the new location would also solve it, but i don't think implications are worth the additional complexity in this case.

**Comment by melak** [comment]
No, this is not the solution. The solution is either `O_NOFOLLOW` (which I'm not sure how you'd do in Ada, although some bits of the Internet suggest it is possible), use unpredictable names (`mkstemp`, also not sure how you'd do that in Ada), or just put the files somewhere else. What's wrong with `/var/synth`?

**Comment by jrmarino** [comment]
as I said, O_NOFOLLOW is not an option.  It requires a new library for creating files.
I guess changing the location from /tmp to /var/synth would be okay.
It just doesn't seem like a realistic problem given the difficulty of making the symlink and the pay-off for succeeding (which is having access  to information that is most probably useless)

**Comment by melak** [comment]
Which is _overwriting arbitrary files_.

**Comment by melak** [comment]
This looks perfect, thank you!
