### ISSUE TITLE
DEFAULT_VERSIONS not honoured?

### ISSUE THREAD

**Issue by melak** [jrmarino/synth#109]
Synth 2.02 on FreeBSD 11.1:

```bash
$ pkg info synth | head -3
synth-2.02
Name           : synth
Version        : 2.02
```

I have a couple of `DEFAULT_VERSION`s in `/etc/make.conf`, among them one for Perl:

```bash
$ grep perl /etc/make.conf 
DEFAULT_VERSIONS+=              perl5=5.26
```

For some reason, `synth` wants to build Perl 5.24 (which would have been the default had I not overridden it), but also wants to keep Perl 5.26 as well

```bash
$ grep perl5 /var/synth/synth_status_results.txt
lang/perl5.24 (new 5.24.3)
lang/perl5.26 (new 5.26.1)
```

I cannot spot anything anywhere that would warrant building Perl 5.24:

```bash
$ pkg info --dependencies -a | grep -i perl.*24
$ find /usr/local/lib -name 'libperl*.so*'
/usr/local/lib/perl5/5.26/mach/CORE/libperl.so
/usr/local/lib/perl5/5.26/mach/CORE/libperl.so.5.26.1
/usr/local/lib/perl5/5.26/mach/CORE/libperl.so.5.26
$ 
```

I did actually let it do whatever it wanted (although that was with 2.01), `synth status` looked about the same as this, and I ended up with _both_ 5.24 and 5.26 (5.24 having been symlinked to `/usr/local/bin/perl`, so picked up as the default version).

Where might 5.24 be sneaking back in?

Hm, on closer inspection, something wonky is happening with the `emulators/linux-c[67]` ports as well (and these two are the only DEFAULT_VERSIONs I have) - with `DEFAULT_VERSIONS+=linux=c7` and no `linux-c7` packages currently installed, Synth would give me a bunch of `-c6` ones as well:

```bash
$ grep -c linux-c6 /var/synth/synth_status_results.txt
29
```

Again, no `linux-c6-*` packages currently installed, nor any traces of `linux-c6-*` dependencies as per `pkg`.

**Comment by jrmarino** [comment]
please read the synth man page for the locate of the profile make.conf.
/etc/make.conf is NOT used.  Whatever is in that file is ignored.

**Comment by melak** [comment]
I stand educated, this is indeed what's been happening.
