### ISSUE TITLE
Issues with building Apache-OpenOffice on FreeBSD

### ISSUE THREAD

**Issue by cmanv** [jrmarino/synth#110]
Currently editors/openoffice-4 cannot be built with either tmpfs or ccache enabled.

1- synth caps tmpfs to 12Gb which is plenty for most ports but insufficient for OpenOffice. The build requirements for this port are 11Gb of disk space and 2Gb of memory. With synth this results in a 'no space left on device' error late in the build if tmpfs is enabled. (I have 8Gb memory + 17Gb of swap space configured on this system running FreeBSD 11.1-RELEASE)

2- This port also have its own 'CCACHE' option (off by default). Enabling this option works fine with poudriere, but with synth it results in a failure early in the build phase. (I have ccache enabled in synth)

**Comment by jrmarino** [comment]
on the second issue, I'd clear the ccache directory.  After that, I would not be surprised to see ccache work fine with apache openoffice.  Occasionally ccache uses previous work that should be considered invalid, and I think that's what is happening with you.

**Comment by jrmarino** [comment]
on the first issue, you can try rebuilding synth with a patch to file src/replicant.adb, line 1083
change integer from "12" to something higher.
However, the last time I checked, 12 is greater than 11, so in theory 12Gb allocation for work directory should be sufficient.  Obviously the 11Gb value is wrong.

**Comment by cmanv** [comment]
On the first issue, my understanding is that the tmpfs requirement would be 11 + 2. I'm going to patch this as you suggested and report back later.

For the second issue, I already tried to fix it by clearing the cache but that didn't solve the issue.

**Comment by jrmarino** [comment]
no, the 2G memory requirement doesn't count against tmpfs

**Comment by jrmarino** [comment]
on ccache issue, I'd just check that you didn't clear your default ccache directory instead of the ccache directory specified by the synth configure screen.  that's easy to do if you forget to set CCACHE_DIR In the environment for the command.

**Comment by cmanv** [comment]
I was able to build apache-openoffice with a tmpfs cap of 16Gb. The usage of tmpfs in the work area grows to almost 15Gb at the end of the build phase.

Concerning ccache, I confirm that the build still fails even with a clean cache directory.
I think there's a problem with the port. CCACHE_DIR is set to /ccache but there's this errror  the log file:
```
ccache: error: Failed to create directory /root/.ccache/tmp: Operation not permitted
dmake:  Error code 1, while making '../unxfbsdx.pro/obj/ifparser.obj'
```

**Comment by jrmarino** [comment]
well, the /root directory is read only, so that would be the error.  
I'm not sure how the port can influence how ccache works though.
Ports are not allowed to write to $HOME or /root though, so that's an issue with the port.

**Comment by cmanv** [comment]
I've created a PR for this port. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224276

Thanks for the help

**Comment by jrmarino** [comment]
the tmpfs cap of 16G is only required for the tmpfs_workdir right?
meaning 12G is still okay for tmpfs_localbase.  I assume that's the case.

**Comment by cmanv** [comment]
Yes, that is correct. The 16Gb is only for the work area.

**Comment by jrmarino** [comment]
wait, I just looked up your PR and the port itself.
This is insane.
You don't set CCACHE on at the port level.  You set it on at the poudriere / synth level.

So the port authors are doing something extremely non-standard.
However, it should not affect you.  You just leave the CCACHE option off and set ccache on at the synth configure screen.

I misunderstood before.  I thought you were using ccache for all ports (as most people do).

So to iterate:
1) make sure inane CCACHE option is OFF for openoffice
2) set up ccache properly at the synth level.

That should solve the issue.

**Comment by cmanv** [comment]
I use ccache at the synth level, but this port won't honor that (it's the same thing with poudriere). This port requires that you setup the option and will override CC and CXX in the Makefile.

**Comment by jrmarino** [comment]
that's stupid.  Surely only simple code is needed to detect ccache is being used and the makefile can then adjust CONFIGURE_ENV according (option should be needed here)

The "CCACHE_DIR=/ccache" in /etc/make.conf is being ignored, so this hack the openoffice port maintainers have come up with isn't complete.

**Comment by cmanv** [comment]
Yes, this looks wrong, but I don't think these 2 files are used anymore. They're not referenced in any of the makefiles and svn log says it's some old support scripts from the OpenOffice-3 days.

**Comment by jrmarino** [comment]
well, delete them and see if openoffice still builds. 
That will let you know if they are used or not. :)

**Comment by jrmarino** [comment]
put it this way: if they are used, they will definitely break the build.

**Comment by cmanv** [comment]
I just completed a build without those files, so that answers the question.

**Comment by jrmarino** [comment]
might be worth recommending their removal in the PR then.   Nobody needs cruft.
Regardless, something similar is causing the breakage: ccache is being invoked without overriding the default definition of CCACHE_DIR.  And it's not in the man makefile, because CCACHE_DIR is defined in the jails /etc/make.conf file.

**Comment by cmanv** [comment]
Actually, I've figured out a fix. CCACHE_DIR need to be exported to the shell environment prior to calling build.pl in the Makefile. 
I'll do some tests and add a patch to the PR later today. I'll also request that they drop the ccache option entirely and just follow WITH_CCACHE_BUILD.

**Comment by cmanv** [comment]
FYI, the issues were fixed in the FreeBSD ports tree with r459465 and r460047.
- The ccache option has been removed and the port now follow the framework settings.
- The port now builds without the crashdump option and this reduces tmpfs usage to 8Gb.

So I'm closing this ticket.
