### ISSUE TITLE
remove old packages?

### ISSUE THREAD

**Issue by mexas** [jrmarino/synth#112]
Can synth delete old versions of packages?
Say I want to delete all but the latest packages:
```
# ls /var/synth/live_packages/All/libgcrypt*
/var/synth/live_packages/All/libgcrypt-1.7.8.txz
/var/synth/live_packages/All/libgcrypt-1.8.0.txz
/var/synth/live_packages/All/libgcrypt-1.8.1.txz
/var/synth/live_packages/All/libgcrypt-1.8.2.txz
```
If there is no synth command for it,
is it safe to delete these by hand?
Or will this break some synth record keeping?

Thanks

**Comment by jrmarino** [comment]
whenever you "synth rebuild-repository", it should remove all obsolete packages.
apparently you've not been using that command.

**Comment by mexas** [comment]
cool, thank you!
