### ISSUE TITLE
FreeBSD pkg-static errors

### ISSUE THREAD

**Issue by mexas** [jrmarino/synth#114]
I'm the maintainer of FreeBSD lang/opencoarrays. I just updated the port to the latest upstream. I can build the port manually from under the ports tree fine, but under synth it fails pkg-static:
```
===>  Building package for opencoarrays-1.9.3_1
pkg-static: Unable to access file /construction/xports/lang/opencoarrays/work/stage/usr/local/lib/libcaf_mpi.so.1:No such file or directory
```
Full log: <http://eis.bris.ac.uk/~mexas/log/lang___opencoarrays.log>

This is a weird error. This file should be built and is indeed included in pkg-plist.
However, the log shows that instead of *so.1, libcaf_mpi.so.2 is generated.

Do you know what's going on?

Don't know if it's related but I also see pkg-static errors in devel/flang-clang:
```
-- Installing: /construction/xports/devel/flang-clang/work/stage/usr/local/flang/lib/clang/5.0.1/include/__clang_cuda_builtin_vars.h
```
but then
```
===>  Building package for flang-clang-5.0.20171019_1
pkg-static: Unable to access file /construction/xports/devel/flang-clang/work/stage/usr/local/flang/lib/clang/5.0.0/include/__clang_cuda_builtin_vars.h:No such file or directory
```
Note that install uses version 5.0.1 whereas package shows 5.0.0.
This is not my port, so I just mailed the port maintainer for advice.
I'm building flang-clang manually now to compare.
Takes a while, will update when done.

Many thanks for your help!

**Comment by mexas** [comment]
oh... when I build lang/opencoarrays manually now I get libcaf_mpi.so.2, not *.so.1.
I've no idea why. Maybe my USE_LDCONFIG=yes is not right.

But devel/flang-clang does pass pkg-static and gets the package built.

**Comment by jrmarino** [comment]
I don't understand.  Obviously the upstream developers bumped the library version.  As a maintainer, it's your job to update the pkg-plist to mirror that change.  Synth is working perfectly and what you describe is normal maintainer work.  (it's has NOTHING to do with USE_LDCONFIG)

**Comment by mexas** [comment]
Thanks. I can only assume my manual build was contaminated by unclean environment.
Sorry about this.
