### ISSUE TITLE
Synth is unable handle security/base-audit properly

### ISSUE THREAD

**Issue by yasuhirokimura** [jrmarino/synth#116]
When `security/base-audit` was installed `synth upgrade-system` always rebuilt it even though it was not changed at all. And yesterday this port was updated from 0.1 to 0.2 so I tried again. `Synth upgrade-system` rebuilt it as before but after command was completed installed package was still version 0.1. `security/base-audit` itself is quite small and simple port. It has only one RUN_DEPENDS, no OPTIONS, no configure and build step, and installs only one shell script into `${PREFIX}/etc/periodic/security`. So I can't find the reason why `synth` is unable to handle this port properly.

Conditions are as following:

OS: FreeBSD 11.1-RELEASE amd64
Synth: 2.02
Revision of ports tree: 458882

**Comment by jrmarino** [comment]
doesn't sound right.  
You're relying on pkg(8) to tell synth what to upgrade.
When in doubt, do it manually.  In other words, 

1.  "synth force" security/base-audit 
2.  rebuild synth repository
3. "pkg remove" base-audit
4. "pkg install" base-audio (from local repository)

remember, synth can build base-audit all day long, but if pkg(8) fails to recognize it during upgrade, that's not synth's fault.  If anything, it's pkg(8).  Synth only builds stuff.  the package management (things installed on the server) isn't done by synth.
