### ISSUE TITLE
feature request: make options for specific ports in list

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#117]
Hello!

I use Synth to build and update the ports on my host system as well as building ports from a list for my jails.
I'm using the same profile for this (and therefore the same make file). I generally don't need a different profile / make file for the different jails and this way it is very easy to automate via cron for me ('portsnap cron update && ezjail-admin update -P && env TERM=dumb synth just-build /usr/local/etc/
synth/LiveSystem-JailPorts.txt && env TERM=dumb synth prepare-system`).
However, there are certain ports which I would like to build with different dependencies (e.g. build www/h2o with openssl-devel instead of libressl).
It would be great (if even possible) to be able to set port specific make options, e.g.:

```
databases/mariadb102-server
databases/mariadb102-client
devel/py-pip@py27
devel/py-pip@py36
lang/go
lang/php71
lang/php71-extensions
www/h2o DEFAULT_VERSIONS+= ssl=openssl-devel
www/uwsgi@py36
```

This is my `LiveSystem-make.conf`:
```
#MAKE_JOBS_UNSAFE=yes
DEFAULT_VERSIONS= mysql=10.2m
DEFAULT_VERSIONS+= ssl=libressl
#DEFAULT_VERSIONS+= ssl=openssl-devel
#DEFAULT_VERSIONS+= ssl=openssl
DEFAULT_VERSIONS+= php=7.1
#DEFAULT_VERSIONS+= php=7.0
DEFAULT_VERSIONS+= python=3.6
```

And additionally: It would be great to be able to comment out jails in the list:
```
#lang/python2
lang/python3
```

**Comment by jrmarino** [comment]
you can't mix openssl selections (they conflict; they can't be installed together). The only way is with a different profile to create a separate repository.  It's a freebsd-ports-collection limitation.

Specific port options can be set through [profile]-make.conf (a per-profile setting).  Obviously that would be static.

**Comment by jrmarino** [comment]
as for commenting out lists, I could I would suggest piping the list through sed, e.g. "s/#/d", producing either stdout or a temporarily list.

**Comment by bax-** [comment]
That's what I kind of guessed but I hoped there would be a way around having multiple repositories (with all the associated things).

About commenting out: That would work, right.
Might be something worth adding anyway.

Thanks!

**Comment by jrmarino** [comment]
for openssl, you just have to choose.
We have libressl as the default for dports, and we lost about 20-25 ports because those require openssl or otherwise don't build on libressl.  However, the DEFAULT_VERSIONS setting can switch it back to openssl.  I build both (openssl for port updates, libressl for distribution).  The only way it works is two separate repositories.  It's the same for any setting where there is a default and options (e.g. mysql, postgresql, etc) ...

**Comment by bax-** [comment]
If I create a new profile for this (build ports with different SSL versions) – is it sufficient to just change the Packages directory for this profile and keep all the other configurations the same?

**Comment by jrmarino** [comment]
pretty much, yes.  Obviously you'd have a unique [profile]-make.conf too.

**Comment by bax-** [comment]
yes, that much I realized.
Thanks!

**Comment by UrsusDominatus** [comment]
Is there any chance to get "ignore obsolete ports" option during build process? I have cron driven update process scheduled at nighttime and often need to start build process manually when I see "obsolete ports detected and nothing rebuilt" message. If synth simply skips ports with obsolete options, most of the ports will be rebuilt at time when update is scheduled.

Now it can be somewhat continuous process to build everything that need to be updated (especially if gcc and/or clang need to be recompiled) in time when it is not desired to make excessive cpu resources pressure.
