### ISSUE TITLE
synth and "flavors"

### ISSUE THREAD

**Issue by ivr588** [jrmarino/synth#120]
Hi,

I'm trying to feed a list of ports to synth using:
`synth just-build /home/john/ports.2.build`
the error I'm getting is:
`Error: port origin 'devel/py-asn1crypto' is not recognized.`
`Perhaps you intended one of the following port flavors?`
`   - devel/py-asn1crypto@py27`
`   - devel/py-asn1crypto@py36`
/etc/make.conf looks like this:
`DEFAULT_VERSIONS+=python=2.7`

How can I overcome this error? it's entirely a possibility that i've misunderstood "flavors"

many thanks

**Comment by jrmarino** [comment]
edit ports.2.build file and add either "@py27" or "@py36" to the end of the "devel/py-asn1crypto" line (no spaces).

Basically your name is ambiguous.  synth doesn't know if you want the py27 flavor or the py36 flavor, so you need to specify that.

**Comment by ivr588** [comment]
ok i'll try that, thank you.

**Comment by ivr588** [comment]
all sorted :D thanks again
