### ISSUE TITLE
feature request: jails support

### ISSUE THREAD

**Issue by okapia** [jrmarino/synth#122]
It'd be nice to have somewhat cleaner support for jails. I use a nullfs mount to make the Synth repo available in my jails and use synth to build packages for the jails. It sort-of works to do things like:

    synth status $(pkg -j mail query %o)

And similarly for just-build but how about allowing synth -j mail status.

Only other thing that bothers me is the "Please change the current directory" message. What is synth doing in the current directory anyway? It'd be less code to try chdir("/tmp") than to print the error.

But thanks for synth. I've used it for some time and have been very happy with it.

**Comment by jrmarino** [comment]
The operating system won't null mount a directory properly if synth was launched from that directory or one of its subdirectories.  It's an OS limitation.

If the cwd is the real distfiles directory and you launch synth, the null mount malfunctions when it's mounted to /distfiles internally.

just use 
> (cd / && synth .... )

**Comment by okapia** [comment]
Thanks for your explanation on that.
