### ISSUE TITLE
feature request: exit with non-zero when make config is needed

### ISSUE THREAD

**Issue by Ximalas** [jrmarino/synth#123]
It would be very nice for scripting purposes if synth exits with a non-zero value when `make config` is needed for some port. To give some context, here is the shell script I use for running synth:

```shell
#!/bin/sh

cd /

for p in `/usr/bin/make -C /usr/ports/local -V SUBDIR`; do
  LOCAL_METAPORTS="${LOCAL_METAPORTS} local/${p}"
done

/usr/local/bin/synth rebuild-repository            || exit
/usr/local/bin/synth just-build ${LOCAL_METAPORTS} || exit
/usr/local/bin/synth rebuild-repository            || exit

# EOF
```
This first invocation of rebuild-repository is probably redundant, but in my misbelief it might serve as a safeguard. All I want is to terminate the script as early as possible to catch things like `make config` or other errors.

**Comment by jrmarino** [comment]
How would synth do this?  "make config" isn't required for synth.  It assumes default options if no configuration is set (and "no config" is the rule, not the exception).

**Comment by Ximalas** [comment]
Assume I have altered the options. Say turned off NLS or made other adjustments. Whenever the options change, I have to rerun make config.

**Comment by jrmarino** [comment]
well, synth already detects this situation and stops with a fatal message (but not with an non-zero exit)

**Comment by Ximalas** [comment]
Yes, I know. Maybe I should grep for the error mesage and halt my script.

**Comment by jrmarino** [comment]
well, that would the quickest for you.  I'm not opposed to changing the exit status (once I figure out how to do that) but it won't necessarily be available in the short term.

**Comment by Ximalas** [comment]
Thank you for your consideration and thank you for creating synth in the first place.

**Comment by Ximalas** [comment]
Maybe you could sprinkle Ada.Command_Line.Set_Exit_Status(1) throughout synth, and possibly return all the way to the OS.

sysexits.h stops at 78, and if you/we want unique values for each case, we could start at, say 81. That way the returned value will reveal where the last call to Set_Exit_Status was made. I'm assuming nothing else will call Set_Exit_Status.

**Comment by Ximalas** [comment]
The following patch was accepted by the compiler.

```diff
diff --git a/src/portscan-packages.adb b/src/portscan-packages.adb
index 2386bc5..8366592 100644
--- a/src/portscan-packages.adb
+++ b/src/portscan-packages.adb
@@ -1,12 +1,14 @@
 --  This file is covered by the Internet Software Consortium (ISC) License
 --  Reference: ../License.txt
 
+with Ada.Command_Line;
 with PortScan.Ops;
 with Signals;
 with Unix;
 
 package body PortScan.Packages is
 
+   package CLI renames Ada.Command_Line;
    package OPS renames PortScan.Ops;
    package SIG renames Signals;
 
@@ -889,6 +891,7 @@ package body PortScan.Packages is
    begin
       rank_queue.Iterate (Process => check_port'Access);
       if fail_count > 0 then
+         CLI.Set_Exit_Status (1);
          TIO.Put (LAT.LF & "A preliminary scan has revealed the cached " &
                  "options of");
          if fail_count = 1 then
```

I'm in the process of using the modified synth on my builders. More details to follow.

**Comment by Ximalas** [comment]
Success!

```text
# synth upgrade-system; echo Exit Status $?
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
Cached options obsolete: lang/mono

A preliminary scan has revealed the cached options of one port are
obsolete.  Please update or remove the saved options and try again.
  e.g. make -C /usr/ports/lang/mono config
  e.g. make -C /usr/ports/lang/mono rmconfig
Unfortunately, the system upgrade failed.
Exit Status 1
```

**Comment by jrmarino** [comment]
Thanks.  I'm not to sure when the next release will be.  I have to improve the flavor generation index using the cheat method that poudriere uses first.

**Comment by Ximalas** [comment]
I've made another patch for propagating the failure of any build to synth's exit status.

```diff
diff --git a/src/portscan-buildcycle-ports.adb b/src/portscan-buildcycle-ports.adb
index 057ce48..4ec9008 100644
--- a/src/portscan-buildcycle-ports.adb
+++ b/src/portscan-buildcycle-ports.adb
@@ -1,8 +1,12 @@
 --  This file is covered by the Internet Software Consortium (ISC) License
 --  Reference: ../License.txt
 
+with Ada.Command_Line;
+
 package body PortScan.Buildcycle.Ports is
 
+   package CLI renames Ada.Command_Line;
+
    ---------------------
    --  build_package  --
    ---------------------
@@ -240,6 +244,10 @@ package body PortScan.Buildcycle.Ports is
          result := generic_execute (id, command, timed_out, time_limit);
       end;
 
+      if not result then
+         CLI.Set_Exit_Status (1);
+      end if;
+
       --  Reopen the log.  I guess we can leave off the exception check
       --  since it's been passing before
```

**Comment by jrmarino** [comment]
I don't think this is a good approach.
It means if any package, even out of 28,000 packages, fails to build _for any reason_ then synth will exit with a 1 error code.  But this is misleading. 

If the goal is to detect a single (or or more) build failures, then hooks would be the recommended approach.

**Comment by Ximalas** [comment]
I defer to your judgement.

**Comment by Ximalas** [comment]
I saw the release of 2.03, and I have learned enough, but not much, Ada to patch my own systems. I think it's time to close this issue.
