### ISSUE TITLE
Using portdowngrade with synth (FreeBSD)

### ISSUE THREAD

**Issue by mkastner** [jrmarino/synth#126]
On FreeBSD (using quarterly) I had to downgrade the current mariadb101-server since it doesn't build because of of vulnerability problem. So used portdowngrade to revert back to a version that actually builds.

However, since portdowngrade does not write to the ports tree anymore, in this case (propably because that was the directory portdowngrade was called from) it put the downgraded port files into

`/usr/ports/mariadb101-server`

Which is a good thing. However synth doesn't know about this location (how could it) and still tries to install from

`/usr/ports/databases/mariadb101-server`

Is there a way to configure synth to also search in other paths outside

`/user/ports/*`

**Comment by jrmarino** [comment]
But why not do the expected and remove databases/mariadb-server and then move ./mariadb-server folder to databases/ ?

portdowngrade is a horrible approach that probably fails oftens.  The ports tree is constantly changing and often changes are made as units, and reverting a single port of a unit change would result in breakage.  It's assuming a big risk (also interesting that in this case, an older version is less vulnerable than the latest version.  are you sure?)

But going with the assumption that you A) already know what a terrible idea portdowngrade is and B) you realize that you have a good chance that the downgraded port won't build (especially if you go back far in time) then you should finish the replacement manually.  There's no reason to keep the current port and have the downgraded version in a different location.  It doesn't solve anything.

**Comment by jrmarino** [comment]
closing (no response in 2 weeks)
