### ISSUE TITLE
misc/esniper build fails

### ISSUE THREAD

**Issue by benlaurie** [jrmarino/synth#130]
If I run `ENTERAFTER=patch synth test misc/esniper` and then run `make` in the ensiper port, the config log shows:

```
configure:3451: cc -o conftest -I/usr/local/include -O2 -pipe  -fstack-protector -fno-strict-aliasing   -fstack-protector conftest.c -L/usr/local/lib -lcurl  >&5
/usr/bin/ld: warning: libnghttp2.so.14, needed by /usr/local/lib/libcurl.so, not found (try using -rpath or -rpath-link)
```

running `env LD_LIBRARY_PATH=/usr/local/lib make` works fine...

**Comment by jrmarino** [comment]
sounds like a problem with the curl port, not synth.
in other words, curl files to link with -Wl,-rpath and fails to use ldconfig (guessing without looking).
That has nothing to do with synth.  right?

**Comment by benlaurie** [comment]
it builds fine not under synth, so there's something odd going on with synth, it seems to me...

**Comment by jrmarino** [comment]
"builds fine not under synth" is completely irrelevant, and not surprising as ldconfig has probably been set by a another unrelated port.  Synth has clean, uncontaminated jails. Your "not under synth" environment is completely contaminated (from the point of view of reproducible builds) and not reproducible by anybody not using your machine.

There's nothing going on with synth.

Every time some port maintainer makes a mistake, I hear complaints that synth is malfunctioning.  Maybe someday people will start blaming the ports tree first. dunno if/when that will happen though.

**Comment by benlaurie** [comment]
I'd be happy to blame and/or correct the port if I understood what it is doing wrong - probably if you want people to blame ports first, more info on how to diagnose them would help, not everyone understands this stuff inside out.

How should curl use ldconfig?

**Comment by jrmarino** [comment]
> not everyone understands this stuff inside out
Right, so why would they immediately assume a build tool is at fault before the much more obvious explanation of a bad port?  Synth is not undergoing changes, so if it's working for months the other reason to suspect it are if the tree undergoes a major change (as seen by recent /etc/rc.d error message)

Assuming curl is the thing at fault (I was just guessing), the first mistake is not linking with -Wl,-rpath.  The use of ldconfig is for ports that don't link properly.
see: https://www.freebsd.org/doc/en/books/porters-handbook/book.html
section 6.3

Alteratively,  misc/esniper might be missing an explicitly linkage to libnghttp2.  Maybe curl is being built with a non-often used option that esniper isn't expecting.  In any case, one of the 2 ports is the most likely culprit.  Synth is just reported a normal build error.

**Comment by benlaurie** [comment]
Hmm. Well, curl does use ldconfig.

misc/esniper only depends on curl - adding a dependency to libnghttp2 does not appear to make any difference, but in any case I am confused: are you saying that ensiper ought to include all of curl's dependencies? Because there are a lot, and only libnghttp2 appears to be a problem...

BTW, the dependency in curl on libnghttp2 is part of its default config.

**Comment by jrmarino** [comment]
you need to report this to esniper maintainer.  It's not a synth issue.

**Comment by jrmarino** [comment]
moreover, the esniper maintainer should be able to reproduce with at least synth and most likely poudriere if he has the same settings as you do.

**Comment by jrmarino** [comment]
for more info, linkers nowdays require explicit linkages instead of recursive linkages.
So the older linker may have seen the libcurl links to libnghttp2 and automatically pulls in it, while gnu and maybe the latest elftools linker requires an explicit "-lnghttp2" flag on esniper.

**Comment by jrmarino** [comment]
i'm guessing esniper will build again with v2.05.
The /etc/rc.subr error looks like it means ldconfig wasn't working anymore.  So curl was specifying it, but no action was being taken.  Which means it was technically a synth problem after all (which means I owe you an apology but I didn't recognize it as the other /etc/rc.subr issues already mentioned in previous PRs)

**Comment by benlaurie** [comment]
I am indeed being hit by that. When are you expecting to release 2.05?

**Comment by jrmarino** [comment]
it's out.  you can build it manually if you want. (change version number in ports-mgmt/synth, "make makesum" and build it.  Not sure when eric will push the new version.

**Comment by benlaurie** [comment]
2.05 does indeed fix the problem.
