### ISSUE TITLE
Should 'build' remove invalid packages when rebuilding repo?

### ISSUE THREAD

**Issue by felix** [jrmarino/synth#131]
I often run `synth just-build ... && synth rebuild-repository` because if I run just `synth build ...` the repository keeps a bunch of invalid packages. Should [synth.adp line 188](https://github.com/jrmarino/synth/blob/befb3eef4ee65dcc0220c04027f8c49dd1a19e40/synth.adb#L188) perhaps be:
```
PIL.rebuild_local_respository (remove_invalid_packages => True) and then
```
or am I just doing it wrong?

**Comment by jrmarino** [comment]
no, the line is correct.   Trying to autoremove packages other than repository generation causes all sorts of issues and to address those issues, the removal of invalid packages was intentionally limited to the repository generation step.  It's not an oversight.
