### ISSUE TITLE
[feature request] Please aggregate errors and report them in the end

### ISSUE THREAD

**Issue by yurivict** [jrmarino/synth#132]
Currently synth stops immediately when some error occurs in one of port scans. Port scans can take a long time, and rerunning them after each error only to find another one is unreasonably time consuming.

Proposed fix: maintain the list of errors, and only report them together in the end.

Thanks!

**Comment by jrmarino** [comment]
sorry, a port scan error is fatal.  It is not possible to continue.  The problem has to be fixed immediately.  It shouldn't happen on a stock tree (unless somebody commits an error) and maintainers are expected to fix errors synth detects.

**Comment by yurivict** [comment]
> sorry, a port scan error is fatal. It is not possible to continue.

If the port is a leaf port, why is the error for this port fatal for the rest of the port scan?

**Comment by jrmarino** [comment]
How is synth supposed to know that it's a leaf port?
The scan is expected to be 100% integrity.  If a flaw is found, synth can't trust anything and most stop, otherwise corrupt data will cause issues later.  

It is fatal.

**Comment by yurivict** [comment]
Just consider the rest of the scan not 100% clean after the first error, report the list of errors in the end, and ask the user to fix them and rerun.

**Comment by jrmarino** [comment]
I don't know how many ways to say it can't be done.  Certain errors cause infinite loops.
The average user can't fix it anyway.  The tree is corrupt.
The only case where this is a problem is when a port developer is testing a port they're working on, and they are the one that likely caused the bug.  How many scan errors would there be in that case anyway?
