### ISSUE TITLE
synth messes up the terminal state when Ctrl-C is pressed

### ISSUE THREAD

**Issue by yurivict** [jrmarino/synth#133]
Ctrl-C is commonly expected to cause a graceful program exit. Yet, the terminal state changes, and reset(1) is needed to restore it.

Version 2.05.

**Comment by jrmarino** [comment]
whoa!  read the man page.
control-Q is supposed to be used, not control-C.
Control-C cannot be trapped due to how the workers operate.

**Comment by jrmarino** [comment]
https://www.freebsd.org/cgi/man.cgi?query=synth&sektion=1&manpath=freebsd-release-ports

search for "graceful exit"
