### ISSUE TITLE
DEFAULT_VERSIONS=gcc=8 still builds with gfortran7

### ISSUE THREAD

**Issue by mexas** [jrmarino/synth#134]
Might be nothing to do with synth, just my confusion with FreeBSD ports builds.
```
# grep DEFAULT_VERSIONS /usr/local/etc/synth/LiveSystem-make.conf
DEFAULT_VERSIONS=gcc=8
```
```
synth build net/mpich
```
results in using gfortran7:
```
--------------------------------------------------
--  CONFIGURE_ENV
--------------------------------------------------
PKG_CONFIG=pkgconf
F77="gfortran7"
FC="gfortran7"
```
What else do I need to force using of gfortran8 in synth builds?

Thanks

Anton

**Comment by jrmarino** [comment]
as far as I can tell from the ports tree code, setting gcc=8 on DEFAULT_VERSIONS should do it. That should set GCC_DEFAULT to 8 which is what https://svnweb.freebsd.org/ports/head/Mk/Uses/fortran.mk?revision=454428&view=markup uses.
Does the log should DEFAULTS_VERSIONS=gcc=8 is part of the make.conf ?

**Comment by mexas** [comment]
Here's the full build log:

[https://seis.bristol.ac.uk/~mexas/net___mpich.log](https://seis.bristol.ac.uk/~mexas/net___mpich.log)

Re make.conf:

```
# cat /etc/make.conf 
#DEVELOPER=yes
#FFLAGS+= -O2 -pipe -march=bdver2 -mtune=bdver2
#FFLAGS+= -funroll-loops --param max-unroll-times=4 -ftree-vectorize
#FFLAGS+= -g
#DEFAULT_VERSIONS=gcc=8
```
I moved all /etc/make.conf stuff explicitly into synth make.conf,
although I understand from the manual, that /etc/make.conf is
always appended to synth make.conf.

```
# cat /usr/local/etc/synth/LiveSystem-make.conf 
DEVELOPER=yes
FFLAGS+= -O2 -pipe -march=bdver2 -mtune=bdver2
FFLAGS+= -funroll-loops --param max-unroll-times=4 -ftree-vectorize
FFLAGS+= -g
DEFAULT_VERSIONS=gcc=8
```

**Comment by jrmarino** [comment]
that's not what I asked.
Look at the build log, and ensure DEFAULT_VERSIONS=gcc=8 is on it.
in other words, if your profile is not LiveSystem then it's not getting in the jails make.conf.

**Comment by jrmarino** [comment]
but i see now you posted a link to log and it is indeed there

**Comment by jrmarino** [comment]
do you have an unaltered ports tree?
Because according to the code, what you've done should be working.  It's acting like DEFAULT_VERSIONS is getting undefined or something.

**Comment by jrmarino** [comment]
(and for the record, it's probably not a synth issue.  the definitions are getting to the jail's make.conf)

**Comment by mexas** [comment]
I'm an idiot, I had net/mpich/Makefile.local with DEFAULT_VERSIONS.
Sorry for wasting your time.
