### ISSUE TITLE
Long-running builds get killed with SIGKILL

### ISSUE THREAD

**Issue by int19h** [jrmarino/synth#139]
(Context: FreeBSD 11.2, Synth installed from Q4 port tree)

Building large packages on a slow machine (netbook) - the kind that takes >6 hours to build - seems to be sporadically failing because of the build process getting killed with SIGKILL. Which is to say, looking at the build log for that package, it just ends abruptly in the middle of a compile with "signal 9". The reason why I say "sporadically" is because the same packages then succeed after a rebuild with no changes whatsoever. 

Two examples I ran into so far are lang/rust and java/eclipse.

The first question that comes to mind is, is there some kind of timeout in Synth that stops a package build if it goes for too long? I couldn't find anything along these lines on the man page or in synth.ini, but I could see why it might have a feature like that to avoid stalling a build queue for e.g. `synth everything`.

The machine was not interacted with during the build in any way, and prior to the build, was running nothing other than the services in the base system (rc.conf: sshd, moused, ntpd, powerd), so I can't come up with any other explanation.

Also, there seems to be a [similar bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222549) in FreeBSD tracker from a while ago that may be related. It was closed because the person who filed it also saw the build succeed after retrying, so they never looked into it further. Curiously, it was also about lang/rust! I'm not sure if that's just because it takes so long to build in general, or there's something special about it.

**Comment by jrmarino** [comment]
There is a watchdog but it's clear when synth kills the build.  The last line on the log says the build froze and synth killed it.

rust is kind of flakey.  That signal 9 issue happens on other platforms too.  I've seen it on dragonfly.  Mono also does it.  It's not a synth issue per se.

**Comment by int19h** [comment]
I'm curious as to what could be the root cause. The same packages do build with `make install` from the ports, so clearly the system *is* capable of building them. What's different in the Synth environment?

I notice that various threads discussing Synth mention that it does need substantial amounts of memory - could that be related? Given that this is a netbook with a measly 4Gb of RAM... Should I add more swap to rectify?

**Comment by int19h** [comment]
That was indeed the problem - now I'm able to build everything that was mysteriously failing before. Thanks!
