### ISSUE TITLE
Feature Request: configuration option for just-build list file

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#14]
Maybe it's too specific to my needs or maybe there is a more flexible / universal solution.

I have several ports I need to be built for my jails (because of custom options or to have the latest version available).

If there was an option like "repository just-build" with an empty default conf file that also allowed comments that would be pretty nice.

The idea would be to have these ports also built if needed when `synth upgrade-system` or `synth rebuild-repository` were called (but not installed).

**Comment by jrmarino** [comment]
I think you are thinking too complex.
All you need a complete list of ports that you want in the repository and just build that.  You would not use upgrade-system or rebuild-repository here.  That is for the live system, not what you are trying to do.

with a constant port list, you "just-rebuild" the same file over and over and it will incrementally build what changed.

Comments are out of scope, if you really need comments I'd suggest have a script that filters out a raw file and produces a clean one.

**Comment by bax-** [comment]
Sorry: so would a just-build be sufficient to make the ports available or will I need to build or rebuild after that?

**Comment by jrmarino** [comment]
the packages would be built, but the repository would be old.  It would need something to regenerate it.  Maybe we need a command that does that.

**Comment by bax-** [comment]
Oh I thought rebuild-repository did that

**Comment by jrmarino** [comment]
rebuild-repository is just upgrade-system minus the installation.  It's host-system based.  If you run it, it will build whatever is missing from the system first.

**Comment by jrmarino** [comment]
remember, the target audience was single machine, so the use case of a repository other than what the host system needs was neglected a bit.

**Comment by bax-** [comment]
Just for clarification: will rebuild-repository update the repository to contain the ports from the list file even if the system is up to date?

Sorry if my questions are stupid.

I totally understand that passing ports to jails isn't what Synth was built for. I just could imagine that this is a great tool for people that think poudriere is too much overhead for them.

**Comment by jrmarino** [comment]
> Just for clarification: will rebuild-repository update the repository to contain the ports from the list file even if the system is up to date?
I think it does, yes

> I totally understand that passing ports to jails isn't what Synth was built for. 
It should be suitable for that, we just need to polish some more

> I just could imagine that this is a great tool for people that think poudriere is too much overhead for them.
That was a main factor.  also, synth was designed to be used without having to configure at all so people could use it out of the box.  The "create jail", "create port tree" prerequisite for poudriere was a big killer I think.

**Comment by jrmarino** [comment]
I don't see anything more interesting here, so I'm going to close this one.
