### ISSUE TITLE
No explanation for why a port is on the update list

### ISSUE THREAD

**Issue by myfreeweb** [jrmarino/synth#140]
I have replaced `mesa-libs` and `mesa-dri` with a custom port [`mesa-dev`](https://github.com/myfreeweb/freebsd-ports-dank/tree/master/graphics/mesa-dev). It's replaced as a dependency in all ports. `mesa-libs` is NOT installed. All dependent ports are rebuilt (*nothing* in `06*log` mentions `mesa-libs` as a dependency anymore!!!) yet `mesa-libs` itself still appears in that log when checking `status`:
 
```
% < /var/log/synth/06_obsolete_packages.log grep mesa
Current graphics/mesa-libs package depends on libdrm-2.4.93,1.txz, but this is a different version than requirement of libdrm-2.4.96,1.txz (from graphics/libdrm)
```

Is there any way to find out why exactly it's getting on the build list?

(Also would be nice: a "never build these ports" block-list that would abort the build if the listed ports are on the list.)

**Comment by jrmarino** [comment]
"check status" is querying your system status.  It's using pkg(8) to see what is installed on your system.  Obviously you've got mesa-libs installed on your system.

You shouldn't be using this command.  It's was supposed to be a convenience command to build packages for the localhost (as opposed to creating a repository many systems could use).

**Comment by jrmarino** [comment]
In other words, if you want a build list, create a file and give that to synth.  Don't use "status" at all.

**Comment by myfreeweb** [comment]
Yeah, definitely:

```
% pkg info mesa-libs
pkg: No package(s) matching mesa-libs
```

pkg wants to install it as a dependency of several packages if I try `pkg upgrade`, sure, but it's not installed. I guess some `pkg query` things might be returning it because of that :(

I do want to just conveniently upgrade the packages on the local machine. Welp, I guess I'll have to create a list anyway..
