### ISSUE TITLE
Ensuring Synth has a package for everything that is installed on the system

### ISSUE THREAD

**Issue by int19h** [jrmarino/synth#141]
Note: this is not a bug, just can't quite wrap my head around all the concepts that are involved after reading the docs, and looking for some help.

Long story short, I'm trying to convert an existing FreeBSD install, with a bunch of stuff that was installed from ports via `make install`, to Synth. I would like to ensure that *everything* on the system comes from Synth - i.e. every package that is installed on the system, should be in the Synth package repo, and should be installed from that repo.

For new packages, this is automatic, of course. But I need to do something about the ones I already have installed. Looking at Synth manpage and options, I'm not quite sure how to bootstrap this properly. If I understand everything right, what I basically need is something like `synth force ...`, where `...` is the list of all packages that are already installed on the system. 

Now, it seems like I should be able to use a `build.list` file, after using something else to generate a list of installed packages. But I can't figure out how to do that properly, either - `pkg info` lists all installed packages, but the package names include the version number and exclude the category, and then there's the package description that needs to be trimmed. Is there any straightforward way to get the installed package list in the format that Synth can readily consume - i.e. category/port, one per line? Or is there any option that I've missed in Synth itself that would do this step automatically, without having to script it?

**Comment by jrmarino** [comment]
read this: https://www.dragonflybsd.org/docs/howtos/HowToDPorts/#index4h1 (bullet-proof).
That's how you end up with a list of "prime" packages, the ones that pull in the rest.  All you need are those primes.  This technique is often used to upgrade between major OS versions.  Should be all you need.

**Comment by int19h** [comment]
Just what I needed, thank you!
