### ISSUE TITLE
Problem with new profile

### ISSUE THREAD

**Issue by Peter2121** [jrmarino/synth#144]
I successfully built a repository with default settings. Now I created a new profile to build a repository with some custom settings. I begin with a copy of default make.conf and blank ports configuration, but I cannot build packages being on this new profile. Building all ports is failed with the following message:

```
--------------------------------------------------------------------------------
--  Phase: build-depends
--------------------------------------------------------------------------------
===>   indexinfo-0.3.1 depends on file: /usr/local/bin/ccache - not found
===>   indexinfo-0.3.1 depends on package: /packages/All/ccache-3.4.3.txz - not found
===>   USE_PACKAGE_DEPENDS_ONLY set - not building missing dependency from source
*** Error code 1

Stop.
make: stopped in /xports/print/indexinfo
```
I don't understand USE_PACKAGE_DEPENDS_ONLY parameter and don't see where is it set.

**Comment by jrmarino** [comment]
okay, first thing's first: this is a not a bug in synth, but a user error.

secondly, you say you start with "default make.conf and blank ports configuration".  I am going to need to see those.  Unless "blank ports configuration" means all the options are defaults (no options saved).

My guess is your make.conf is messed up.   so paste it.

**Comment by Peter2121** [comment]
There is nothing in port's configuration directory.
The only uncommented line in profile's makefile is:
`DISTDIR = /data/distfiles`
The directory exists, it was used by the default profile, there are distribution files inside.
I'm almost sure it's a configuration problem, but I cannot find the cause :(

**Comment by jrmarino** [comment]
Why would you set DISTDIR when it's supposed to be configured via "synth configure" ?

and when you say "makefile", you mean [PROFILE]-make.conf right?

**Comment by jrmarino** [comment]
where did you get the make.conf anyway?

**Comment by Peter2121** [comment]
Yes, it is [PROFILE]-make.conf.
I've just created another profile 'from scratch' and I could build some packages without errors.
So I think that somewhere the profile was corrupted, but I have no idea why and where.
Sorry for noise.
