### ISSUE TITLE
REPLICANT.SCENARIO_UNEXPECTED following FreeBSD 12.0 Upgrade

### ISSUE THREAD

**Issue by GitHubinat0r** [jrmarino/synth#145]
Following the upgrade to FreeBSD 12.0, I get the below error. I am *not* using jails. 

If you need any further output, please let me know.

```
# synth install net/mosh
Builder mounts detected; attempting to remove them automatically ...
Dismounting successful!
Regenerating flavor index: this may take a while ...

raised REPLICANT.SCENARIO_UNEXPECTED : /usr/sbin/mtree -p /usr/obj/synth-live/SL09/var -f /etc/mtree/BSD.var.dist -deqU => failed (exit code not 0)

```

**Comment by GitHubinat0r** [comment]
Also, I uninstalled all the ports and reinstalled them following the upgrade. (In case that helps rule out anything.)

**Comment by GitHubinat0r** [comment]
Not sure if this is directly relevant, but the 12.0 release notes:

> The ntpd(8) utility has been updated to allow being run as a non-root user.

https://www.freebsd.org/releases/12.0R/relnotes.html

**Comment by jrmarino** [comment]
it may be that ntpd needs to be added add to the default users.  Unfortunately I'm hitting the road right now and will be out of pocket all weekend.

You can probably modify /etc/mtree/BSD.var.dist to remove reference to ntpd to get around it for now.

**Comment by GitHubinat0r** [comment]
I'll try to tinker around with it and let you know what works. Thanks for the suggestions!

**Comment by GitHubinat0r** [comment]
Commenting out the ntp line in /etc/mtree/BSD.var.dist allowed me continue with the port install. I'll post back if it failed along the way.

During the upgrade I think I recall the ntpd user being removed, but the group still exists in /etc/group. Again, I think it's related to the changes to how ntpd is run in FreeBSD 12.0 and I'm one of the few crazy enough to upgrade a system a few days after release.

**Comment by zamzamdesu** [comment]
Happened to me too and I have a standard installed. It looks that the synch of the passwd files was not correct as uid 123 was not being recognized as ntpd users.
Worked after running: ` /usr/sbin/pwd_mkdb -p /etc/master.passwd`

**Comment by GitHubinat0r** [comment]
Running the pwd_mkdb command above fixed it. Thanks!

**Comment by utrenkner** [comment]
Same here! Works after following @zamzamdesu 's suggestion!

**Comment by mfoacs** [comment]
Same here, thanks!
