### ISSUE TITLE
synth can't distinguish between armv6 and armv7 FreeBSD systems.

### ISSUE THREAD

**Issue by daemonblade** [jrmarino/synth#147]
On FreeBSD-12/arm with armv7 binaries, the file(1) command returns identical output as that for FreeBSD12/arm with armv6 binaries; and so get_arch_from_bourne_shell() always "armv6".

The only way to tell the difference is from "readelf -A" and look for the **Tag_CPU_arch** line, which returns the actual value:
```
8:01pm> readelf -A /bin/sh
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: arm1176jzf-s
  Tag_CPU_arch: ARM v6
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: 16-bit Thumb
  Tag_FP_arch: VFPv2
  Tag_ABI_PCS_GOT_use: direct
  Tag_ABI_PCS_wchar_t: wchar_t size 4
  Tag_ABI_FP_denormal: Sign Only
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte align
  Tag_ABI_align_preserved: 8-byte align
  Tag_ABI_enum_size: 32-bit
  Tag_ABI_VFP_args: AAPCS (VFP variant)
  Tag_ABI_optimization_goals: Speed
  Tag_ABI_FP_16bit_format: IEEE 754
  Tag_conformance: 2.09
  Tag_Virtualization_use: TrustZone
```

**Comment by jrmarino** [comment]
let's say we implement a routine to execute readelf and return either "armv6" or "armv7" based on the outputted text.  Wouldn't there still be an issue with determine_package_architecture() ? (specifically the suffix() and newsuffix() subfunctions).

**Comment by jrmarino** [comment]
lazy question: is armv6 even worth supporting?

**Comment by daemonblade** [comment]
> let's say we implement a routine to execute readelf and return either "armv6" or "armv7" based on the outputted text. Wouldn't there still be an issue with determine_package_architecture() ? (specifically the suffix() and newsuffix() subfunctions).

If you have a patch (or a dev-branch on github), I can give it a try.

> lazy question: is armv6 even worth supporting?

It's still the default for 11-STABLE/arm and its ports.

And while armv7 is the default for 12-STABLE/arm, I using 12-STABLE/armv6 as emulators/qemu-user-static doesn't quite work as yet for armv7. It's impossible to build armv7 ports natively on a dinky RPI2, and impossible to do it on a grunty amd64 with a broken qemu-user-static.

**Comment by jrmarino** [comment]
okay, so the answer is determine_package_architecture definitely has to support armv7 (it can't build armv7 packages and name them as armv6).  See 

https://github.com/freebsd/pkg/blob/005fe61d11d0c40f5462ddacef791385eee68471/libpkg/pkg_elf.c#L676-L682

**Comment by jrmarino** [comment]
All I did was confirm that this patch compiles.
Can you test it to see if the code does what we intend?

**Comment by daemonblade** [comment]
I'll let you now when I get around to testing it this weekend (a bit busy at the moment).

Thanks!

**Comment by daemonblade** [comment]
I've tried the code at _master_; unfortunately it doesn't quite work. On startup, I keep getting:
```
ARM_version_7 error: expected Tag_CPU_arch not found
```

My fumbling attempts of trying to figure out what's wrong have only yielded the fact that replicant-platform.adb line 87, `contents` is an empty string. I couldn't figure out why that was the case.

**Comment by jrmarino** [comment]
contents is empty?  That means
```
/usr/bin/readelf -A /bin/sh
```
is failing to return a result.

Try something like
```
env ENTERAFTER=extract synth test editors/nano
```
when you get the prompt, type in "/usr/bin/readelf -A /bin/sh" and post the output.

**Comment by daemonblade** [comment]
Here's the session output
```
1.onyx:/xbuilds,8:39am# env ENTERAFTER=extract synth test devel/ccache
ARM_version_7 error: expected Tag_CPU_arch not found
ARM_version_7 error: expected Tag_CPU_arch not found
ARM_version_7 error: expected Tag_CPU_arch not found
Stand by, building pkg(8) first ... done!
ARM_version_7 error: expected Tag_CPU_arch not found
ARM_version_7 error: expected Tag_CPU_arch not found
ARM_version_7 error: expected Tag_CPU_arch not found
After inspection, it has been determined that there are no packages that                                                                              require rebuilding; the task is therefore complete.
Starting interactive build of devel/ccache                                                                                                            Stand by, building up to the point requested ...
ARM_version_7 error: expected Tag_CPU_arch not found
Entering interactive test mode at the builder root directory.
Type 'exit' when done exploring.
# file /bin/sh
/bin/sh: ELF 32-bit LSB executable, ARM, EABI5 version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 12.0 (1200501), FreeBSD-style, stripped
# /usr/bin/readelf -A /bin/sh
Attribute Section: aeabi
File Attributes
  Tag_conformance: 2.09
  Tag_CPU_arch: ARM v7
  Tag_CPU_arch_profile: Application Profile
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: 32-bit Thumb
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_R9_use: V6
  Tag_ABI_PCS_GOT_use: direct
  Tag_ABI_PCS_wchar_t: wchar_t size 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte align
  Tag_ABI_align_preserved: 8-byte align
  Tag_ABI_enum_size: 32-bit
  Tag_ABI_VFP_args: AAPCS (VFP variant)
  Tag_ABI_optimization_goals: Speed
  Tag_CPU_unaligned_access: Not allowed
  Tag_ABI_FP_16bit_format: IEEE 754
```

Interestingly enough, on the host-builder:
```
1.onyx:/xbuilds,8:51am# readelf -A /bin/sh
1.onyx:/xbuilds,8:51am# 
```

Is synth running `readelf` on the host's sysroot rather than `${Directory_system}`?

The other odd thing I've noticed is that synth will always attempt a rebuild of ports-mgmt/pkg even if the package is already there. The contents +COMPACT_MANIFEST looks correct, but synth keeps thinking that it's wrong?

**Comment by jrmarino** [comment]
yeah, that's the problem.  Can you verify the host readelf against ${Directory_system}/bin/sh produces the expected output?

The ports-mgmt/pkg rebuild might be related.  Grab a copy of the produced pkg package and use pkg(8) info to determine the ABI of the package.  That might help.

**Comment by daemonblade** [comment]
The hosts's `readelf` works as expected against the armv7 binaries:
```
1.onyx:~,11:04am# readelf -A /xbuilds/rpi2v7/sysroot/bin/sh
Attribute Section: aeabi
File Attributes
  Tag_conformance: 2.09
  Tag_CPU_arch: ARM v7
  Tag_CPU_arch_profile: Application Profile
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: 32-bit Thumb
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_R9_use: V6
  Tag_ABI_PCS_GOT_use: direct
  Tag_ABI_PCS_wchar_t: wchar_t size 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte align
  Tag_ABI_align_preserved: 8-byte align
  Tag_ABI_enum_size: 32-bit
  Tag_ABI_VFP_args: AAPCS (VFP variant)
  Tag_ABI_optimization_goals: Speed
  Tag_CPU_unaligned_access: Not allowed
  Tag_ABI_FP_16bit_format: IEEE 754
```

pkg(8) also seems to report that the compiled package is good:
```
2.onyx:/tmp,11:06am# pkg info -F pkg-1.10.5_5.txz
pkg-1.10.5_5
Name           : pkg
Version        : 1.10.5_5
Origin         : ports-mgmt/pkg
Architecture   : FreeBSD:12:armv7
Prefix         : /usr/local
Categories     : ports-mgmt
Licenses       : BSD2CLAUSE
Maintainer     : pkg@FreeBSD.org
WWW            : https://wiki.freebsd.org/pkgng
Comment        : Package manager
Options        :
        DOCS           : on
Shared Libs provided:
        libpkg.so.4
Annotations    :
        FreeBSD_version: 1200501
Flat size      : 11.2MiB
Description    :
Package management tool

WWW: https://wiki.freebsd.org/pkgng
```

**Comment by jrmarino** [comment]
Can you test against with the latest commit?
The repeating pkg build might be fixed at the same time.  let's see.

**Comment by daemonblade** [comment]
I'm still getting quite a few `ARM_version_7 error: expected Tag_CPU_arch not found`.

On `replicant-platform.adb`, I put in 2 debug lines.
```
88       TIO.Put_Line (command);
89       TIO.Put_Line (contents);
```

On running **synth**:
```
,6:01pm# env ENTERAFTER=extract synth test devel/ccache
/usr/bin/readelf -A /xbuilds/rpi2v7/sysroot/bin/sh
Attribute Section: aeabi
File Attributes
  Tag_conformance: 2.09
  Tag_CPU_arch: ARM v7
  Tag_CPU_arch_profile: Application Profile
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: 32-bit Thumb
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_R9_use: V6
  Tag_ABI_PCS_GOT_use: direct
  Tag_ABI_PCS_wchar_t: wchar_t size 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte align
  Tag_ABI_align_preserved: 8-byte align
  Tag_ABI_enum_size: 32-bit
  Tag_ABI_VFP_args: AAPCS (VFP variant)
  Tag_ABI_optimization_goals: Speed
  Tag_CPU_unaligned_access: Not allowed
  Tag_ABI_FP_16bit_format: IEEE 754

ARM_version_7 error: expected Tag_CPU_arch not found
^C
```

**Comment by jrmarino** [comment]
okay, I have an idea what the issue is, hold on.

**Comment by jrmarino** [comment]
okay, hopefully it works now.

**Comment by daemonblade** [comment]
Yes, it looks good. Both armv6 and armv7 cross-builds appear to be working as expected.

**Comment by jrmarino** [comment]
good.  I also infer that the pkg package constant rebuilding is no longer an issue.

**Comment by daemonblade** [comment]
Yes, the constant rebuild of **ports-mgmt/pkg** has gone away.
