### ISSUE TITLE
TERM issues while running via cron

### ISSUE THREAD

**Issue by felix** [jrmarino/synth#148]
I would like to run synth via cron unattended on a remote machine. To avoid the TERM prompt:
```
Please define TERM in environment first and retry.
```
I define `TERM=dummy`  in crontab:
```
/usr/sbin/portsnap auto && env TERM=dummy /usr/local/bin/synth just-build /usr/local/etc/synth/ports ...
```
But I then have no way of avoiding the following prompt
```
*******************************************************************
 The ports tree has at least one file newer than the flavor index.
 However, port directories perfectly match.  Should the index be
 regenerated? (Y/N)
```
due to the check at src/portscan-pilot.adb line 1895 testing for a TERM being defined:
```
         if tree_newer then
            if Unix.env_variable_defined ("TERM") then
            -- snip
            end if;
```
Perhaps that latter test can also check for 'dummy' (or another suitable TERM) or somehow avoid the TERM requirement to run the build commands.

**Comment by jrmarino** [comment]
I see.  Probably the best solution is also check the value of TERM env variable via unix.env_variable_value to make sure it's not "dummy".  The reason it exists is to avoid output when no term is defined but that does indeed mess up the cron case.
