### ISSUE TITLE
PHP configured/built with ZTS Zend Thread Safety

### ISSUE THREAD

**Issue by denradford** [jrmarino/synth#149]
When PHP is configured and built with ZTS - Zend Thread Safety, it changes the PHP_EXT_DIR from `/usr/local/lib/php/20180731` to `/usr/local/lib/php/20180731-zts`.

When Synth begins to build a port that depends on a PHP extension it builds the dependent extension and correctly installs it into `20180731-zts/` but then incorrectly searches for the dependent extension in `20180731/` and the build fails

```
===>   php73-xmlreader-7.3.1_1 depends on file: /usr/local/lib/php/20180731/dom.so - not found
===>   Installing existing package /packages/All/php73-dom-7.3.1_1.txz
Installing php73-dom-7.3.1_1...
Extracting php73-dom-7.3.1_1: .......... done
===>   php73-xmlreader-7.3.1_1 depends on file: /usr/local/lib/php/20180731/dom.so - not found
*** Error code 1

Stop.
make: stopped in /xports/textproc/php73-xmlreader
```
This happens with both PHP 7.2 and 7.3 and can be quickly replicated by configuring PHP with ZTS then running `synth just-build textproc/php73-xmlreader` which depends on `textproc/php73-dom`

[textproc___php73-xmlreader.log](https://github.com/jrmarino/synth/files/2823349/textproc___php73-xmlreader.log)
[textproc___php73-dom.log](https://github.com/jrmarino/synth/files/2823354/textproc___php73-dom.log)

**Comment by jrmarino** [comment]
wouldn't this be a problem with the php framework? (as opposed to a problem with synth code)

**Comment by jrmarino** [comment]
to be clear, there's no difference building from the ports tree directory and using portmaster

**Comment by jrmarino** [comment]
I'm not saying it's not reproducible.  I'm insinuating the php maintainers the ones at fault.

**Comment by jrmarino** [comment]
see php.mk
```
#
# If you are building PHP-based ports in poudriere(8) with ZTS enabled,
# add WITH_MPM=event to /etc/make.conf to prevent build failures.
```

**Comment by jrmarino** [comment]
did you try adding WITH_MPM=event in the [profile]-make.conf ?

**Comment by denradford** [comment]
It all works when building directly from ports tree.
It all works when building/installing/updating with portmaster.
It does **not work** correctly when **Synth** attempts it 
/etc/make.conf and /usr/local/etc/synth/LiveSystem-make.conf
```
WITHOUT_X11= yes
DEFAULT_VERSIONS+= php=7.3 python=3.7 python3=3.7 perl5=5.28 mysql=8.0 ssl=openssl111
```

failure ocurrs at the build depend phase.
logs attached in original post

I have been working on this issue on my own off and on for months now. It has persisted across multiple version of FreeBSD and PHP. The problem only occurs with **Synth** tries to build.

**Comment by jrmarino** [comment]
> It all works when building directly from ports tree.
> It all works when building/installing/updating with portmaster.

which is irrelevant because by design both environments are dirty and non-reproducible between users
All this means is synth is catching a developer error.

The WITH_MPM hack should fix your issue.  It's a hack they added to the php.mk  because somebody realized it's broken.

**Comment by jrmarino** [comment]
> The problem only occurs with Synth tries to build.
Please understand that one possibility is synth (and apparently poudriere) are correct and the framework is broken for proper environments.  Don't shoot the messenger.

**Comment by denradford** [comment]
> 
> 
> did you try adding WITH_MPM=event in the [profile]-make.conf ?

This worked. Issue resolved. :)

I guess you correctly surmised that the primary reason I configured PHP with ZTS is to accommodate apache event MPM.

I'm sorry, it did appear to me to be pointing to Synth. As you say, of course Synth's environment is pristine every time.

Thank you so much for your help
