### ISSUE TITLE
Question: Cronjobs, automate builds

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#15]
I want to make sure if this makes sense or if there are more elegant solutions.
I want the ports in my jails (supplied via list.txt) and on my host system rebuilt if newer on a daily or weekly basis.

I assume that `portsnap fetch -I update` isn't enough and that I can't use the `-I` flag for Synth to work?

Would this make sense:
`portsnap cron update && synth just-build /folder/list.txt && synth rebuild-repository && pkg update`

**Comment by jrmarino** [comment]
synth rebuild-repository isn't really correct.
If there are packages on the live system that aren't on list.txt, those will be rebuilt.
The impact of this isn't terrible so you can do it if you want.  

I would not update automatically.  that seems like a bad idea to me.

**Comment by jrmarino** [comment]
also, your use case is "rebuild repository" weekly, not update package builder weekly.

The "pkg update" would be on the jails, not the host system.

**Comment by bax-** [comment]
why wouldn't you update automatically?
I don't upgrade, I just want the packages to be already built when I'm ready to upgrade.

There are a few packages on the live system that aren't in the list file but I don't see another possibility at this point.

**Comment by jrmarino** [comment]
pkg upgrade (which is no different that synth upgrade-system) upgrades the system.  That's beyond rebuilding repo.  so your command above does set system to upgrade unattended.

**Comment by bax-** [comment]
I'm doing `pkg update`, not `pkg upgrade`.
But it probably isn't needed on a regular basis since synth does this anyways ?
Or would I need to do this before calling Synth?

**Comment by jrmarino** [comment]
i have no idea why you are doing it.

**Comment by bax-** [comment]
To have a script compare the available packages later and write me an email if there are updates:
`pkg -vIL=`
Do I still need to call `pkg update` before that when I use Synth?

**Comment by jrmarino** [comment]
normally I would say no.  Most pkg commands auto-update the repository data anyway unless you tell it not to with the -U comman.

However, if you have a specific reason (e.g. need to force the update for a script) I guess that's fine.
(obviously synth makes pkg update the repo information when it's the one issuing the install commands)

**Comment by jrmarino** [comment]
This is going to be nasty, but I'm going to rename "synth rebuild-repository" to "synth prepare-system" and then reuse "synth rebuild-repository" to rebuild the repository on command (no packages built first)

**Comment by jrmarino** [comment]
Now that 0.99_3 is released, I think we can close this.
