### ISSUE TITLE
Is it possible to build for older os versions?

### ISSUE THREAD

**Issue by mike-pt** [jrmarino/synth#151]
Sorry if this is in the FAQ, but unless my search skills failed me I didn't find info on this...

Obiously I could just create my own jail to do this, but as stated in the FAQ there's no benefit on doing that since synth actually uses jails(or jail like envs... I'm guess its just chroots) .... and so I was wondering if there maybe an hidden flag/setting to have synth grab an older userland to build packges?

This is would be interesting if say we wanted to provide a repo for a package but we need to distribute  say FreeBSD 12 and 11

**Comment by jrmarino** [comment]
you're mixing up the terminology (probably due to poudriere terms).
The FAQ says there is no real benefit to running inside a jail (other than controlling what user runs synth).  The other "jail" is the build environment which is defined in the configuration menu.  By default it's the system root of the host server.  

However, you can extract any freebsd release and add a profile that uses that freebsd release as the system root for the builds (just update the configuration items).

So yes, it's possible.

**Comment by mike-pt** [comment]
Yeah I must admit that I am switching away from poudriere to synth, to be honest I was searching for "release" "version" and "jails" which lead me to that part.

But I'm still not clear what I need to do to make this work... So if I create a new profile and point the `[G] System root directory      /` at `/bsd11.0` and I download the userland to say:

`/synth/releases/12.0-RELEASE/root/` I can just change that line to achieve this? (meaning would everything else be relative to this new root like the /usr/ports .. build base etc? Or should I update those to?

**Comment by jrmarino** [comment]
well, if you extract the userland to /synth/releases/11-2-RELEASE/root then you'd set the "[G]" option to that directory.
No, nothing else is relative.  the ports directory wouldn't change, nor would build base.  IIRC correctly, it's just the single system root menu item that changes.  Note that older releases are fine, but you can't reliably build on releases newer than the host.

**Comment by jrmarino** [comment]
well, it would be 
```
/synth/releases/11.2-RELEASE/
```
for system root actually.  "/root" is not the system root.

**Comment by mike-pt** [comment]
Actually the root path there actually means the system root to not the user dir... I'm thinking of using the release incase extracts already :) 

Thanks for the clarification I will try this out today.

Closing this!
