### ISSUE TITLE
Ignore ports with obsolete options

### ISSUE THREAD

**Issue by UrsusDominatus** [jrmarino/synth#152]
Is there any chance to get "ignore obsolete ports" option during build process? I have cron driven update process scheduled at nighttime and often need to start build process manually when I see "obsolete ports detected and nothing rebuilt" message. If synth simply skips ports with obsolete options, most of the ports will be rebuilt in time when update was scheduled.

**Comment by jrmarino** [comment]
it's a fatal error.  There's no way to skip it, the options issue has to be resolved.
To mitigate it, don't set options unnecessarily.

**Comment by UrsusDominatus** [comment]
Oh, I see. I really need custom build options for my iRedMail based mail server jail. Poudriere didn't have similar issues, so I thought that this is possible with synth. Tank you for clarification.

**Comment by jrmarino** [comment]
Poudriere is simply hiding the issue, which can cause serious side effects that are hard to track down.  Believe me, you want to know when options change (or disappear).

**Comment by jrmarino** [comment]
You actually just pointed out one of the serious flaws with poudriere that has never been addressed (at least they could decide to show errors and ignore, but it can't detected the errors).

**Comment by UrsusDominatus** [comment]
Interesting thing. Glad to hear that synth is more confident about potential hidden flaws in ports after build process. Reading carefully man page, I think I can do what I want with "hook_pkg_failure" script, fixing port options (automatically) and restarting build process.

**Comment by cadatoiva** [comment]
Didn't know if I should open a new issue with this closed one being so similar. In portmaster, any ports with obsolete/invalid/missing options that it finds during the initial checks, it just runs the `make config` for that port and lets the user correct without a fatal abort. I would like to see this functionality added.
