### ISSUE TITLE
Do not set DEVELOPER = YES by default

### ISSUE THREAD

**Issue by Duffyx** [jrmarino/synth#154]
DEVELOPER = YES should only be set if its present in make.conf.
Even when DEVELOPER = NO in make.conf its overwritten by Synth.
This makes me not able to build samba48 atm becuase of https://reviews.freebsd.org/D19562 and there will be other ports as well that will fail.

**Comment by Duffyx** [comment]
====> Running Q/A tests (stage-qa)
Error: lang/python should not be depended upon. Instead, use USES=python:xy with a specific version.
*** Error code 1

Stop.
make: stopped in /xports/net/samba48

**Comment by jrmarino** [comment]
No, DEVELOPER=YES is part of the "synth test" command. 

From your log there, there's obviously a bug in samba48 makefile.

see here:
TEST_DEPENDS+=                  python:lang/python 
(line 252).

You should be notifying port maintainer for samba48.  It's not a synth issue.

**Comment by Duffyx** [comment]
So strange as I got that log from a Synth just-build fileoforigins

**Comment by jrmarino** [comment]
i don't understand.
There's a bug in the makefile.  Synth logged the result of the bug.  I don't see what is strange about that.
Synth is doing what it's designed to do: find bugs in port makefiles.  The ports tree is fair from flawless.

**Comment by Duffyx** [comment]
Let me ask a simple question, does Synth force DEVELOPER = YES when running a `synth just-build portlist`?  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236945

**Comment by jrmarino** [comment]
I don't think so.   You can confirm by checking the log (grep for DEVELOPER)

**Comment by jrmarino** [comment]
a quick scan of the code indicates DEVELOPER is only set when "synth test" command used.  It would not happen with "synth build"

**Comment by Duffyx** [comment]
Thx for verifying. Thats why I find it strange as I explicitly set DEVELOPER = NO but it still ends up being enabled. I'll double check tomorrow that I didnt screw my testcases up in any way.

**Comment by Duffyx** [comment]
OK I am a fucking idiot, I had hard linked /etc/make.conf with LiveSystem-make.conf but apparently the linking wasnt OK anymore so everytime I edited /etc/make.conf it didn't pass the changing to that file to Synth. Closing this one.

**Comment by jrmarino** [comment]
yeah, I strongly recommend against linking (LiveSystem-make.conf should be isolated, it shouldn't match the system make.conf) but people still commonly do it.  And they get burned for it occasionally.

So I would recommend leaving it as profile-specific as it was meant...
