### ISSUE TITLE
ccache-3.7.1 and Synth

### ISSUE THREAD

**Issue by kaba1ah** [jrmarino/synth#158]
Sorry if this is the wrong place to ask, but the latest commit in FreeBSD's port collection for devel/ccache (https://docs.freebsd.org/cgi/getmsg.cgi?fetch=4335501+0+/usr/local/www/mailindex/archive/2019/svn-ports-head/20190519.svn-ports-head) seems to break something.

Running 'synth just-build devel/ccache' generates an error:

`devel/ccache scan aborted because a circular dependency on devel/ccache was detected.`
`... backtrace devel/gettext-runtime`
`... backtrace devel/gmake`
`... backtrace devel/ccache`

Not sure where to start...

I'm under FreeBSD 11.2-RELEASE-p5 r341363 with Synth 2.08.

Thank you.

**Comment by ThomasHerrlin** [comment]
[FreeBSD bugzilla 237979](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237979#c1)
make.conf workaround that worked for me:
.if ${.CURDIR:M*/devel/ccache*} || ${.CURDIR:M*/print/indexinfo*} || ${.CURDIR:M*/devel/gmake*}
NOCCACHE=yes
WITHOUT_CCACHE_BUILD=yes
.endif

Note that I have symlinked LiveSystem-make.conf -> /etc/make.conf, and that i have other ccache customization stuff in my make.conf, YMMV.

**Comment by kaba1ah** [comment]
Fixed in https://docs.freebsd.org/cgi/getmsg.cgi?fetch=693180+0+current/svn-ports-all (NO_CCACHE=yes).
