### ISSUE TITLE
Better error message for empty `/usr/ports`

### ISSUE THREAD

**Issue by hartzell** [jrmarino/synth#159]
On a freshly set up FreeBSD12 system (via the AWS ZFS AMI), with no `/etc/make.conf` and an empty `/usr/ports` directory and a `portshaker` managed set of ports trees underneath `/usr/portshaker`, I got this error message when I tried to configure synth:

```
$ sudo synth configure
It seems that a blank PORTSDIR is defined in /etc/make.conf
Configuration failed to load.
```

It confused me, since I didn't *have* an `/etc/make.conf`.  I created one and lazily set `PORTSDIR=/usr/ports`, intending to set it up the way I wanted from `synth configure`.   That led to the same error message.  I then set `PORTSDIR=/usr/portshaker/merged` (which is a valid ports tree) and was able to run `synth configure`.

I think that what it was complaining about was that the ports directory it was using (`/usr/ports`, picked up as a default somewhere) was empty.

If so, a more informative message might be:

```
The configured ports directory, /usr/ports, is empty.  Please set PORTSDIR in /etc/make.conf to a valid ports tree.
```

I'm a bit confused about why I need to set PORTSDIR at all; I was expecting to set it to what I wanted from within `synth configure`.

**Comment by jrmarino** [comment]
Sorry about responding to this 6 years later.
You make good points.  If I recall correctly, the ports framework crashes if PORTSDIR is not defined.  So you have a valid point - you'd think setting it in synth should be enough, but in reality it has to be defined in 2 places.

now - internally the ports are mounted at /usr/ports regardless of the true path.

I think the main issue is that that synth was configured to use an empty directory.  It's been a long time, but I think make.conf was optional, so my guess is that it made PORTSDIR default to /usr/ports and then complained that /usr/ports was empty.

probably the error message could be much better but OTOH this is the only complaint i've seen on this in 6 years.
