### ISSUE TITLE
Missing warnings and more

### ISSUE THREAD

**Issue by bettercom** [jrmarino/synth#160]
After migrating from portmaster to synth I ran into some problems:

`synth install databases/postgresql11-server`

installed server and client.

With `make -C /usr/ports/mail/spamassassin config` I enabled `PGSQL` so `databases/p5-DBD-Pg` became a dependency.

`synth install mail/spamassassin` installed several dependencies but probably due to `PGSQL_DEFAULT?=9.5` in `/usr/ports/Mk/bsd.default-versions.mk` synth built and installed `databases/postgresql95-client` and **deleted** `postgresql11-server` **without chance to confirm deletion**. That is really bad and I have no idea how to handle such issues. Installing `postgresql11-server` afterwards caused deletion of spamassassin et al.

Setting `DEFAULT_VERSIONS+=pgsql=11` in `/etc/make.conf` did not fix this issue with synth.

`make -C /usr/ports/mail/spamassassin install` or `portmaster mail/spamassassin` worked as expected and used a previous installed postgresql-client without expecting the default version, any previously installed version was not uninstalled.

IMHO synth should

1. delete installed packages only after explicit confirmation
2. check better which packages already fulfill requirements

Did I miss something? It's not clear whether synth uses parameters set in `make.conf`.

However: Thank you for development of this helpful tool.

**Comment by daemonblade** [comment]
`make.conf` options should be put into `/usr/local/etc/synth/LiveSystem-make.conf`. There's a section on this on the man-page in the FILES section.
