### ISSUE TITLE
Distcc Support?

### ISSUE THREAD

**Issue by GitHubinat0r** [jrmarino/synth#163]
I'm wanting to distribute some of the workload from my builder machine to spares and thought this would be an appropriate use case for distcc and seem to be having issues integrating the usage with Synth. 

I'm able to manually have distcc run when I run 'make' for a port. I seem to be having integration issues with Synth.

In my /root/.cshrc I have:

```
setenv PATH /usr/local/libexec/ccache:$PATH
 
setenv CCACHE_PATH /usr/bin:/usr/local/bin
setenv CCACHE_DIR /var/tmp/ccache
setenv CCACHE_LOGFILE /var/log/ccache.log
setenv CCACHE_PREFIX distcc
```

I updated /usr/local/etc/synth/LiveSystem-environment to include:

```
PATH=$PATH:/usr/local/libexec/ccache

CCACHE_PATH=/usr/bin:/usr/local/bin
CCACHE_DIR=/var/tmp/ccache
CCACHE_LOGFILE=/var/log/ccache.log
CCACHE_PREFIX=distcc
DISTCC_HOSTS="192.168.1.52"
```

And when I run 'synth install devel/cmake' it fails with the output in /var/log/synth/devel___cmake.log:

```
--------------------------------------------------------------------------------
--  Phase: pkg-depends
--------------------------------------------------------------------------------
===>   cmake-3.14.4 depends on file: /usr/local/sbin/pkg - not found
===>   Installing existing package /packages/All/pkg-1.10.5_5.txz
/xports/Mk/Scripts/do-depends.sh: mkdir: not found
*** Error code 127

Stop.
make: stopped in /xports/devel/cmake
```
If I update /usr/local/etc/synth/LiveSystem-environment to:

```
#PATH=$PATH:/usr/local/libexec/ccache

CCACHE_PATH=/usr/bin:/usr/local/bin
CCACHE_DIR=/var/tmp/ccache
CCACHE_LOGFILE=/var/log/ccache.log
CCACHE_PREFIX=distcc
DISTCC_HOSTS="192.168.1.52"
```

I get the following error in /var/log/synth/devel___cmake.log:

```
===>  Configuring for cmake-3.14.4
---------------------------------------------
CMake 3.14.4, Copyright 2000-2019 Kitware, Inc. and Contributors
---------------------------------------------
Error when bootstrapping CMake:
Cannot find appropriate C compiler on this system.
Please specify one using environment variable CC.
See cmake_bootstrap.log for compilers attempted.

---------------------------------------------
Log of errors: /construction/xports/devel/cmake/work/cmake-3.14.4/Bootstrap.cmk/cmake_bootstrap.log
---------------------------------------------
===>  Script "configure" failed unexpectedly.
Please report the problem to kde@FreeBSD.org [maintainer] and attach the
"/construction/xports/devel/cmake/work/cmake-3.14.4/config.log" including the
output of the failure of your make command. Also, it might be a good idea to
provide an overview of all packages installed on your system (e.g. a
/usr/local/sbin/pkg-static info -g -Ea).
*** Error code 1

Stop.
make: stopped in /xports/devel/cmake
```

If I remove or comment out the remaining lines in /usr/local/etc/synth/LiveSystem-environment, everything works fine.

Is distcc not supported or did I misconfigure my system?

**Comment by GitHubinat0r** [comment]
Looks like the issue can be simplified even further. It seems that Synth doesn't support ccache's CCACHE_PREFIX option.

**Comment by GitHubinat0r** [comment]
It looks like the underlying issue is the lack of the distcc binary which is not copied to the chroot. I wanted to do a primative test and pause the process, copy the binary over before compile and see if it would work, but it's mounted ro and I'm a bit puzzled as to how to remount it r/w.

**Comment by jrmarino** [comment]
it would require framework support just as the ports framework supports ccache (which becomes a build requirement when activated).  Something would have to add distcc as a build requirement.

Anyway, synth obviously doesn't have any specific support, so if it can't be activated through a profile make.conf, it probably won't work.

**Comment by GitHubinat0r** [comment]
Thanks for the hints. I was able to modify the make.conf to include the logic used by the bsdadminscripts and removed ccache to help reduce complexity.

```
# /usr/local/etc/buildflags.conf
BUILDFLAGS= /usr/local/share/bsdadminscripts2/buildflags.mk
.if exists(${BUILDFLAGS})
.include "${BUILDFLAGS}"
.endif
```

Specifically, the /usr/local/share/bsdadminscripts2/buildflags.mk contained the relevant section:

```
CC:=                    ${BUILDFLAGS_DISTCC} ${CC}
CPP:=                   ${BUILDFLAGS_DISTCC} ${CPP}
CXX:=                   ${BUILDFLAGS_DISTCC} ${CXX}
```

I then ran synth force devel/cmake, let it start compiling, then paused the process then:

```
chroot /usr/obj/synth-live/SL01
```

Once I was chrooted in, I confirmed distcc was present, but got this error message:

```
ld-elf.so.1: Shared object "libpopt.so.0" not found, required by "distcc"
```

**Comment by GitHubinat0r** [comment]
No longer an issue. Moved onto using Poudriere with a dedicated builder machine.
