### ISSUE TITLE
FreeBSD: graphics/darktable: release 2.6.2_3 fails to build under ports-mgmt/synth

### ISSUE THREAD

**Issue by topcat001** [jrmarino/synth#168]
I have run into a dependency issue on FreeBSD for ports which use OpenMP from the base system, in particular darktable. The FreeBSD bug report is here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240488
Build log for "synth test graphics/darktable" is attached to the FreeBSD bug report.

Original forum thread is here: https://forums.freebsd.org/threads/synth-cannot-install-or-upgrade-darktable.72250/

Right now I have to manually edit the Makefile and remove the libomp section to get darktable to install.

**Comment by daemonblade** [comment]
It's actually a port issue, rather than a synth issue. The port Makefile has to corrected individually. One example of a fix is in games/tesseract:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242292

**Comment by topcat001** [comment]
Thanks for the comment! There is a suggested patch for the darktable package which moves the dependency to ports like in the tessaract example. This is the solution for now.

However, if the base system supplies the library, then probably it should be picked up. I don't know of a good solution to the problem at the moment.

**Comment by topcat001** [comment]
FreeBSD has removed openmp from ports, and hence this issue is now fixed. Closing.
