### ISSUE TITLE
Deleted port from ports/ causes synth to fail

### ISSUE THREAD

**Issue by pavalos** [jrmarino/synth#17]
```
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
Stand by, building pkg(8) first ... done!
Scan of mail/dcc-dccd failed (port deleted?), it will not be considered.

raised PORTSCAN.NONEXISTENT_PORT : /xports/mail/dcc-dccd (mail/spamassassin)
```

Shouldn't it just be ignored instead of failing to do anything?

**Comment by jrmarino** [comment]
it was supposed to ignore it, that's the what first thing say it would do, "it will
 not be considered".

not sure what's going on, but that's definitely a bug.

**Comment by jrmarino** [comment]
if you want to test:
change Makefile line 24 from
```
GH_TAGNAME=     v1.3:bundle ab6e2f2
```
to
```
GH_TAGNAME=     v1.3:bundle 548f9bd
```

then run "make makesum"
then rebuild it

**Comment by jrmarino** [comment]
(you might want to run
```
pkg ins gcc6-aux
```
first

**Comment by jrmarino** [comment]
synth 0.99_3 released; should fix it (?)

**Comment by pavalos** [comment]
Nope:

```
Scanning entire ports tree.
 progress: 68.17%
culprit: mail/spamassassin
Scan aborted because dependency could not be located.
/xports/mail/dcc-dccd (required dependency of mail/spamassassin)
Failed to scan ports tree   (Synth must exit)
```

**Comment by jrmarino** [comment]
Well, that one was handled, so it's doing what it's supposed to do and told you exactly the problem.

I think you'll going to have to remove spamassassin manually and/or rebuild it to get rid of mail/dcc-dccd (or at least get rid of ports that require mail/dcc-dccd)

**Comment by jrmarino** [comment]
FYI, this is what happened to the port, why it was skipped:
...
base system Sendmail not found or too old, rebuild with WITH_PORTS_SENDMAIL=yes or WITHOUT_DCCM=yes
```
It requires sendmail.
Perhaps it could be recovered to the ports tree if we define WITHOUT_DCCM in the port.

**Comment by pavalos** [comment]
> Well, that one was handled, so it's doing what it's supposed to do and told you exactly the problem.
> 
> I think you'll going to have to remove spamassassin manually and/or rebuild it to get rid of mail/dcc-dccd (or at least get rid of ports that require mail/dcc-dccd)

I guess I was expecting it to just ignore mail/dcc-dccd and all the ports that use it.

> Perhaps it could be recovered to the ports tree if we define WITHOUT_DCCM in the port.

I'd be fine with that.

**Comment by jrmarino** [comment]
it would ignore mail/dcc-dccd if it were a leaf package, but it's a dependency so it can't go on.  The sysadmin needs to decide now to resolve it.

**Comment by jrmarino** [comment]
dcc-dccd is back in the tree (without DCCM option)
