### ISSUE TITLE
Fetch Prebuild issue ?

### ISSUE THREAD

**Issue by Antoni0Torres** [jrmarino/synth#170]
I'm using synth from several month to build a small package list, thanks, it's really nice.

I found that fetch prebuild packages are not always respected or maybe I'm missing something.

When there is a version difference between "latest" pkgs and ports, synth try to compile and use last version from ports, this is ok and is only
a problem with ports <> pkgs syncronisation.

But I found also that when synth build a port because his version is higher in ports it also build the others ports in which the build port depend on
but the version of it is the same in lastes pkg and ports so it could fetch the pkg but don't do it.

Example:

rspamd -> depend on openblas -> depend on gcc9

- rspamd is build because custom options and it's on the list for synth
- openblash is build because ports version (0.3.7,1) is higher than pkg latest version (0.2.20_11,1)
- gcc9 is build but port version (9.2.0_1) is the same as pkg version in latest, don't should it be fetched rather than compiled ?

Thanks.

**Comment by jrmarino** [comment]
it's working as designed.  You may think the depends don't need rebuilding but they do.  Synth (and poudriere) rebuild all depends when any predecessor port changes.  It's got nothing to do with the version.
