### ISSUE TITLE
consider ASSUME_ALWAYS_YES environment variable

### ISSUE THREAD

**Issue by basbebe** [jrmarino/synth#171]
`pkg` considers the `ASSUME_ALWAYS_YES` and the `DEFAULT_ALWAYS_YES` environment variables.  
For automation (e.g. cronjobs) it would be great if synth also considered these.  
e.g. when initiating a cronjob which builds some ports or which logs a synth status, the output wouldn't halt on some `y/n` question (e.g. regenerate flavor index) and we could avoid the cpu overhead of `yes | synth status`

[yes on wikipedia](https://en.wikipedia.org/wiki/Yes_%28Unix%29):

> Yes can be used as an easy way of generating CPU load, for example in 2006, the yes command received publicity for being a means to test whether or not a user's MacBook is affected by the "Intermittent Shutdown Syndrome" bug, where a MacBook would randomly shut off without any user input. By running the yes command indefinitely twice via Terminal under Mac OS X, users were able to max out their computer's CPU, and thus see if the failure was heat related.[1][2]

**Comment by jrmarino** [comment]
Interactive ports were removed years ago (the only ones to ask questions).
Are you sure someone brought one back?
Plus you can always add it yourself with a environment profile. Finally
"always yes" is a bad idea. Ports having interaction is a last resort so
the question really should be answered thoughtfully.
Example of this interactive port is? Link please.

**Comment by basbebe** [comment]
I wasn't thinking of interactive ports but of synth's own prompts.
But I think I made a mistake here: I assume that synth uses the TERM=dumb environment variable and then doesn't prompt?

**Comment by jrmarino** [comment]
If I remember correctly, that's right.  If the TERM isn't set, then it
won't prompt at all so that it can be used by cron.
