### ISSUE TITLE
Dealing with license agreements

### ISSUE THREAD

**Issue by ncoder-1** [jrmarino/synth#173]
Great work with `synth`!

I'm wondering if it would it be worth mentioning in the `README.md` that some packages require license agreements (for example: `sysutils/fusefs-exfat` and `sysutils/exfat-utils`) and `synth` won't build or be able to fetch a prebuilt package (since they are not distributed on the pkg repos) and it terminates without clearly stating what went wrong.

My workaround is to add `DISABLE_LICENSES=yes` in my synth profile's make.conf (in my case `/usr/local/etc/synth/LiveSystem-make.conf`). You can also do a per-license agreement instead of all licenses (like explained [here](https://forums.FreeBSD.org/threads/automatic-license-agreement-per-package.71438/post-442601)).

If it's not worth mentioning, then at least someone can search here on GitHub and find this.

**Comment by jrmarino** [comment]
Well, you're basically doing what is expected.
Pretty much everyone either disables the licenses or sets the "yes to all" variable (which I can't remember off the top of my head).
So synth is working as designed and pretty much exactly like poudriere in this aspect.

**Comment by ncoder-1** [comment]
Except it's not giving out an explicit error message if you don't, hence why I suggested either adding a note in `README.md` or have this GitHub "issue" in the archives so someone can google it and find a solution.  Feel free to close.

**Comment by jrmarino** [comment]
It's not a synth thing, it's a FreeBSD ports thing.  If you built the port on a live system you'd have the same issue.  Maybe it could go in a FAQ section but I wouldn't want to present it as "do this always to circumvent licensing".  It's just keeping with the default.  And there's basically the same issue with "do not package this" ports.  that setting could be overridden as well.

**Comment by ncoder-1** [comment]
Sure.  Again, feel free to close, at least it's here and searchable, that was my only intention.

**Comment by jrmarino** [comment]
ok.  Glad that synth is working out for you!
