### ISSUE TITLE
OPTIONS_UNSET not being used?

### ISSUE THREAD

**Issue by rwv37** [jrmarino/synth#175]
I tried a "synth status", and noticed that synth wants to build a billion X11 ports, which surprised me because I have that turned off in my /usr/local/etc/synth/LiveSystem-make.conf:

```
OPTIONS_UNSET=CUPS DEBUG X11 
WANT_OPENLDAP_SASL=yes
```

 I am sure that it is getting at least some settings from that file, because toggling WANT_OPENLDAP_SASL leads to synth appropriately wanting to build either openldap24-client or openldap24-sasl-client. But x11 (and cups, and I assume debug) always seem to be used.

I googled around thinking that maybe "OPTIONS_UNSET" is not supported, but I see that a bunch of people use it. I also noticed that a lot of people use a bunch of "OPTIONS_UNSET+=" lines instead of a single "OPTIONS_SET=" line, so I tried that; it did not help. And in any case, I haven't been able to find anything indicating what I might be doing wrong here, nor what I might be able to do to fix it. Any ideas? Thanks.

**Comment by jrmarino** [comment]
Synth doesn't recreate functionality.  It executes the ports framework.  If OPTIONS_UNSET is supported by the ports framework, then it's used.

Check the log of a build.  You will see LiveSystem-make.conf printed there if you are building with the LiveSystem profile.  Since you said some settings are in effect, you should see it near the beginning of the log.

My guess?  You already saved the options via the ports dialog previously.  You might want to find the directory where options are saved and delete everything.  or at least the ones you're really concerned about.  I think you'll see the path to the options directory when you type "synth configure".

**Comment by jrmarino** [comment]
no, you understood it perfectly.
Did you check a log (any log) to make sure LiveSystem-make.conf is getting concatenated to the generated make.conf?
If it is (and it sounds like it is), then I don't know.  If the generated make.conf is present with your changes but the ports tree isn't respecting it, the issue must be in the ports tree.

**Comment by rwv37** [comment]
OK, I just looked at the build order from 00_last_results.log, and cups was very near the end. I assume that only the things following it in the build order might depend on it?

So, based on that idea (whether it's right or not), I discovered that openjdk8 has a dependency on cups, and also on at least some x11 things. I have openjdk8, in turn, because it's required indirectly by two of my top level packages (devel/nexus2-oss and print/pdftk).

But on my real system, I have openjdk8, nexus2-oss, and pdftk installed, but do *not* have cups or any x11 stuff installed. And my LiveSystem-make.conf is just a copy of my make.conf. In the past I've always updated via "portmaster -advw", and never got cups or x11 stuff (since I figured out the OPTIONS_UNSET stuff for them years ago).  So I don't understand why I'm getting them with one build system but not with the other.

**Comment by rwv37** [comment]
Oops, wrote that before seeing your recent comment about checking for LiveSystem-make.conf. So:

I'm not sure... it seems like it's getting in there, but I don't know enough to know for sure that this is what you're asking about. The only thing I see in there referring to make.conf is this (note that it does have my OPTIONS_UNSET and WANT_OPENLDAP_SASL lines):

```
--------------------------------------------------
--  /etc/make.conf
--------------------------------------------------
SYNTHPROFILE=LiveSystem
USE_PACKAGE_DEPENDS_ONLY=yes
PACKAGE_BUILDING=yes
BATCH=yes
PKG_CREATE_VERBOSE=yes
PORTSDIR=/xports
DISTDIR=/distfiles
WRKDIRPREFIX=/construction
PORT_DBDIR=/options
PACKAGES=/packages
MAKE_JOBS_NUMBER_LIMIT=4
WITH_CCACHE_BUILD=yes
CCACHE_DIR=/ccache
OPTIONS_UNSET=CUPS DEBUG X11
WANT_OPENLDAP_SASL=yes
HAVE_COMPAT_IA32_KERN=YES
CONFIGURE_MAX_CMD_LEN=262144
_PERL5_FROM_BIN=5.30.3
_CCVERSION_921dbbb2=FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581)
(based on LLVM 8.0.1) Target: x86_64-unknown-freebsd12.1 Thread model: posix Ins
talledDir: /usr/bin
_CXXINTERNAL_acaad9ca=FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581
) (based on LLVM 8.0.1) Target: x86_64-unknown-freebsd12.1 Thread model: posix I
nstalledDir: /usr/bin  "/usr/bin/ld" "--eh-frame-hdr" "-dynamic-linker" "/libexe
c/ld-elf.so.1" "--hash-style=both" "--enable-new-dtags" "-o" "a.out" "/usr/lib/c
rt1.o" "/usr/lib/crti.o" "/usr/lib/crtbegin.o" "-L/usr/lib" "/dev/null" "-lc++"
"-lm" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-neede
d" "-lgcc_s" "--no-as-needed" "/usr/lib/crtend.o" "/usr/lib/crtn.o"
_OBJC_CCVERSION_921dbbb2=FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366
581) (based on LLVM 8.0.1) Target: x86_64-unknown-freebsd12.1 Thread model: posi
x InstalledDir: /usr/bin
CC_OUTPUT_921dbbb2_58173849=yes
CC_OUTPUT_921dbbb2_9bdba57c=yes
CC_OUTPUT_921dbbb2_6a4fe7f5=yes
CC_OUTPUT_921dbbb2_6bcac02b=yes
CC_OUTPUT_921dbbb2_67d20829=yes
CC_OUTPUT_921dbbb2_bfa62e83=yes
CC_OUTPUT_921dbbb2_f0b4d593=yes
CC_OUTPUT_921dbbb2_308abb44=yes
CC_OUTPUT_921dbbb2_f00456e5=yes
CC_OUTPUT_921dbbb2_65ad290d=yes
CC_OUTPUT_921dbbb2_b2657cc3=yes
CC_OUTPUT_921dbbb2_380987f7=yes
_ALTCCVERSION_921dbbb2=none
_OBJC_ALTCCVERSION_921dbbb2=none
_SMP_CPUS=8
UID=0
ARCH=amd64
OPSYS=FreeBSD
OSVERSION=1201000
OSREL=12.1
_OSRELEASE=12.1-SYNTH
PYTHONBASE=/usr/local
_PKG_CHECKED=1
```

**Comment by jrmarino** [comment]
it's in there, see this line:
```
OPTIONS_UNSET=CUPS DEBUG X11
```

**Comment by rwv37** [comment]
Yes, so like I said I don't understand why I'd be getting cups and x11 with one build system but not the other.

**Comment by jrmarino** [comment]
> So, based on that idea (whether it's right or not), I discovered that openjdk8 has a dependency on cups, and also on at least some x11 things. I have openjdk8, in turn, because it's required indirectly by two of my top level packages (devel/nexus2-oss and print/pdftk).

That makes sense.  Either openjdk8 has a hardcoded dependency or it may have a different name for the option (the former is more likely).

So IIRC, UNSET actually removes the option.  it doesn't set it to "NO".  Don't quote me on that.  So if you had not used UNSET, but rather ran the options dialog and turned off CUPS, it probably wouldn't pick it up, even if openjdk8 pulls it in.

Again, this is all port tree stuff.

**Comment by jrmarino** [comment]
So something (openjdk) is pulling cups in, and whatever port we're talking about here is detecting it.  So that part needs to be configured to NOT use cups even if available.

UNSET may be interfering with that.

**Comment by rwv37** [comment]
OK, I will try recreating all the default options files that I had gotten rid of with redundant-opt-files.sh and seeing what happens. Thanks.

**Comment by jrmarino** [comment]
check the configure part of the log and see if it's configuring with CUPS.  And check configure arguments to confirm it's explicitly saying to NOT build with cups (or lack of it)

**Comment by jrmarino** [comment]
don't worry about all the ports.  just the one that isn't building as you expect.
The redundant script didn't hurt anything (and probably helped)

**Comment by rwv37** [comment]
When I run make config on openjdk8, there is no explicit cups option, and the x11 options are off.

The synth log file for openjdk8 indicates that it is building "--with-cups=/usr/local", and that it depends on the file /usr/local/include/cups/cups.h. So I guess that's hardcoded... but still, I don't understand why it wouldn't have ever have caused portupgrade to install cups.

Maybe openjdk8 was just changed to have this dependency recently (i.e. within the past week and a half or so)? Or maybe portupgrade hasn't needed to rebuild openjdk8 until recently? I will try another portupgrade on my actual installation and see if it now produces cups and/or x11.

**Comment by jrmarino** [comment]
so is the issue is that you don't want cups period but some ports need it?
I thought the issue was that some port was configurable to have cups or not and it was building with cups.   

If a port is hardcoding a dependency you don't want, the only option you have is to patch the port.  As to why you didn't see this before, there's a few reasons.  One likely one is you had an older version of java jdk that didn't have cups built in, but now that's no longer an option.

**Comment by rwv37** [comment]
Well, no, the issue is that I don't understand why synth and portmaster are dealing with cups differently:

I update all installed ports very regularly, usually once a week. If openjdk8 didn't need cups at some point in the past, but had been changed to need cups and have that requirement hardcoded rather than configurable, I am under the impression that portupgrade should have installed cups as part of its upgrade. Is that not correct?

**Comment by rwv37** [comment]
Well, anyway, screw it, I'll just uninstall everything from my real system and switch over to whatever synth says needs to be there. Thanks for all your help.
