### ISSUE TITLE
Builder mounts detected

### ISSUE THREAD

**Issue by Amplificator** [jrmarino/synth#176]
I followed the steps to install synth in a jail (running Freenas and set it up in a jail)

When I run upgrade-system or status I get this message:

> Builder mounts detected; attempting to remove them automatically ...
> The attempt failed. Check for stuck or ongoing processes and kill them.
> After that, try running Synth again or just manually unmount everything
> still attached to /usr/obj/synth-live

I have no idea on how to proceed from here. Any tips?

**Comment by jrmarino** [comment]
maybe this FAQ entry has a clue?
https://github.com/jrmarino/synth#synth-fails-when-i-run-it-inside-a-jail--what-can-i-do

**Comment by Amplificator** [comment]
I already set those options.

But I found the solution. When cancelling a run using ctrl+c it will "lock" the file in question so other jails can't run synth at all. Letting a command finish properly will not give the error, so I guess it is not freeing up something?

**Comment by jrmarino** [comment]
You're never supposed to use control-C.  There's a control-Q option for a graceful shutdown.  I'm sure that's documented in man page and other places.
