### ISSUE TITLE
dependencies check

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#18]
I just downloaded a ports tree with an updated libressl
In my make.conf I have 

```
WITH_OPENSSL_PORT=      yes
OPENSSL_PORT=           security/libressl
```

I thought that I might have to rebuild all the ports that depend on libressl.
I also think that dovecot2 wasn't build against libressl.

But `synth status`showed that everything was OK

**Comment by jrmarino** [comment]
read the man page (or the github tutorial) about customizing make.conf.  Synth doesn't use the host make.conf at all.

**Comment by bax-** [comment]
Interesting and good to know.
So is there any way to build against libressl e.g.?

**Comment by jrmarino** [comment]
maybe you misunderstood?
I didn't say synth can't use customized make.conf, I said it doesn't use the HOST make.conf

**Comment by bax-** [comment]
Oh I'm so sorry!
I misunderstood your answer.
I wasn't aware that Synth completely ignored the make.conf of the host and all options had to be set in the custom part.
Thank you!
