### ISSUE TITLE
Please stop using grey and red too much

### ISSUE THREAD

**Issue by FreeBSD-fan** [jrmarino/synth#182]
First, I am using synth 2.08 on FreeBSD 12.2 p 4.
I can't read skipped because the dark grey blends into the black backgound.  I haven't found relief with vidcontrol.
Ans PLEASE stop using lightred anywhere except the failed tag in the history list and the failed tag in the upper section.  Please do NOT use lightred for a builder ID tag.
Other than those nickpicks, I love synth.

**Comment by jrmarino** [comment]
Why not use the dynamic html report instead?  It's superior to curses.
There's only a few colors available to terminal applications.  I can't pick optimal shades.
The combinations for builders are extremely limited.
