### ISSUE TITLE
11.4 openssl problem for prefetch packages

### ISSUE THREAD

**Issue by nuclight** [jrmarino/synth#183]
In summer 2020, the Qt dropped support for OpenSSL versions 1.0.x which are in 11.x branch, and official packages on 11.x silently had more than 10000 packages missing now. In particluar, the `qt5-network` was now broken, and all it's deps like `telegram-desktop`.

The suggestion in ports commit was to add `DEFAULT_VERSIONS+=ssl=[openssl|libressl*]` to `/etc/make.conf` (btw I don't know which is better).

Well, I have only one my desktop on FreeBSD and lived on older branch for few months, and then discovered synth - sounds like great alternative to Poudriere specifically for one-machine case! I enabled fetching from official repo in `synth configure`.

But when I tried, it said

`Total packages that would be fetched: 929`

and when I changed `make.conf` with `cp /etc/make.conf /usr/local/etc/synth/LiveSystem-make.conf`, it now saidL

`Total packages that would be fetched: 588`

Now, there are e.g.
```
  N => www/chromium
  N => www/firefox-esr
```
amongst other ports to build, which are very heavy for this 12 Gb-RAM machine.

Is there any way to fetch "untouched" ports like chromium from official repo and apply openssl-rebuild only to those missing?

**Comment by jrmarino** [comment]
well, I'm guessing your definition of "untouched" is different than poudriere's and synth's.
I was going to mention the option to fetch from freebsd's repo and rebuild only what's necessary but I just realized you're already doing that.
By the way, copying /etc/make.conf to LiveSystem-make.conf can cause huge problems depending what's in the /etc/make.conf.   I recommend building LiveSystem-make.conf from scratch and only define lines you understand the purpose of (rather than just duplicating the system make.conf and assume it's good).

Anyway, no, synth already did the best it could at avoiding building (which is already risky on FreeBSD given the inherent mismatch on the ports tree that built the packages and the current ports tree).  If synth put it on the rebuild list then Synth is convinced it needs to be built from scratch.

**Comment by nuclight** [comment]
My `/etc/make.conf` was empty and for now exists solely as a backup to test things when removing `LiveSystem-make.conf`.

So, I was (and still) living on Quarterly branch, (2020Q3 before), and first thought I could mitigate the unmaintained 11.x problem with "untouched" things by this in `make.conf`:
```
.if ${.CURDIR} == ${PORTSDIR}/net/qt5-network
DEFAULT_VERSIONS+= ssl=openssl
.endif
```
and against DEFAULT_VERSIONS without `.if`, it offered me to download 930 packages and to build about 246, with about 500 packages if plain DEFAULT_VERSIONS, and 929 (to fetch) with empty `make.conf`. Yes, without Firefox and Chrome, those would be fetched.

I began fetching and building and after an hour realized it may be bad idea if just `qt5-network` would link with ports' openssl but dependent on it will use base one - what if it will boom?..

So I tried to put following to `make.conf`:
```
MY_OPENSSL_LIST= net/qt5-network databases/sqlitebrowser .... x11-toolkits/qt5-gui

.for portsslport in ${MY_OPENSSL_LIST}
.if ${.CURDIR} == ${PORTSDIR}/${portsslport}
DEFAULT_VERSIONS+= ssl=openssl
.endif
.endfor
```
and got
`make: "/etc/make.conf" line 7: Malformed conditional (${.CURDIR} == ${PORTSDIR}/${:Unet/qt5-network})`
wondering how it ever worked first time?.. O_o

Finally I changed `make.conf` to
```
# pkg query %ro qt5-network
MY_OPENSSL_LIST= net/qt5-network databases/sqlitebrowser net-p2p/transmission-qt ... x11-toolkits/qt5-gui

.for portsslport in ${MY_OPENSSL_LIST}
.  if ${.CURDIR:N*${portsslport}} == ""
DEFAULT_VERSIONS+= ssl=openssl
.  endif
.endfor
```
and now `synth prepare-system` offered to me to download 150 packages and to build only 50! But with `www/node` amongst them, which never existed on my system O_o how could I see what tries to use it?

So now I'm confused if this is safe to continue.

**Comment by nuclight** [comment]
```
Scanning existing packages.
libreoffice-7.1.0.3_1.txz has less options than required (13)
libreoffice-7.1.0.3_1.txz failed option check.
curl-7.74.0.txz GSSAPI_BASE is ON but port says it must be OFF
curl-7.74.0.txz failed option check.
vlc-3.0.11_9,4.txz has less options than required (77)
vlc-3.0.11_9,4.txz failed option check.
lang/python37 package has less dependencies than the port requires (4)
Query: devel/gettext-runtime:gettext-runtime-0.21
devel/libffi:libffi-3.3_1
devel/readline:readline-8.0.4

python37-3.7.9_1.txz failed dependency check.
devel/py-setuptools@py37 package depends on python37-3.7.9_1.txz which doesn't exist or has been scheduled for deletion
py37-setuptools-44.0.0.txz failed dependency check.
devel/ninja package depends on python37-3.7.9_1.txz which doesn't exist or has been scheduled for deletion
ninja-1.10.2,2.txz failed dependency check.
devel/meson package depends on ninja-1.10.2,2.txz which doesn't exist or has been scheduled for deletion
...
[...many similar lines...]
```

Ok, I look at first of them - libreoffice. Synth did for it:
```
pkg query -F /zp/bsd/synth/live_packages/All/libreoffice-7.1.0.3_1.txz %Ok:%Ov
COINMP:off
CUPS:on
DOCS:on
GNOME:off
GTK3:off
JAVA:off
MMEDIA:on
PGSQL:off
SDK:off
TEST:off
WEBDAV:off
```
That's a dozen.

Now, in `editors/libreoffice/Makefile` I see:
```
OPTIONS_DEFINE= COINMP CUPS DOCS GNOME GTK3 JAVA KF5 MMEDIA PGSQL QT5 SDK TEST WEBDAV
OPTIONS_DEFAULT=        CUPS MMEDIA QT5

.if !defined(DEFAULT_VERSIONS) || ! ${DEFAULT_VERSIONS:Mssl=*}
# Blocked by net/qt5-network: cannot use QT5 with default OpenSSL
OPTIONS_EXCLUDE_FreeBSD_11+=    QT5
.endif
```
The same clause in `vlc`'s port Makefile.

`curl/Makefile` has
`OPTIONS_DEFAULT=        ALTSVC ... GSSAPI_${${SSL_DEFAULT} == base :?BASE :NONE} DICT ...`

For python it's
```
query -F /zp/bsd/synth/live_packages/All/python37-3.7.9_1.txz %do:%dn-%dv
devel/gettext-runtime:gettext-runtime-0.21
devel/libffi:libffi-3.3_1
devel/readline:readline-8.0.4
```
and
```
/usr..lang/python37> make run-depends-list
/usr/ports/devel/libffi
/usr/ports/devel/readline
/usr/ports/devel/gettext-runtime
/usr/ports/security/openssl
```

Exactly my case, eh?

But! in `/usr/local/etc/synth/LiveSystem-make.conf` I have:
```
...
MY_OPENSSL_LIST+= editors/libreoffice
MY_OPENSSL_LIST+= lang/python37
MY_OPENSSL_LIST+= ftp/curl

.for portsslport in ${MY_OPENSSL_LIST}
.  if ${.CURDIR:N*${portsslport}} == ""
DEFAULT_VERSIONS+= ssl=openssl
.  endif
.endfor
```
thus it should be enabled in fact? or not?..

**Comment by jrmarino** [comment]
well, it's actually 11 not 12.
QT5 and KF5 are excluded so 13-2 = 11.
However, freshports shows 14 options for Libreoffice, LTO was recently added I think.  
Are you sure the ports tree doesn't have LTO option in Libreoffice makefile?

We somebody adds an option to a makefile, this is exactly what you see in the logs.

**Comment by nuclight** [comment]
This is quarterly branch, I guess it's in New Year state here still.

BTW, I probably found the problem from #185 leading to `www/chromium` listed to rebuild: python -> glib -> at-spi2-core -> at-spi2-atk -> chromium.

Looked at glib and it has python run-depend (btw Linux people say glib don't dep from python, they split another pkg):
`USE_PYTHON=     py3kplist` - don't know what is this, but port's files just have codegen/*.py - no **real** OpenSSL depends.
Shit! Snake shit!

Can I hack somehow and circumvent rebuilding for glib -> python case?..

Still don't understand, though, why in #185 Synth did not find at least _any_ package to fetch...

**Comment by jrmarino** [comment]
closing as the original report wasn't really a synth problem.
