### ISSUE TITLE
`prepare-system` deletes just-built packages by "failed dependency check"

### ISSUE THREAD

**Issue by nuclight** [jrmarino/synth#184]
Hi, I'm from #183 with synth 2.08_1 and trying to get upgraded to 2021Q1 (Revision: 566552 of ports tree). Finally, it built almost everything, but two packages are constantly deleted and rebuilt again:
```
 ID  Duration  Build Phase      Origin                                   Lines 
===============================================================================
 01  00:44:46  deinstall        emulators/virtualbox-ose                 30718 
 02  Shutdown                                                                  
===============================================================================
 00:31:51 [02] shutdown                                               --:--:--
 00:31:51 [02] success  net/wireshark                                 00:31:07 
 00:00:37 [--] ignored  net-p2p/retroshare                            --:--:-- 
The task is complete.  Final tally:
Initial queue size: 3
    packages built: 2
           ignored: 1
           skipped: 0
            failed: 0

Duration: 00:45:24
The build logs can be found at: /var/log/synth
Stand by, prescanning existing packages.
Stand by, recursively scanning 1181 ports serially.
Scanning existing packages.
virtualbox-ose-5.2.44_4.txz failed dependency check.
wireshark-3.4.2.txz failed dependency check.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt
```
Actually, both packages are built susccessfully, but for some unknown reason:
```
$ cat 06_obsolete_packages.log
emulators/virtualbox-ose package has more dependencies than the port requires (34)
Query: audio/alsa-lib:alsa-lib-1.1.2_2
accessibility/atk:atk-2.36.0
ftp/curl:curl-7.74.0
devel/dbus:dbus-1.12.20_3
graphics/gdk-pixbuf2:gdk-pixbuf2-2.40.0
devel/gettext-runtime:gettext-runtime-0.21
devel/glib20:glib-2.66.7,1
graphics/gtk-update-icon-cache:gtk-update-icon-cache-3.24.24
graphics/libGLU:libGLU-9.0.1
devel/libIDL:libIDL-0.8.14_5
x11/libX11:libX11-1.6.12,1
x11/libXcursor:libXcursor-1.2.0
x11/libXext:libXext-1.3.4,1
x11/libXinerama:libXinerama-1.1.4_2,1
x11-toolkits/libXmu:libXmu-1.1.3,1
x11-toolkits/libXt:libXt-1.2.0,1
net/libvncserver:libvncserver-0.9.13_1
x11/libxcb:libxcb-1.14_1
textproc/libxml2:libxml2-2.9.10_2
textproc/libxslt:libxslt-1.1.34_1
graphics/mesa-libs:mesa-libs-20.2.3
security/openssl:openssl-1.1.1j,1
x11-toolkits/pango:pango-1.42.4_5
graphics/png:png-1.6.37
audio/pulseaudio:pulseaudio-13.0_2
devel/qt5-core:qt5-core-5.15.2
devel/qt5-dbus:qt5-dbus-5.15.2_1
x11-toolkits/qt5-gui:qt5-gui-5.15.2_2
graphics/qt5-opengl:qt5-opengl-5.15.2_1
print/qt5-printsupport:qt5-printsupport-5.15.2_1
x11-toolkits/qt5-widgets:qt5-widgets-5.15.2_1
x11/qt5-x11extras:qt5-x11extras-5.15.2_1
devel/sdl12:sdl-1.2.15_15,2
net/vde2:vde2-2.3.2_5
emulators/virtualbox-ose-kmod:virtualbox-ose-kmod-5.2.44_3

Tripped on: virtualbox-ose-kmod-5.2.44_3.txz:emulators/virtualbox-ose-kmod
virtualbox-ose-5.2.44_4.txz failed dependency check.
net/wireshark package has more dependencies than the port requires (28)
Query: accessibility/atk:atk-2.36.0
dns/c-ares:c-ares-1.16.1
devel/desktop-file-utils:desktop-file-utils-0.26
graphics/gdk-pixbuf2:gdk-pixbuf2-2.40.0
devel/gettext-runtime:gettext-runtime-0.21
devel/glib20:glib-2.66.7,1
security/gnutls:gnutls-3.6.15
graphics/gtk-update-icon-cache:gtk-update-icon-cache-3.24.24
security/libgcrypt:libgcrypt-1.8.7
security/libgpg-error:libgpg-error-1.41
archivers/liblz4:liblz4-1.9.3,1
net/libmaxminddb:libmaxminddb-1.4.3
www/libnghttp2:libnghttp2-1.42.0
net-mgmt/libsmi:libsmi-0.4.8_1
security/libssh:libssh-0.9.5
textproc/libxml2:libxml2-2.9.10_2
security/openssl:openssl-1.1.1j,1
audio/opus:opus-1.3.1
x11-toolkits/pango:pango-1.42.4_5
lang/python37:python37-3.7.9_1
devel/qt5-core:qt5-core-5.15.2
x11-toolkits/qt5-gui:qt5-gui-5.15.2_2
multimedia/qt5-multimedia:qt5-multimedia-5.15.2_1
print/qt5-printsupport:qt5-printsupport-5.15.2_1
graphics/qt5-svg:qt5-svg-5.15.2_1
x11-toolkits/qt5-widgets:qt5-widgets-5.15.2_1
misc/shared-mime-info:shared-mime-info-2.0
archivers/snappy:snappy-1.1.8
comms/spandsp:spandsp-0.0.6

Tripped on: spandsp-0.0.6.txz:comms/spandsp
wireshark-3.4.2.txz failed dependency check.
```
Well, for wireshark if I do
```
$ grep spandsp /usr/ports/net/wireshark/*
/usr/ports/net/wireshark/Makefile:RTP_LIB_DEPENDS=       libspandsp.so:comms/spandsp
```
then I see it is because I've enabled option in `make config` of wireshark, but still - why?

I have enabled fetching packages from official FreeBSD repo so I guess it uses port build options from there? Then it is a bug.

For virtualbox, sutuation is even more strange. In the `synth/live_packages/All` directory, I see the only related file
`virtualbox-ose-kmod-5.2.44_3.txz 128644 bytes 30 Jan`
and no others.

There is line
`RUN_DEPENDS= ${LOCALBASE}/etc/rc.d/vboxnet:emulators/virtualbox-ose-kmod`
in `emulators/virtualbox-ose/Makefile`

So what's wrong? How'd I tell synth to use packages it actually built (with my options) and finally `upgrade-system` with them?

**Comment by jrmarino** [comment]
when you see something like this:
```
net/wireshark package has more dependencies than the port requires (28)
```
You can be sure it's a problem in the port itself, specifically with LIB_DEPENDS or RUN_DEPENDS.
The issue occurs due to how ports dependencies work.  They list libraries and the associated port.  If the library matches a system library, it doesn't get pulled in and the product builds with the system library.  However, synth doesn't know that the dependency was never used, so there's a mismatch on the number of dependencies.  I probably am misremembering a bit, but that's the gist of the problem.

You can figure out the culprit by comparing the list from the query output with the port Makefile.  

The solution?  Once you figure out the culprit, you comment out the line the portfile, and rebuild.  It will then pass repository checks.  (Often you can figure it out just by looking at the makefile -- the system library is usually obvious)

**Comment by nuclight** [comment]
Well, could you please view these two concrete makefiles as I am newbie in ports makefiles?

https://svnweb.freebsd.org/ports/branches/2021Q1/net/wireshark/Makefile?revision=560000&view=markup
https://svnweb.freebsd.org/ports/branches/2021Q1/emulators/virtualbox-ose/Makefile?revision=560000&view=markup

As far as I can see, this is not system library but due to some option in `make config`.

BTW I did `synth just-build net/wireshark emulators/virtualbox-ose` and files are left in repo - can I now just `pkg upgrade` instead of `synth upgrade-system` ?

**Comment by jrmarino** [comment]
To answer your last question -- are you not generating a repository?  But yes, you can run pkg commands directly.

I'm wondering if you have any options set on wireshark.
when I ran this command `make run-depends-list` in the /usr/ports/net/wireshark directory, I only get 25 lines and spansdp isn't one of them.  So either the latest makefile for wireshark is different from yours, or I'm using standard options and you aren't.  If you are intentionally setting options on one or both of these ports, tell me which ones you set.

**Comment by nuclight** [comment]
For last question, I don't quite understand whether I generating a repository or not / which commands, as I've not used synth or pkg much yet.

Yes, I have options on both ports. For wireshark:
```
$ cat /var/db/ports/net_wireshark/options
# This file is auto-generated by 'make config'.
# Options for wireshark-3.4.2
_OPTIONS_READ=wireshark-3.4.2
_FILE_COMPLETE_OPTIONS_LIST=ANDROIDDUMP CISCODUMP DECRYPT GUI LUA MAXMIND OPUS RTP SNMP SSHDUMP GSSAPI_BASE GSSAPI_HEIMDAL GSSAPI_MIT GSSAPI_NONE
OPTIONS_FILE_SET+=ANDROIDDUMP
OPTIONS_FILE_SET+=CISCODUMP
OPTIONS_FILE_SET+=DECRYPT
OPTIONS_FILE_SET+=GUI
OPTIONS_FILE_UNSET+=LUA
OPTIONS_FILE_SET+=MAXMIND
OPTIONS_FILE_SET+=OPUS
OPTIONS_FILE_SET+=RTP
OPTIONS_FILE_SET+=SNMP
OPTIONS_FILE_SET+=SSHDUMP
OPTIONS_FILE_UNSET+=GSSAPI_BASE
OPTIONS_FILE_UNSET+=GSSAPI_HEIMDAL
OPTIONS_FILE_UNSET+=GSSAPI_MIT
OPTIONS_FILE_SET+=GSSAPI_NONE
```
For two virtualbox ports:
```
$ cat /var/db/ports/emulators_virtualbox-ose*/options
# This file is auto-generated by 'make config'.
# Options for virtualbox-ose-kmod-5.2.44
_OPTIONS_READ=virtualbox-ose-kmod-5.2.44
_FILE_COMPLETE_OPTIONS_LIST=DEBUG VIMAGE
OPTIONS_FILE_UNSET+=DEBUG
OPTIONS_FILE_SET+=VIMAGE
# This file is auto-generated by 'make config'.
# Options for virtualbox-ose-5.2.44
_OPTIONS_READ=virtualbox-ose-5.2.44
_FILE_COMPLETE_OPTIONS_LIST=ALSA DBUS DEBUG GUESTADDITIONS MANUAL NLS PULSEAUDIO PYTHON QT5 R0LOGGING UDPTUNNEL VDE VNC VPX WEBSERVICE X11
OPTIONS_FILE_SET+=ALSA
OPTIONS_FILE_SET+=DBUS
OPTIONS_FILE_UNSET+=DEBUG
OPTIONS_FILE_SET+=GUESTADDITIONS
OPTIONS_FILE_UNSET+=MANUAL
OPTIONS_FILE_SET+=NLS
OPTIONS_FILE_SET+=PULSEAUDIO
OPTIONS_FILE_UNSET+=PYTHON
OPTIONS_FILE_SET+=QT5
OPTIONS_FILE_UNSET+=R0LOGGING
OPTIONS_FILE_SET+=UDPTUNNEL
OPTIONS_FILE_SET+=VDE
OPTIONS_FILE_SET+=VNC
OPTIONS_FILE_UNSET+=VPX
OPTIONS_FILE_UNSET+=WEBSERVICE
OPTIONS_FILE_SET+=X11
```

**Comment by jrmarino** [comment]
okay, for wireshark, the dependency causing the issue is 
security/openssl:openssl-1.1.1j,1

Did you say earlier you have a non-standard ssl setup?

**Comment by jrmarino** [comment]
my guess is virtualbox has the same issue

**Comment by jrmarino** [comment]
cd /usr/port/net/wirkshark 
make -V LIB_DEPENDS
openssl isn't on the list.  But it's getting added to the package.
A hack might be to manually add it to the port makefile.  The bigger question is why USES=ssl isn't adding it.

**Comment by nuclight** [comment]
Yes, I've described in #183 that I trying to fix absence of newer openssl and it's dependent packages on 11.4 branch like Qt. So I've used a custom `make.conf` and identical `LiveSystem-make.conf` https://github.com/jrmarino/synth/issues/183#issuecomment-786325988

**Comment by jrmarino** [comment]
so you have a default ssl that defers on a per-port basis?
Yeah, that's probably part of the issue.
At the very least you'll have to set ssl default to openssl on wireshark and virtualbox I think.

**Comment by nuclight** [comment]
Shit, I've found that I've added net/wirkshark to openssl-list in `/etc/make.conf` but forgot to do `cp /etc/make.conf /usr/local/etc/synth/LiveSystem-make.conf`. Added both wireshark and virtualbox, copied, and it completed `prepare-system` succesfully.

Well, except warnings
```
Installed package ignored, multimedia/audacious package unmatched
Installed package ignored, multimedia/audacious-plugins package unmatched
Installed package ignored, graphics/py-cairo package unmatched
Installed package ignored, missing from ports: graphics/py-gimp
Installed package ignored, missing from ports: devel/py-gobject
Installed package ignored, missing from ports: x11-toolkits/py-gtk2
Installed package ignored, missing from ports: devel/vulkan-headers
```
on start, and I still not sure this SSL is correct, but that's topic of another ticket / #183.
