### ISSUE TITLE
"status-everything" chokes on an (arguably) well-formed Makefile

### ISSUE THREAD

**Issue by ALPHA-60** [jrmarino/synth#186]
First of all, thank you for creating Synth, it's the program that got me into Ada language.

I ran `synth status-everyting` on FreeBSD, and got

```
Scanning entire ports tree.
 progress: 1.00%              
culprit: astro/py-spktype21@py37
  Scan aborted because dependency is malformed.
  RUNTIME: 	 py37-jplephem>0:astro/py-jplephem@py37 py37-setuptools>0:devel/py-setuptools@py37 /usr/local/bin/python3.7:lang/python37 (astro/py-spktype21@py37)
Failed to scan ports tree   (Synth must exit)
```

The `astro/py-spktype21` contains an empty NUMPY variable as the first runtime dependency, and a tab afterwards, which creates a leading tab in the output of `make -VRUN_DEPENDS`:

```make
RUN_DEPENDS=	${NUMPY}	\
		${PYTHON_PKGNAMEPREFIX}jplephem>0:astro/py-jplephem@${PY_FLAVOR}
```

I have [reported](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254740) this Makefile issue to the maintainer of `astro/py-spktype21` and `astro/py-spktype10`.

I'm not sure that is is a Synth issue at all, but it came to me that Synth could have a slightly more tolerant parser, which trims spaces *and tabs* from the `make -V...` output, because they are the characters which are already used to split the `make -V` output.

Here's just a quick fix for this particular issue, it is entirely possible it breaks other things because it changes the functionality of already existing functions (`Trim`). The place which it is supposed to affect is https://github.com/jrmarino/synth/blob/5ec51e37c368839a049627ebef215d194c16c7c0/src/portscan.adb#L543

```diff
diff --git a/src/johnnytext.adb b/src/johnnytext.adb
index af0b4c3..e6c0178 100644
--- a/src/johnnytext.adb
+++ b/src/johnnytext.adb
@@ -71,7 +71,7 @@ package body JohnnyText is
    --------------
    function trim (US : Text) return Text is
    begin
-      return SU.Trim (US, AS.Both);
+      return SU.Trim (US, space_and_HT, space_and_HT);
    end trim;
 
 
@@ -80,7 +80,7 @@ package body JohnnyText is
    --------------
    function trim (S : String) return String is
    begin
-      return AS.Fixed.Trim (S, AS.Both);
+      return AS.Fixed.Trim (S, space_and_HT, space_and_HT);
    end trim;
 
    ---------------
diff --git a/src/johnnytext.ads b/src/johnnytext.ads
index 09d53bc..dbf6efb 100644
--- a/src/johnnytext.ads
+++ b/src/johnnytext.ads
@@ -3,11 +3,13 @@
 
 with Ada.Strings.Unbounded;
 with Ada.Strings;
+with Ada.Strings.Maps;
 
 package JohnnyText is
 
    package AS  renames Ada.Strings;
    package SU  renames Ada.Strings.Unbounded;
+   package SM  renames Ada.Strings.Maps;
    subtype Text is SU.Unbounded_String;
    type Line_Markers is private;
 
@@ -109,6 +111,8 @@ private
 
    single_LF : constant String (1 .. 1) := (1 => ASCII.LF);
 
+   space_and_HT : constant SM.Character_Set := SM.To_Set(" " & ASCII.HT);
+
    type Line_Markers is
       record
          back_marker  : Natural := 0;
```

**Comment by jrmarino** [comment]
So you already mentioned the issue -- it's unclear if the change in trim() will have unwanted/unforeseen side effects.
It would be best to leave trim() alone, and create a second function (e.g. trimtab) to handles spaces and tabs, and then update the code that calls make -V to use trimtab instead of trim.

I can see the argument that the makefile is well formed, but I can also see that putting a tab in the make -V output is unwanted.  With the proposed change, Synth would no longer be able to detect that.  The question is if that's synth's job.  I would have argued synth doubles as a developer too.

But if you want to add trimtab function and use it in situations like this, I would approve the pull request.

**Comment by ALPHA-60** [comment]
I agree, it's not clear-cut. Synth detected a real issue with the above port due to its strictness. The strongest argument for trimming tabs for me would be compatibility with existing port builders -- what they are building, synth should probably build also. Otherwise, a benign leading tab would leave the port tree in a quasi-broken state until someone removes it, but  no other tool, not even portlint, would even warn about this tab. I'll check where it makes sense to trim tabs, and send a PR.

**Comment by jrmarino** [comment]
when the PR comes in, once I merge it, I'll make a new release.

**Comment by ALPHA-60** [comment]
#188 should fix this. I didn't touch parsing of `(DE)SELECTED_OPTIONS`, because I wasn't able to inject tabs into `make -V...` output by manipulating, for example "OPTIONS_DEFINE".

**Comment by jrmarino** [comment]
Okay, I created v2.10.
The maintainer (ericbsd) hasn't updated the port in 2 years; he skipped v2.09.  I suggested to Terran to let him know v2.10 is out (since he probably needs it more as it fixes rust build).  Just FYI in case you want to ask ericbsd as well.
