### ISSUE TITLE
Feature request/suggestion: fall back to /etc/make.conf when no <profile>-make.conf found

### ISSUE THREAD

**Issue by bitwise-operators** [jrmarino/synth#189]
I just started using synth, and immediately ran into a surprise (after rebuilding everything):
When you don't create a LiveSystem-make.conf, it doesn't use any config file, even if /etc/make.conf exists.

It would be nice if the application would fall back to /etc/make.conf, if it exists and there is no <profile>-make.conf.

Alternatively, when the system is initialized and there is an /etc/make.conf, it could be copied to LiveSystem-make.conf, to match the default profile in synth.ini.

As a third alternative, the install script could detect the presence of /etc/make.conf, and warn the user who installed synth that the application will not use it, with instructions to manually copy it to LiveSystem-make.conf (although that might be something I need to submit to the FreeBSD port maintainer, not here).

Regards, and keep up the good work!

EDIT: after rebuilding everything from scratch (again), it seems this isn't the problem.
Wherever the file is located, I can't get synth to honour the DEFAULT_VERSIONS set in my make.conf.

If I specify DEFAULT_VERSIONS+=ssl=libressl, it still builds everything against openssl in base, and if I specify DEFAULT_VERSIONS+=php=7.4, I still have to specfify a flavor when I want to install a port that has php flavors.

Is this a bug, or am I doing something wrong? The same make.conf works fine when using portmaster.

**Comment by jrmarino** [comment]
using the system /etc/make.conf can easily cause major issues.  Requiring profile versions of make.conf and ignoring /etc/make.conf avoids strange bugs and behavior that can be a major headache to discover.  (believe me, this has happened).

On the surface, the suggestion seems logical and useful, but in practice it's a recipe for disaster.  remember make.conf is really for building the base system.  using it for packages was probably a bad idea, so synth tried to address that.
