### ISSUE TITLE
Feature Requests: Flags

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#19]
Following flags could be convenient:

- quiet output (e.g. for use w/ cron), e.g. `-q`

- add list-file to the system's installed packages for building (e.g. `synth upgrade-repository -l /usr/local/etc/synth/portlist.conf` to upgrade repository with host packages and the ones supplied in the file).
Maybe additionally to a config option for such a file

- choose specific profile for this build, e.g. `-p libressl`

**Comment by jrmarino** [comment]
i can tell you right now I'm not interested in putting flags in the command line.
I don't want it to look like a git man page.

It's got a simple interface intentionally.

**Comment by jrmarino** [comment]
cron: isn't it possible to write a shell script that launches synth and sends stdout to /dev/null ?

**Comment by jrmarino** [comment]
the profile suggestion is interesting but not sure how to implement it cleanly atm.

**Comment by bax-** [comment]
yes, for sure.
There are quite a few programs that have a `-q`flag so I thought it might be useful for some / something to think about.
It's just some ideas I wanted to suggest.

**Comment by jrmarino** [comment]
maybe profile could be sent with environmental variable.  It's something only an advanced user would need

**Comment by jrmarino** [comment]
--quiet would be a pain to implement.  There are too many places to suppress.  not trivial at all, and of course unhandled exceptions spew.  wrapping it is the way to go

**Comment by bax-** [comment]
sounds reasonable!

**Comment by jrmarino** [comment]
I think I can close this:
quiet: no, just redirect stdout to /dev/null, even in cron.  (profile would not use curses)
list-file: I don't urderstand the point of this at all.  You would just use a master list of files; I see no reason to "append" what's on the host system.  Seems to add complexity for its own sake.

selectable profile: Will be available in next release (soon)

**Comment by bax-** [comment]
the idea of the list file was to make something like

`synth just-build /listfile && synth prepare-system`

into

`synth prepare-system -l /listfile`

So it would rebuild the system's ports and the list's port with just one command.
It's probably confusing and unnecessary.

**Comment by jrmarino** [comment]
that makes no sense, those are two opposing commands
"synth prepare-system" has a ports list, it's generated from the system.
Thus "just-build" and "prepare-system" are not compatible.

prepare-system and system-upgrade are just specialty cases of "synth build", "synth install"

**Comment by jrmarino** [comment]
thus "prepare-system" and a build list are also incompatible

**Comment by bax-** [comment]
Yes but I assumed that `prepare-system`would check for the system's ports, rebuild them if necessary, and then rebuild the repository INCLUDING the ports built from the list file.
And I thought that it had worked that way when I had used `rebuild-repository`before that command was repurposed (to add the ports I had built for the jails to the repository).

**Comment by jrmarino** [comment]
it's a specialty case.  If you want host system + more, then you create a ports file that is host system + more.  pkg can produce the initial list (e.g. "pkg prime-list" should do it) and the user would just augment that.

People are also asking for "exclude lists" too, e..g exclude from host system.  The answer is the same, make a master list and forget prepare-system, upgrade-system commands.

**Comment by bax-** [comment]
You're probably right. I was trying to avoid listing the host system's ports to stay flexible.
It worked the way I did it though.
otherwise I might use 
```
> synth just-build /list && synth rebuild-repository
```
And update the host separately… (`synth prepare-system`)

**Comment by jrmarino** [comment]
yes, that combination will do what you want.

**Comment by jrmarino** [comment]
no, i mean this one:
```
synth just-build /list && synth prepare-system
```

that's what you want.

**Comment by bax-** [comment]
thanks
