### ISSUE TITLE
Feature Request: Command to update any and all packages that have new versions

### ISSUE THREAD

**Issue by Barracuda6** [jrmarino/synth#190]
I am using synth to maintain a local package repository for a number of jails (and for the host system, but that's secondary). It looks like the best way for me to do this right now is to use `synth just-build <list of ports>`.

Before I started using synth, I used `portmaster -ad` inside each jail to upgrade each of the jail's ports that had a new version. I think it would be nice for synth to have a command to build new packages for any package in its package repository that has a new version available in ports.

**Comment by jrmarino** [comment]
well, if you are using <list of ports> against the newest ports tree then you really don't need anything else.  Synth will determine which ports needs rebuilding and in addition will build new dependencies as needed.  The only ports that might not get updated would be dependency ports that are no longer used for building or runtime by the <list of ports>.

To me you are already using the optimal process given a multiple jail setup ... unless I'm missing something?

**Comment by Barracuda6** [comment]
I was hoping to avoid having to maintain a list of ports, but given your explanation this might just be the best way (to avoid unnecessarily rebuilding dependency ports that are no longer used).
