### ISSUE TITLE
Synth ignores devel/qt5-core in FreeBSD 13.0

### ISSUE THREAD

**Issue by cmanv** [jrmarino/synth#191]
Synth is now ignoring devel/qt5-core following a recent change in that port. The port now tests for the existence of /etc/rc.d/os-release which does not exist in Synth's chroot. For FreeBSD versions prior to 13.0, a runtime dependency (sysutils/etc_os-release) is added. For FreeBSD 13.0, that dependency cannot be installed since it's supposed to be in base. The result is that the port is ignored by Synth.

Edit: I've opened an issue in FreeBSD's bugzilla as well.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255354

**Comment by cmanv** [comment]
The issue as been dealt in the port by modifying its logic. However I'm leaving this issue open and let the author of Synth decide whether to include /etc/rc.d/os-release in Synth's chroot when it exists in base.

**Comment by jrmarino** [comment]
I'm going to close this without doing anything, but if this issue returns (needing support for os-release) I'm happy to revisit.
