### ISSUE TITLE
Does synth resize columns?

### ISSUE THREAD

**Issue by qcybb** [jrmarino/synth#192]
Does synth resize columns in the console window?

I'm running in to a really strange issue. Every time Synth is building packages, my console goes from 130 columns to 80 columns.

Instead of a pure black background, everything shifts to the left.

![issue](https://user-images.githubusercontent.com/16991734/117203944-80ad1280-ada4-11eb-86cd-fd085f8ea6b5.png)

**Comment by jrmarino** [comment]
it responds to resize events and may (I can't remember) refresh
periodically anyway (ncurses based).  So yes, it's probably responsible.
You may wish to use the dynamic html version of the status instead on the
console.

**Comment by qcybb** [comment]
Ok, thank you.

It appears SecureCRT has an option to disable 80/132 column switching, so feel free to close this issue.

**Comment by jrmarino** [comment]
Thanks
