### ISSUE TITLE
sys/sys/param.h in freebsd/main loses comment after __FreeBSD_version

### ISSUE THREAD

**Issue by Ximalas** [jrmarino/synth#193]
Commit <a href="https://cgit.freebsd.org/src/commit/sys/sys/param.h?id=9e0ba9536b7cbba0e81e561458e95aafb65ee485">`﻿9e0ba9536b7cbba0e81e561458e95aafb65ee485﻿`</a> removed the `﻿/* Master, propagated to newvers */﻿` comment after `__FreeBSD_version` in `﻿sys/sys/param.h﻿` in FreeBSD's main branch aka 14.0-CURRENT.

synth now﻿ believes I'm running FreeBSD 1.0. I temporarily doctored my `/usr/include/sys/param.h` and that will hold up until the next time I upgrade my "LiveSystem".

The same commit says this is proper way to extract `__FreeBSD_version`:
`awk '/^\#define[[:space:]]*__FreeBSD_version/ {print $3}'`
I believe there's a small mistake in the regexp and it should be `^\#define[[:space:]]+__FreeBSD_version`.

At any rate, `get_osversion_from_param_header` in `src/replicant-platform.adb` should be changed to cope with the missing comment.

**Comment by jrmarino** [comment]
Thank you for a very detailed explanation with links.
At first glance, the `get_osversion_from_param_header` should not have been affected by removing the comment and the spaces that precede it.  But obviously your experience says otherwise.  I'll take a harder look.

**Comment by jrmarino** [comment]
okay, I see the logic flaw now

**Comment by jrmarino** [comment]
Okay, I believe I fixed it and created a new release, 2.11.
Can you let the port maintainer know so he can bring it in?  And close the issue when that's done?

**Comment by fluffykhv** [comment]
[port maintainer mode on]:  landed in main (https://cgit.FreeBSD.org/ports/commit/?id=a53b9c858eb613ea9f1e79d0b31655d747cc5275) and quarterly (https://cgit.FreeBSD.org/ports/commit/?id=8527b435b418ca72092601127e9229f949663cb8) branches

**Comment by Ximalas** [comment]
Synth 2.11 works as expected in freebsd/src/main post commit <a href="https://cgit.freebsd.org/src/commit/sys/sys/param.h?id=9e0ba9536b7cbba0e81e561458e95aafb65ee485">`﻿9e0ba9536b7cbba0e81e561458e95aafb65ee485﻿`</a>.
