### ISSUE TITLE
pkg 1.17.0 in FreeBSD changes package suffix to .pkg

### ISSUE THREAD

**Issue by Ximalas** [jrmarino/synth#197]
With pkg 1.17.0, `freebsd/ports/main` commit `e497a16a286972bfcab908209b11ee6a13d99dc9` (https://cgit.freebsd.org/ports/commit/?id=e497a16a286972bfcab908209b11ee6a13d99dc9), package suffix is now `.pkg`.
This causes the command `synth rebuild-repository` to believe the package repository is empty.
A workaround is to run `pkg repo /path/to/repo`.

Actually, this issue is more severe, as it turns out Synth believes it must (re)build every port specified, because the associated `.txz` files no longer exists.

**Comment by qcybb** [comment]
I'm having the same issue.

However, only 44 of 215 packages are stored (in .pkg format) in the packages directory. The rest are missing.

Synth is now rebuilding all 171 missing packages anytime there is a new update. Those never get packaged up. No errors or warnings in the logs file. They are all shown as green and marked as "Built".

**Comment by jrmarino** [comment]
So obviously this is a pretty big deal.
What's the suggested approach?  For people that have pre-4.17 pkg, they have to continue using current version of synth and people using 4.17 pkg and newer have to use a new release of synth?  In other words, can Synth handle a single extension (either .txz or .pkg)? Because if it has to support both simultaneously that's a log more complicated.

**Comment by jrmarino** [comment]
does someone want to try to build this and try it?
https://github.com/jrmarino/synth/commit/889368421b42d918ea63de5b8687e7d186505597

It's on a working branch: 
https://github.com/jrmarino/synth/tree/txz-to-pkg-extension

**Comment by Ximalas** [comment]
I gave it a go at my "proving ground" (stable/13) at ${WORK}, and later on the dedicated builder (stable/12) also at ${WORK}. I saw no undesired side effects. The latter is currently rebuilding all ports we use at ${WORK}.

I'm now at home rebuilding `synth`(1) om my laptop (current) and I will shortly rebuild all my ports and experiment with `PKG_COMPRESSION_FORMAT=tzst` in `LiveSystem-make.conf`. Listening to the Interstellar soundtrack at the same time is highly motivating.

**Comment by daemonblade** [comment]
I've just tried the new code and it appears to work fine.

**Comment by jrmarino** [comment]
here's a follow-on commit:
https://github.com/jrmarino/synth/commit/eedd497427fafe36a640e6d6217624254d345a57
Primarily it removes the "-xz" switch for the pkg package extraction.

I think everyone is saying this branch is working as expected (even without the last commit) so if I can get one or two more confirmations, I can merge this into master and cut a new release.

**Comment by shiorid** [comment]
`txz-to-pkg-extension` works on 14-CURRENT

**Comment by jrmarino** [comment]
okay, I'll merge the branch and cut a new release

**Comment by Ximalas** [comment]
> here's a follow-on commit:
> [eedd497](https://github.com/jrmarino/synth/commit/eedd497427fafe36a640e6d6217624254d345a57)
> Primarily it removes the "-xz" switch for the pkg package extraction.
> 
> I think everyone is saying this branch is working as expected (even without the last commit) so if I can get one or two more confirmations, I can merge this into master and cut a new release.

The builder at ${WORK} finally finished with `synth rebuild-repository`:

```
Stand by, prescanning existing packages.
Stand by, recursively scanning 841 ports serially.
Scanning existing packages.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt
```

All metadata is present and accounted for:

```
# ll /var/synth/live_packages
total 348
drwxr-xr-x  2 root  wheel       3 Jul 23 09:33 .tmp/
drwxr-xr-x  2 root  wheel    1719 Jul 23 17:55 All/
drwxr-xr-x  2 root  wheel       5 Jul 23 10:24 Latest/
-rw-r--r--  1 root  wheel     163 Jul 23 17:58 meta.conf
-rw-r--r--  1 root  wheel     792 Jul 23 17:58 meta.pkg
lrwxr-xr-x  1 root  wheel       8 Jul 23 17:58 meta.txz@ -> meta.pkg
-rw-r--r--  1 root  wheel  242480 Jul 23 17:58 packagesite.pkg
lrwxr-xr-x  1 root  wheel      15 Jul 23 17:58 packagesite.txz@ -> packagesite.pkg
```
I think the `txz-to-pkg-extension` branch is ready for release.

**Comment by jrmarino** [comment]
okay, release https://github.com/jrmarino/synth/tree/v2.12 is published.
Can somebody let fluffy know?

**Comment by Ximalas** [comment]
> okay, release https://github.com/jrmarino/synth/tree/v2.12 is published.
> Can somebody let fluffy know?

I'll send an email.

**Comment by Ximalas** [comment]
I hope there's no objections to me closing this issue.
