### ISSUE TITLE
synth doesn't want to install packages after building them

### ISSUE THREAD

**Issue by kworr** [jrmarino/synth#2]
Probably this is a first-run issue, or I was messing with my configuration:

    # synth install sysutils/tmux
    After inspection, it has been determined that there are no packages that
    require rebuilding; the task is therefore complete.
    Scanning entire ports tree.
    Local repository successfully rebuilt
    No repositories are enabled.
    Unfortunately, the system upgraded failed.
    #

There's nothing in logs. I'm missing a clue on what's going on.

**Comment by jrmarino** [comment]
does /usr/local/etc/pkg/repos/00_synth.conf exist?

if so, what are the contents?

**Comment by kworr** [comment]
Nope, no such file. Directory writable.

**Comment by jrmarino** [comment]
okay, that's a legitimated bug.  synth is supposed to create / rewrite file that before trying to install the packages.

**Comment by jrmarino** [comment]
Okay, I think it's fixed.
If you had run "synth upgrade-system" first, we wouldn't have seen this issue because the repo conf file would have then been in place.  we got lucky in that aspect.

**Comment by kworr** [comment]
Can't confirm this one: when running `synth build` or `synth force` it still refuses to install packages.

**Comment by jrmarino** [comment]
I only fixed "install".  I probably need to handle "build" and "force" too. <sigh>

**Comment by jrmarino** [comment]
should be fixed now.
