### ISSUE TITLE
Assignments using != makes Synth 2.12 choke when port options are set for www/chromium (FreeBSD)

### ISSUE THREAD

**Issue by Ximalas** [jrmarino/synth#202]
<a href="https://cgit.freebsd.org/ports/tree/www/chromium/Makefile">`www/chromium/Makefile`</a> in the FreeBSD ports tree recently acquired a new line <a href="https://cgit.freebsd.org/ports/tree/www/chromium/Makefile#n210">210</a> which goes like this:

```
BASE_MEMPCPY!=	${GREP} mempcpy ${CROSS_SYSROOT}/usr/include/string.h
```

With port options being set for `www/chromium`, against common Synth advise, Synth 2.12, when invoked as `synth status www/chromium`, have this to say:

```
Cached options obsolete: www/chromium

A preliminary scan has revealed the cached options of one port are
obsolete.  Please update or remove the saved options and try again.
  e.g. make -C /usr/ports/www/chromium config
  e.g. make -C /usr/ports/www/chromium rmconfig
```

I run FreeBSD Current and I don't need the patch for a missing `mempcpy`(3) function, and I can easily comment out this line in the `Makefile`. This makes Synth go mute on the subject, and this makes us both happy, at least in the short run.

Long ago, I saw a similar issue with `lang/mono`, but I let it slide by never configuring `lang/mono`. For once I actually agreed with the default port options.

Today, I discovered that the culprit is line <a href="https://cgit.freebsd.org/ports/tree/lang/mono/Makefile#n63">63</a> of <a href="https://cgit.freebsd.org/ports/tree/lang/mono/Makefile">`lang/mono/Makefile`</a>. Here are lines <a href="https://cgit.freebsd.org/ports/tree/lang/mono/Makefile#n61">61</a> to <a href="https://cgit.freebsd.org/ports/tree/lang/mono/Makefile#n64">64</a> to give more context:

```
LOCALBASE?=	/usr/local
.if !exists(${LOCALBASE}/bin/mcs)
OPTIONS_SLAVE=	MONOLITE
.endif
```

Synth apparently reacts to the assignment to `OPTIONS_SLAVE`, and maybe Synth misses the surrounding condition. For completeness, here's Synth's complaint when run as `synth status lang/mono`:

```
Cached options obsolete: lang/mono

A preliminary scan has revealed the cached options of one port are
obsolete.  Please update or remove the saved options and try again.
  e.g. make -C /usr/ports/lang/mono config
  e.g. make -C /usr/ports/lang/mono rmconfig
```

I think Synth should accept special assignment operators like `!=`. After all such operators are part of valid Makefile syntax, at least in FreeBSD. Maybe the real issue is something else.

**Comment by jrmarino** [comment]
it's not an assignment.  != means to run the executable, in this case grep,.
But it does evaluate it because it runs make which tries to.
There's something else wrong, e.g. maybe GREP isn't defined or it's missing.
Putting evaluations in the port tree like this is pretty terrible -- it's the reason why it takes 15 minutes plus to generate the index even on a fast machine.

**Comment by Ximalas** [comment]
No, I checked the variables to see if they have any values at all. They all check out.

**Comment by jrmarino** [comment]
```
> env ENTERAFTER=patch synth test chromium
> cd /port
> make -V  BASE_MEMPCPY
```

what is the output

**Comment by Ximalas** [comment]
Synth is running right now on my laptop, but here's the last command's output:

```
# make -C /usr/ports/www/chromium -V BASE_MEMPCPY
void	*mempcpy(void * __restrict, const void * __restrict, size_t);
```

**Comment by jrmarino** [comment]
It's important to run it inside the build environment.

**Comment by Ximalas** [comment]
Right, from within the build env it's missing:
```
# grep mempcpy /var/synth/systems/main-local-amd64-n245945-460e8d61fd20/usr/include/string.h
# 
```
It looks like I should create a new system snapshot and upgrade the LiveSystem.

**Comment by Ximalas** [comment]
It's clear this was a pilot error on my part, and I learned two valuable lessons. The system snapshot was out of date and the test mode of Synth is something to be explored further. John, I'm sorry for wasting your time.

**Comment by jrmarino** [comment]
```
cd /xports/www/chromium
```
yeah, I says "/port".  sorry about that.  That's different between ravenadm (the successor to synth for ravenports).  You figured it out though.  Yes, interactive build and test mode are powerful tools for figure out port issues.
