### ISSUE TITLE
Orphaned Symbolic Links

### ISSUE THREAD

**Issue by qcybb** [jrmarino/synth#205]
My `/var/synth/live_packages/All` directory is full of orphaned symbolic links. 

Are these not supposed to be cleaned as well when Synth is removing the old packages?

**Comment by jrmarino** [comment]
I though All only contained one link, to pkg
I don't recall there being code to read dangling symlinks though.  It would have to be added.

**Comment by qcybb** [comment]
I'm sorry, I should have updated this months ago and better described the issue.

The "All" directory was full of symlinks that were listed as somepackage.txz -> somepackage.pkg

Every .pkg file had a corresponding .txz symlink pointing to it. I assumed this was something Synth was doing during package creation.

With that said, I'm not sure what happened but this issue resolved itself. The symlinks are no longer there and the "All" directory only contains .pkg files again.

**Comment by jrmarino** [comment]
right, I understood you.  I just remembered (from the last time I used freebsd pkg) that the All directory only contained one symlink.  So something has changed, or you have a different configuration.

so if it resolved itself (it sounds like it's back to the behavior I remember) then there was probably a bug in the ports tree Mk framework for a while and somebody fixed it.

**Comment by qcybb** [comment]
Yeah, that's probably what happened. It was messy in there for a while through.

Please feel free to close this issue.

**Comment by jrmarino** [comment]
thanks.
