### ISSUE TITLE
Reproducible builds support

### ISSUE THREAD

**Issue by ghost** [jrmarino/synth#206]
Does `snyth` support reproducibly built packages through `SOURCE_DATE_EPOCH`? If `SOURCE_DATE_EPOCH` is set to the `TIMESTAMP` in `distinfo` when `pkg create` is called, it should allow for a number of packages to be reproducible.

**Comment by jrmarino** [comment]
I can't find current documentation on SOURCE_DATE_EPOCH.  I assume the
ports tree sets it under specific circumstances, probably a make.conf
variable or the setting of an environment variable.  If you tell me how
it's done for poudriere, I can likely tell you how to set it on synth too.
John

**Comment by jrmarino** [comment]
you could actually have a script update an environment file that synth picks up. 
from man page 
```
<profile>-environment
		       This is an optional, user-provided file.	It contains a
		       list of name-value pairs	joins with an equals sign
		       (e.g. HTTP_PROXY=http://proxyserver:8888/), one pair per
		       line.  If the file exists, these	variables will be de-
		       fined in	the builder environment.  For the default pro-
		       file, the file would normally be	located	at
		       /usr/local/etc/synth/LiveSystem-environment
```

so you can set SOURCE_DATE_EPOCH yourself in that file
