### ISSUE TITLE
Synth EOL? : Depends on expired lang/gcc6-aux

### ISSUE THREAD

**Issue by qcybb** [jrmarino/synth#208]
Any plans to address this issue?

Checking for packages with security vulnerabilities:
synth-2.12: Tag: expiration_date Value: 2022-06-30
synth-2.12: Tag: deprecated Value: Depends on expired lang/gcc6-aux

I emailed fluffy and they said:

Yes, synth is marked as expired because lacks of Ada compiler.
gcc6-aux is outdated and dead, alternative Ada compiler is not ported to FreeBSD, so yes, synth port have no future.

**Comment by jrmarino** [comment]
I've got no connection to FreeBSD anymore.   There's no technical reason to
remove gcc6-aux, the ports guys are just being vindictive.  You synth users
need to raise he'll to change their minds.

However, I could add synth to http://www.ravenports.com and at least
freebsd users could get it from there.

**Comment by ALPHA-60** [comment]
I commented on this issue in ports@FreeBSD.org: https://lists.freebsd.org/archives/freebsd-ports/2022-June/002045.html

If anyone else is affected by this, please chime in.

**Comment by jrmarino** [comment]
I've started work on adding the synth port to Ravenports.
Once it's finished, I'll rebuild all FreeBSD packages and put out
instructions how to install it.
As for your concern about losing Ada in general on FreeBSD, it's all
conserved in Ravenports.

**Comment by jrmarino** [comment]
So this was done a long time ago, but an unrelated problem prevented me from publishing the packages.
I've written instructions on how to install Synth on AMD64 from Ravenports.
It would be great if you could proof the instructions for me and verify Synth from Ravenports still works as expected:

https://github.com/jrmarino/Ravenports/wiki/Synth_Install

**Comment by jrmarino** [comment]
any news about the synth EOL?
Did you try installing from Ravenports (per the wiki) ?  (now at https://github.com/Ravenports/Ravenports/wiki/Synth_Install )

**Comment by qcybb** [comment]
I have not tried installing it from Ravenports yet as Synth is still in the ports system.

As for the EOL issue, this is what is showing up in my daily security emails :

Checking for packages with security vulnerabilities:
Database fetched: Sun Oct 16 03:55:47 PDT 2022
synth-2.12: Tag: expiration_date Value: 2022-06-30
synth-2.12: Tag: deprecated Value: Depends on expired lang/gcc6-aux

**Comment by qcybb** [comment]
Ok, I'll try and check it out a little bit later this week.

**Comment by qcybb** [comment]
Ok, in case I miss it please keep me posted.

**Comment by jrmarino** [comment]
I've pushed a new repository for FreeBSD this morning, so hopefully I've addressed those issues.  If you want to test out the wiki instructions now, feel free.

**Comment by qcybb** [comment]
Ok, thanks! I'm not sure I will have time today, but I should be able to test it over the weekend.

**Comment by flux77** [comment]
Is Synth still at risk of being removed from the FreeBSD ports tree now that there is [lang/gnat12](https://www.freshports.org/lang/gnat12/) in the ports tree?

**Comment by jrmarino** [comment]
I have nothing to do with it, but I would think no.
1) synth builds with newer gnat
2) that gnat12 needs gcc-aux to build.
so if they need gcc-aux anyway, there's no motive for removing synth.

and there's always a backup plan if that happens (it's built by ravenports)

**Comment by lispstudent** [comment]
Just FYI, [synth is still available in ports](https://www.freshports.org/ports-mgmt/synth).
