### ISSUE TITLE
Use for jails?

### ISSUE THREAD

**Issue by rwv37** [jrmarino/synth#209]
I'm finally biting the bullet and trying to figure out jails. I think I have a basic grasp on them, but I'm not exactly sure how to use Synth for them (I mean to manage the contents of jails; I don't mean "I want to run Synth in a jail", which I understand is not the way it should be done). Frankly, I have been so very happy with Synth compared to every other ports management thing I've ever used that if it comes down to one or the other, no question I'm keeping Synth and forgetting about jails. But I want both.

Here's my current methodology for installing new ports, which has consistently worked flawlessly for me:

1. _(add the new ports to my file "topLevelPackages.txt")_
2. synth status topLevelPackages.txt
3. synth just-build topLevelPackages.txt
4. synth rebuild-repository
5. synth install _(port)_
6. _(rinse and repeat step 5 for each new port)_
7. pkg autoremove

The specific thing I'm most concerned with is step 5, "synth install". How do I tell it to install into the jail? I don't see any option (akin to pkg's "-j") in the documentation or the man page, and googling hasn't helped me.

Thanks in advance.

**Comment by jrmarino** [comment]
I think you would generate a repository, make that repository accessible for the jail (e..g. on a mount) and then inside the jail run pkg commands to install.

"synth install" is just a convenience command wrapping "pkg commands" that in some ways I regret implementing.

**Comment by rwv37** [comment]
OK, I'll give it a shot. Thanks again!

**Comment by rwv37** [comment]
Seems like it's working great!

A note about one minor hiccup that may help somebody reading this in the future: Make sure you set up a config file for pkg within the jail itself (even though you're going to use the host's pkg with the "-j" flag, not the jail's pkg, to access it).
