### ISSUE TITLE
Add environment variable or command-line switch to temporarily enable/disable ncurses interface

### ISSUE THREAD

**Issue by chenein** [jrmarino/synth#216]
I mostly want to run synth from cron (nightly prepare-system), but occasionally I want to run the same configuration interactively with ncurses (e.g. when adding a port to my top-level list for the first time).

I recognize that I can manually re-configure the profile to add/remove ncurses flag, but that creates multiple steps (potential to forget) and is not easy to script. Is there a possibility to allow this to be requested on the command line?

Alternatively, is it possible for synth to disable ncurses temporarily when TERM=dummy is set (similar to "synth status").

**Comment by jrmarino** [comment]
okay, so see this code:

https://github.com/jrmarino/synth/blob/cc05e2d260e1d162dc1ce29c56cee3a00987469b/src/portscan-pilot.adb#L1860-L1870

so basically it's suggesting to define TERM=dumb on the cron task directly.  So not exactly what you were suggesting, but that's the workaround people have been using since the beginning

**Comment by chenein** [comment]
Thanks for this, I had followed "dummy" from a forum post someplace, but "dumb" works.

Suggest you amend the github description as follows:


**Non-curses mode**

There is a text mode for the building phase. It shows much less information than the curses-based screen, but if curses is acting up, the text mode gets the job done just fine. Also, when cron launches Synth, it is required that it be using a profile that has disabled the curses display **or set TERM=dumb**.

**Comment by jrmarino** [comment]
thanks, done.
