### ISSUE TITLE
feature-request: show UPDATING

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#22]
feature-request:
Show UPDATING information of a port which was added since the last build if issuing status, build, install, prepare-system or upgrade-system.

**Comment by jrmarino** [comment]
1) the request doesn't account for 20 UPDATING messages and 
2) the majority of UPDATING is not applicable to Synth.  It's for crappy portmaster and hand-updating via pkg.  Only UPDATING messages dealing with data (and not the package themself) would apply (e.g. dump pgsql databases first, uninstall, reinstall, reimport).
3) doesn't package do something with UPDATING ?
4) how would this redundant information even be displayed?  Not dumping to stdout at the end.  A log would be overwritten.

UPDATING isn't handled well anywhere, it's not a good system.

**Comment by matt-xtaz** [comment]
@bax - I use an alias in my shell (bash) as below. Just run this before you run synth, it shows you any entries that have been added within the last fortnight. Though as @jrmarino says most of them don't apply to synth anyway.

alias pnotes='pkg updating -d `date -v-2w +%Y%m%d`'

**Comment by jrmarino** [comment]
Maybe github is having a problem?  I got this via email from xtaz but I don't see it on the ticket!

> @bax - I use an alias in my shell (bash) as below. Just run this before you run synth, it shows you any entries that have been added within the last fortnight. Though as @jrmarino says most of them don't apply to synth anyway.

```
alias pnotes='pkg updating -d date -v-2w +%Y%m%d'
```

seems like a good tip!

**Comment by jrmarino** [comment]
does not work for me though:
```
pkg: illegal option -- v
Usage: pkg updating [-i] [-d YYYYMMDD] [-f file] [portname ...]
For more information see 'pkg help updating'.
```

**Comment by bax-** [comment]
thanks @jrmarino @xtaz
