### ISSUE TITLE
Saving a file from a port's work directory?

### ISSUE THREAD

**Issue by rwv37** [jrmarino/synth#222]
I've been having a problem building a certain port, and the maintainer has asked for a certain file from its work directory (```/construction/xports/lang/gnat12/work/.build/config.log```). It seems to me like ```/construction``` is something that Synth automatically makes and automatically destroys? In any case, I have no such directory on my machine. Is there a way to save that file so that I can access it after Synth finishes up? Thanks.

**Comment by jrmarino** [comment]
Break into the build interactively with the ENTERAFTER environment variable and the "test" mode.

e.g.
```
env ENTERAFTER=build synth test gnat12
```
when it stops and give you the prompt, you have two options:

1) from another terminal, access the files you want from the builder directory.  I can't remember what that is, something like "/var/synth/builders/SL09" maybe.

2) from the prompt, copy the file you want to say "/distfiles".  When you hit "exit" the file will be inside the distfiles directory where you can move it somewhere else.

**Comment by rwv37** [comment]
Thank you!
