### ISSUE TITLE
minor display bug in report

### ISSUE THREAD

**Issue by rwv37** [jrmarino/synth#229]
I just noticed that the HTML report of my current synth run says "Kickoff: 29 SEP 2024, 03:52:30 UTC". I actually started it on September 29, 2024 at (about) 23:52:30 Eastern Daylight Time, which would be September 30, 2024 03:52:30 UTC. So it looks to me like it adjusted the time, but not the date.

**Comment by jrmarino** [comment]
yeah, looks like a failed edge case.  the date and time and imaged differently.
https://github.com/jrmarino/synth/blob/20edc379c0b4b12e79962f7be13f2c80d8d0740b/src/portscan.adb#L1485-L1488

The solution isn't immediately obvious.
