### ISSUE TITLE
feature-request: don't require origin if port is already built

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#23]
similar to postmaster, it would be nice to not require the origin of a port if the package already was built (e.g. recognize `curl` as `ftp/curl` if curl was built / installed before).

**Comment by jrmarino** [comment]
no, sorry.
What's the point of these kind of "feature requests" that try to turn it into portmaster? 
This isn't portmaster.  Synth doesn't work on package names, it works (intentionally) on origins.  There's almost no benefit for the risk of introducing bugs into tested code.  What's the payoff?

**Comment by jrmarino** [comment]
by the way, even though I've never used portmaster, I doubt it "remembers" previously built ports.  It's probably just reading the INDEX and allows the port to be specified by it's pkgname name.  I suspect it would work even before it's ever been built.

**Comment by bax-** [comment]
Of course you're absolutely right. It would only be a convenience feature.

**Comment by jrmarino** [comment]
well, do you really think it's more convient to specify a port by package name?

Which is more intuitive: japanese/awk or ja-awk ?  devel/gps or gps-ide?

While often one can guess a package name from the port origin, it's not foolproof and it can be quite different.

**Comment by jrmarino** [comment]
I'm going to keep port origins as the only way to reference a port.  It's consistent and unambiguous (and I don't think using pkg name saves much, especially if port origins are listed in a file) so closing this one.
