### ISSUE TITLE
UI appears to hang when display resizes

### ISSUE THREAD

**Issue by kgaughan** [jrmarino/synth#24]
I was trying out synth after installing it from FreeBSD ports while running it in a tmux session. I had synth running in one pane, and top running in another. When I closed the pane running top, synth's display stopped updating. From what I can tell, synth kept building the jobs it was currently building, and then stopped running further build jobs. It still responded to the exit keystroke.

I'm not 100% sure what's going on, but my best guess (it's over 15 years since I last wrote anything in Ada) is that synth isn't handling SIGWINCH signals sent by tmux properly.

I've managed to replicate the behaviour reliably in tmux. I've yet to try it in another terminal multiplexer, or in a terminal with no multiplexer.

The version installed from ports is 0.99_6, and it's running on an x86 build of FreeBSD 10.1p24. I'll try digging around the code myself this evening to see if I can spot where the problem might lie.

**Comment by jrmarino** [comment]
what are you expectations?
the width is 80 characters, fixed, intentionally.
The height is variable but only when it launches.  After it figures out how tall the window is, it keeps it there.  Thus the only directory it could change is vertical, but does it matter?

solution: set the window to the proper height before starting?

**Comment by kgaughan** [comment]
I'm not expecting the content to resize, just that the UI shouldn't hang if the display resizes for some reason.

Where this might be important is if somebody has synth running in a terminal multiplexer on a server, they disconnect from the server, and then connect on another machine with a different resolution. In that case, the terminal multiplexer is going to resize, and that resize shouldn't cause synth to break.

**Comment by jrmarino** [comment]
I use screen and it really hasn't been a problem.  If you reconnect at a resolution too small, widening the window to accommodate the original size the restores the display.  I haven't seen a "freeze" as you describe here.

Also every 30 seconds the display is completely redrawn that that's the longest it should be corrupt.  Would tmux be different than screen?

**Comment by kgaughan** [comment]
In this case, the window is getting bigger and it's halting entirely: the worker threads finish up what they're doing and nothing more is processed.

I'm currently going back over an Ada tutorial to help refresh my memory so I can start fiddling with the code in the hopes of finding out what's happening.

**Comment by jrmarino** [comment]
that might be tmux-specific.  I've never seen that with _screen_.

is tmux actually throwing an interrupt signal?  I could see that distressing synth.

**Comment by jrmarino** [comment]
by the way, the first person to submit a git hub PR on Ada code gets a cookie. :)  Bapt@ thinks I'm never getting one.

**Comment by kgaughan** [comment]
OK, now you've made it a challenge. :-) It might take a while though: it really has been a while!

**Comment by jrmarino** [comment]
I can reproduce this now.  I don't think adacurses even has a binding for detecting a screen resize.  I'm not sure how to deal with this.  The screen is supposed to redraw every 30 seconds (to clear stderr messages that get printed to screen and mess up the display) so maybe I could just do a full resize, but I'm not sure that would even work given that curses appears to just stop when a resize happens.

**Comment by jrmarino** [comment]
i haven't been successful in fixing this.   The SIGWINCH signal is getting handled by the default handler, which is on, I think, so something else is breaking as a result of the signal.  I just don't understand what yet.  I won't be able to get this fixed for v1.42 as I had hoped.

**Comment by markuspf** [comment]
I'd quite like to try synth, but with a tiling WM I keep running into the resize issue, which is a bit irritating, so I'd appreciate a fix!

**Comment by jrmarino** [comment]
1) The ncurses display is optional, there's a text mode that is not affected by reszing
2) why does using a tiling WM mean that resizing happens?  Can't a window be locked down?

**Comment by jrmarino** [comment]
The tasking was masking the unhandled exception:
> raised TERMINAL_INTERFACE.CURSES.CURSES_EXCEPTION : terminal_interface-curses.adb:144

Now I just have to figure out where to handle it.

**Comment by jrmarino** [comment]
Fix published.
