### ISSUE TITLE
Feature Request: Display progress periodically when ncurses is off

### ISSUE THREAD

**Issue by kmoore134** [jrmarino/synth#26]
We are using synth in a jenkins automated environment, and as such not using the ncurses interface. While it works, it would be nice to have some way to look at the output and determine how many packages are left, how many built, etc. 

Would it be possible to display that every so often in the output? I.E. after X number of builders have finished, or every X number of minutes display a line like:

XX:XX:XX => Status (XX Built, XX Pending, XX Failed, XX Skipped)

**Comment by jrmarino** [comment]
is the running log the best place for this?
maybe updating a 6th log (e.g. 06_progress.log) periodically would be better?

**Comment by jrmarino** [comment]
in other words, it just updates the tally periodically, so the log would be < 10 lines always

**Comment by kmoore134** [comment]
That would be good also, but it would still be handy if there was an option to periodically read / display that on stdout from synth itself. Otherwise I have to manually expose that log file to jenkins somehow.

**Comment by jrmarino** [comment]
Let's start with the running log then.  What period?  60 seconds?

**Comment by kmoore134** [comment]
60 seconds might be overkill, 3-5 minutes instead?

**Comment by kmoore134** [comment]
Works here, thanks!
