### ISSUE TITLE
Feature Request: Use alternative /usr/src

### ISSUE THREAD

**Issue by kmoore134** [jrmarino/synth#27]
Right now we can specify a different system version using "Directory_system=". However the /usr/src directory still gets mounted into them. It would be nice if we could specify another location for system sources to get mounted into builder. Alternatively, if the system directory specified already has /usr/src populated, just skip the mount entirely.

**Comment by jrmarino** [comment]
truthfully I am not very wild about this particular suggestion.  It's not a technical issue although adding new config parameters isn't quick.

You may have noticed that synth interfaces and knobs are simplistic.  I even started using env variables to avoid added command line switches etc.  because it's aimed at users and not devs and taking portmaster interface as a lesson of what to avoid, that's what I came up with.  So I am careful about what gets added.

In this specific scenario, a change of procedure is just as effective as a change in the program.  The user can null mount any src directory on top of the target system root and synth will just mount it again.

I can perhaps imagine this is something jenkins needs/could use, but the original vision was that the system root was integral and present to Synth as correct.

Can't the various system roots be prepared prior to run? (I'm not even asking why it's /usr/src doesn't match the system root)  My favorite question (from NASA) is "what the impacts to operations if the request is *not* granted?"

**Comment by kmoore134** [comment]
What I'm doing right now is splatting the correct system sources in /usr/src as you suggested, and that works fine. However that seems kinda "icky" since on an 11.0-CURRENT host, I like to keep my 11.0-CURRENT sources in /usr/src. Since I'm building packages for 10.X on 11.X, it would be nice if I could just tell synth where my 10.X system sources are located. 

Otherwise I run into an issue down the road, where I go to upgrade the host system from /usr/src sources, and some leftover 10.3 sources are still there.

**Comment by jrmarino** [comment]
I'm re-reading this and IIUC your setup isn't what I would expect.

For example, I'd expect something like

```
A: /
A: /bin     
A: /boot
A: /lib
A: [more]
A: /usr
A: /usr/src
B: /f10/
B: /f10/bin
B: /f10/lib
B: [more]
B: /f10/usr
B: /f10/usr/src
```
so the "A" profile, which represents FreeBSD 11-current would have system root of "/".
The "B" profile, which presents FreeBSD 10.x-release would have a system root of "/f10"

so having 11-0 sources in /usr/src is correct.
Using "/" as the system root for FreeBSD 10 would be incorrect.  If I'm understanding correctly, you don't actually have a FreeBSD 10 root, only FreeBSD 10 src.  IMO, if that's your setup, it's incorrect.

**Comment by kmoore134** [comment]
On 03/ 8/16 04:47 AM, jrmarino wrote:
>
> I'm re-reading this and IIUC your setup isn't what I would expect.
>
> For example, I'd expect something like
>
> |A: / A: /bin A: /boot A: /lib A: [more] A: /usr A: /usr/src B: /f10/
> B: /f10/bin B: /f10/lib B: [more] B: /f10/usr B: /f10/usr/src |
>
> so the "A" profile, which represents FreeBSD 11-current would have
> system root of "/".
> The "B" profile, which presents FreeBSD 10.x-release would have a
> system root of "/f10"
>
> so having 11-0 sources in /usr/src is correct.
> Using "/" as the system root for FreeBSD 10 would be incorrect. If I'm
> understanding correctly, you don't actually have a FreeBSD 10 root,
> only FreeBSD 10 src. IMO, if that's your setup, it's incorrect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrmarino/synth/issues/27#issuecomment-193692078>.
>

I have a FreeBSD 10 root, and I'm paring it with 10 src, by manually
splatting 10 src into /usr/src.

What I want to do is find a way to use an alt src location. If that is
/f10/usr/src, I'm cool with it. That was the first thing I tried, but I
noticed that the builders all nullfs mounted /usr/src on top of that though.

-- 
Kris Moore
PC-BSD Software / iXsystems
Enterprise Storage & Servers Driven By Open Source

**Comment by jrmarino** [comment]
I'm thinking I don't understand because what I think you are saying doesn't make sense to me.

I'm hearing this is an FreeBSD-current system, with FreeBSD 10-release files (bin/*, sbin/*, include/*, etc) stored elsewhere (e.g. /F10) but the src for the FreeBSD 10 is not at /F10/usr/src, but at /usr/src.   I don't understand why it would be configured that way.

to avoid POLA, the src would always be at $SYSROOT + /usr/src.
That's what synth expects and I think pretty much everyone would also expect that.

hence - I suspect I'm not reading this correctly. :)

**Comment by kmoore134** [comment]
ok, let me try to explain this better :)

My host system is 11-CURRENT. I'm building packages for 10.2 using an alternative 10.2 base in /synth/world and a ports tree in /synth/ports:

[PCBSD]
Operating_system= FreeBSD
Directory_packages= /synth/pkg/pcbsd-10.2-edge-edge
Directory_repository= /synth/pkg/pcbsd-10.2-edge-edge/All
Directory_portsdir= /synth/ports
Directory_options= /synth/ports-db
Directory_distfiles= /synth/distfiles
Directory_buildbase= /usr/obj/synth-live
Directory_logs= /synth/log/pcbsd-102-RELEASE
Directory_ccache= disabled
Directory_system= /synth/world
Number_of_builders= 16
Max_jobs_per_builder= 2
Tmpfs_workdir= true
Tmpfs_localbase= true
Display_with_ncurses= false
leverage_prebuilt= false

The issue is that there isn't a place to specify 10.2 freebsd system sources to be mounted into the builders. I.E /synth/10.2/src

When the builder chroot's get started, they are nullfs mounting /usr/src into the chroot's /usr/src. On the system /usr/src is where my 11-CURRENT sources are normally kept. 

What I need is a 'Directory_system_src=/synth/src' in the .ini file which in turn gets nullfs mounted into chroot as /usr/src. (For building ports that need system source, like kmods, etc)

Is this helping?

FWIW, I did try adding system sources to /F10/usr/src, but in the builder chroot I noticed it was still nullfs mounting my systems /usr/src into the chroot builders. (With the 11-CURRENT source) Maybe this was old, since I tested many versions ago. If you've already fixed it to not nullfs mount /usr/src anymore it may not be an issue.

**Comment by jrmarino** [comment]
i always understood the request

I assume "/synth/world" is not limited on disk space.
what's the problem in checking out a 10.2 source at /synth/world/usr/src using subversion?
That's what was envisioned (when /usr/src is actually needed).

Unless you are saying synth is using the wrong mount point??
it should be using /synth/world/usr/src -- are you saying it's using /usr/src?  If that's the case, that's a bug.  Maybe I should check the code....

**Comment by kmoore134** [comment]
On 03/ 8/16 05:31 PM, jrmarino wrote:
>
> i always understood the request
>
> I assume "/synth/world" is not limited on disk space.
> what's the problem in checking out a 10.2 source at
> /synth/world/usr/src using subversion?
> That's what was envisioned (when /usr/src is actually needed).
>
> Unless you are saying synth is using the wrong mount point??
> it should be using /synth/world/usr/src -- are you saying it's using
> /usr/src? If that's the case, that's a bug. Maybe I should check the
> code....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrmarino/synth/issues/27#issuecomment-193999090>.
>

I guess I'm saying its a bug then. When my builders spun up I saw that
/usr/src was nullfs mounted into <chroot>/usr/src, not /F10/usr/src.


-- 
Kris Moore
PC-BSD Software / iXsystems
Enterprise Storage & Servers Driven By Open Source

**Comment by jrmarino** [comment]
confirmed, there are a couple of other mount points, e.g. lib32.
They aren't based on system root, but they should be.

**Comment by bsdforge** [comment]
Can I add a +1 to this request?
I'd like to dedicate the box I currently use synth on to build repos for other FreeBSD versions.
I too am building on a box running -CURRENT.
Now, if I could just figure out how to get synth to cobble packages for other $ARCH's  (i386)....

--Chris

**Comment by jrmarino** [comment]
The request seems to be bogus.  It was a work-around for a bug.  The way forward is the fix the bug, not workaround it.

Using system to build for other FreeBSD version is not an "enhancement"; it does that now.  There are just a couple of mount points that have to fixed, that's all.

**Comment by jrmarino** [comment]
okay, so apparently only one directory was hardcoded, /usr/src.  This was a mistake and it's been changed to be relative to the system root as originally intended.

I'm assuming that resolves the perceived need for a separate /usr/src configuration item?

**Comment by bsdforge** [comment]
Sure it was bogus. But is was a missing "feature", wasn't it? ;)
I'll take it for a spin, and let you know how it worked out.

Thanks, John!

--Chris

**Comment by kmoore134** [comment]
Yea, if it uses the src relative to the world dir then we should be good. I'll mark this as closed :+1:

**Comment by jrmarino** [comment]
This is where the disconnect was.
I was thinking $sysroot + "/usr/src" was the mount point for each builder's /usr/src and that you were asking for configurable location, and I didn't see I shouldn't say "just keep it in $sysroot.

using "/usr/src" for all profiles was a bug all along (I don't think I ever intended that) but nobody flagged it as a bug into late into this github issue.

**Comment by jrmarino** [comment]
fyi, i pushed version 1.22 to ports.
v1.22 contains the commit that fixes this.
