### ISSUE TITLE
synth configure fails

### ISSUE THREAD

**Issue by mneumann** [jrmarino/synth#3]
Version 0.95 as described on mailing list (DragonFly 4.5)

```
# synth configure
Configuration failed to load.
```

**Comment by mneumann** [comment]
Works when I compile it myself. I think it's an issue with ncurses. When I do ```pkg ins ncurses``` for example ```tig``` does not work anymore. It fails with a message "wrong ncurses version 5_7".

**Comment by jrmarino** [comment]
hmm, "fails to load" comes after ncurses is dynamically loaded but before it's used.  I would think there's another cause.   Did you have /usr/dports in place?  is PORTSDIR set in environment?

**Comment by jrmarino** [comment]
oh, you need to rebuild ncurses from source.  I mean, if it's older than 1 hour!

**Comment by jrmarino** [comment]
(but that will require you to rebuild synth from source again.  You might as well use the latest synth by altering the hash in the makefile and regenerating distfile with "make makesum")

**Comment by mneumann** [comment]
It's from last night :). Building from source works. Thanks!
