### ISSUE TITLE
feature request: show relationships

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#30]
I think it would be nice if synth showed some more detailed information with the `status` command (or another command like `details`).
`pkg` doesn't offer a quick overview on which packages were installed, which are just dependencies and so on.
postmaster offers something more detailed with the `-L` flag.

It would be nice to show in the status messages which ports would be rebuilt because they have changed dependencies and which are just dependencies or leaf-dependencies.
Showing a similar list with the status of the already built / installed packages, grouped in primes, dependencies, leaf-dependencies would be a nice feature as well.

**Comment by jrmarino** [comment]
> pkg doesn't offer a quick overview on which packages were installed, which are just dependencies and so on.
Sure it does.  off the top of my head: "pkg prime-list".  There are lots of aliases.  Look at what they do.

**Comment by jrmarino** [comment]
By the way, you can create your own queries and define your own aliases if none of the pre-defined ones are good enough (which is doubtful)

**Comment by jrmarino** [comment]
> It would be nice to show in the status messages which ports would be rebuilt because they have changed dependencies and which are just dependencies or leaf-dependencies.

How is this information anything more that "gee whiz" ?  I didn't matter.  A failure can cascade to hundreds or thousands of ports.  It's just a fact.  You can't do anything with this information.

**Comment by jrmarino** [comment]
> Showing a similar list with the status of the already built / installed packages, grouped in primes, dependencies, leaf-dependencies would be a nice feature as well.

All of that is A) available via pkg and B) doesn't help synth do it's primary function.

In the end, synth is just building a repository to specification (either determined manually via list or automatically via what's already installed on the host).  It doesn't question the specification.

**Comment by bax-** [comment]
It would be a nice additions to status to show more details about the relationship of the ports.
But I wasn't completely aware of all the pkg aliases, thank you for pointing me there!
