### ISSUE TITLE
tty echo+control OFF

### ISSUE THREAD

**Issue by kmoore134** [jrmarino/synth#32]
Minor issue, but we are getting a bunch of these tty echo+control OFF messages in the jenkins log, which started after upgrading to 1.01:

.....
Recovered 111.00 megabytes
Notice: tty echo+control ON command failed
Old work directories detected; attempting to remove them automatically ...
Directory removal successful!
Notice: tty echo+control OFF command failed

Scanning entire ports tree.

.....

**Comment by jrmarino** [comment]
i'm really starting to despise tty.
I'm wondering if that jenkins environment has a tty active.  I can wrap the whole thing in a "isatty" check and if not, just skip the whole thing.

**Comment by jrmarino** [comment]
i'll make the change and update it, you can check by adding a hash.

**Comment by jrmarino** [comment]
try hash e1b3506
If it solves your problem, I'll push it as 1.02

**Comment by kmoore134** [comment]
Confirmed, it fixes the issue via Jenkins builds here.
