### ISSUE TITLE
ldconfig: mkstemp(/var/run/ld-elf.so.hints.eDT10W): No such file or directory

### ISSUE THREAD

**Issue by hvoers** [jrmarino/synth#33]
What does this mean?

# synth status
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
ldconfig: mkstemp(/var/run/ld-elf.so.hints.eDT10W): No such file or directory

raised REPLICANT.SCENARIO_UNEXPECTED : /usr/sbin/chroot /usr/obj/synth-live/SL09 /sbin/ldconfig -m /lib /usr/lib => failed with code 1

**Comment by jrmarino** [comment]
it means the command "/usr/sbin/chroot /usr/obj/synth-live/SL09 /sbin/ldconfig -m /lib /usr/lib" failed.
Like causes is only "/var" exists and "/var/run" does not exist.

I don't know why ldconfig would try to create a temp file there.
Did you add a custom make.conf or environment file?

**Comment by jrmarino** [comment]
according to ldconfig man page, that's the standard location
/var/run/ld-elf.so.hints

**Comment by jrmarino** [comment]
i double checked the code and /var/run is supposed to be created by mtree (BSD.var.dist) so the directory should exist.

**Comment by jrmarino** [comment]
if /usr/obj/synth-live/SL09 is still mounted, try running the command manually and checking if /var/run exists.

**Comment by hvoers** [comment]
root@mbox:/root # ls -al /var/run/*hints*
-r--r--r--  1 root  wheel  129 Feb 18 20:14 /var/run/ld-elf.so.hints
-r--r--r--  1 root  wheel   67 Feb 10 05:40 /var/run/ld.so.hints
root@mbox:/root # synth status
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
ldconfig: mkstemp(/var/run/ld-elf.so.hints.FT3kGe): No such file or directory

raised REPLICANT.SCENARIO_UNEXPECTED : /usr/sbin/chroot /usr/obj/synth-live/SL09 /sbin/ldconfig -m /lib /usr/lib => failed with code 1
root@mbox:/root # /usr/sbin/chroot /usr/obj/synth-live/SL09 /sbin/ldconfig -m /lib /usr/lib
ldconfig: mkstemp(/var/run/ld-elf.so.hints.xb0vET): No such file or directory
root@mbox:/root # ls -al /var/run/*hints*
-r--r--r--  1 root  wheel  129 Feb 18 20:14 /var/run/ld-elf.so.hints
-r--r--r--  1 root  wheel   67 Feb 10 05:40 /var/run/ld.so.hints
root@mbox:/root # ls -al /usr/obj/synth-live/
total 24
drwxr-xr-x   6 root  wheel  512 Feb 18 23:55 .
drwxr-xr-x   3 root  wheel  512 Feb 18 16:22 ..
drwxr-xr-x   2 root  wheel  512 Feb 18 23:55 Base
drwxr-xr-x  21 root  wheel  400 Feb 18 23:55 SL09
drwxr-xr-x   2 root  wheel  512 Feb 18 23:55 SL09_localbase
drwxr-xr-x   2 root  wheel  512 Feb 18 23:55 SL09_work

The /var/run/ld-elf.so.hints is of today.
I removed the old one and created a new one with ldconfig.
That did not help.

**Comment by jrmarino** [comment]
you look in SL09 for var/run, not "/" 
You're supposed to look in the builder.

What's inside SL09?
e.g. find /usr/obj/synth-live/SL09 -type d

**Comment by hvoers** [comment]
"find /usr/obj/synth-live/SL09 -type d" is very long.

root@mbox:/root # ls -al /usr/obj/synth-live/SL09
total 97
drwxr-xr-x   21 root  wheel    400 Feb 19 00:12 .
drwxr-xr-x    6 root  wheel    512 Feb 19 00:12 ..
drwxr-xr-x    2 root  wheel   1024 Nov 19  2014 bin
drwxr-xr-x    2 root  wheel      0 Feb 19 00:12 ccache
drwxr-xr-x    3 root  wheel     20 Feb 19 00:12 compat
drwxr-xr-x    2 root  wheel    512 Feb 19 00:12 construction
dr-xr-xr-x    7 root  wheel    512 Feb 19 00:12 dev
drwxr-xr-x   29 root  wheel  30720 Feb 18 14:25 distfiles
drwxr-xr-x    5 root  wheel    240 Feb 19 00:12 etc
drwxr-xr-x    2 root  wheel      0 Feb 19 00:12 home
drwxr-xr-x    3 root  wheel   1536 Jan 27 12:28 lib
drwxr-xr-x    3 root  wheel    512 Nov 19  2014 libexec
drwxr-xr-x  271 root  wheel  10240 Feb 18 14:23 options
drwxr-xr-x    2 root  wheel    512 Feb 18 15:53 packages
drwxr-xr-x    2 root  wheel      0 Feb 19 00:12 proc
drwxr-xr-x    2 root  wheel      0 Feb 19 00:12 root
drwxr-xr-x    2 root  wheel   2560 Jan 27 12:28 sbin
lrwxr-xr-x    1 root  wheel     11 Feb 19 00:12 sys -> usr/src/sys
drwxr-xr-x    2 root  wheel      0 Feb 19 00:12 tmp
drwxr-xr-x   12 root  wheel    200 Feb 19 00:12 usr
drwxr-xr-x    2 root  wheel      0 Feb 19 00:12 var
drwxr-xr-x   70 root  wheel   1536 Feb 18 17:55 xports

root@mbox:/root # ls -al /usr/obj/synth-live/SL09/var/
total 4
drwxr-xr-x   2 root  wheel    0 Feb 19 00:12 .
drwxr-xr-x  21 root  wheel  400 Feb 19 00:12 ..

So: no /usr/obj/synth-live/SL09/var/run

**Comment by jrmarino** [comment]
it means the mtree command failed. I don't know why.  Is your /etc/mtree normal?  do you have /etc/mtree/BSD.var.dist ?   Is there anything strange about your base?

**Comment by hvoers** [comment]
I have done a freebsd-update fetch and install today, just to be sure.
(running 9.3-RELEASE-p36) All ports are up to date.
/etc/mtree/BSD.var.dist has a "run".

root@mbox:/root # ls -al /etc/mtree/
total 64
drwxr-xr-x   2 root  wheel    512 Dec  6 07:53 .
drwxr-xr-x  22 root  wheel   2560 Feb 15 03:07 ..
-r--r--r--   1 root  wheel    685 Nov 19  2014 BIND.chroot.dist
-r--r--r--   1 root  wheel   5124 Nov 19  2014 BSD.include.dist
-r--r--r--   1 root  wheel   1348 Nov 19  2014 BSD.root.dist
-r--r--r--   1 root  wheel    400 Nov 19  2014 BSD.sendmail.dist
-r--r--r--   1 root  wheel  28892 Dec  6 07:53 BSD.usr.dist
-r--r--r--   1 root  wheel   1869 Nov 19  2014 BSD.var.dist

**Comment by jrmarino** [comment]
from what you have posted, 
**/usr/sbin/mtree -p /usr/obj/synth-live/SL09/var -f /etc/mtree/BSD.var.dist -deqU**
command fails, but I couldn't tell you why.  nobody has reported something like it before

**Comment by hvoers** [comment]
root@mbox:/root # /usr/sbin/mtree -p /usr/obj/synth-live/SL09/var -f /etc/mtree/BSD.var.dist -deqU
mtree: line 21: unknown user auditdistd

Aha. I will check this tomorrow.

**Comment by hvoers** [comment]
User auditdistd is in passwd but was maybe not in master.passwd
Just looking at it with "vipw" solved the problem.
synth is now building all packages.

For the wishlist: Catch mtree errors and show them.

Thank you very much.

**Comment by jrmarino** [comment]
it looks like it used to but the chance with piped commands might have changed that.

**Comment by jrmarino** [comment]
The next release will handle command errors correctly.
It should not have done what it did, you should have gotten the mtree error, not the later resulting error.
