### ISSUE TITLE
Feature Request: Bump priority

### ISSUE THREAD

**Issue by kmoore134** [jrmarino/synth#35]
Not sure if this is ingrained somewhere, but it would be nice to be able to bump the priority of some specific ports when doing 'everything', I.E. editors/libreoffice and others. Maybe a setting in synth.ini?

**Comment by jrmarino** [comment]
how something like this might work is to look for file called:
/usr/local/etc/synth/[profile]-priority.list
It would contain one port origin per line.
The first line would be the highest priority, the second line is the 2nd highest, etc.

What's not clear is what is really gained by this, especially on "synth everything"
