### ISSUE TITLE
Feature Request: batch pre-fetch of distfiles for a list of given port origins

### ISSUE THREAD

**Issue by mpeterma** [jrmarino/synth#36]
Would it be possible to implement a feature in synth to do a batch download of all distfiles for a given list of port origins / file of list with port origins?

Something like

    % synth download-distfiles <list of port origins | filename>

would be a great thing to pre-fetch all distfiles when you are online, and still beeing able to continue the build when disconnected.

Maybe, a corresponding function can be enabled for

    % synth everything

too?

**Comment by jrmarino** [comment]
it's technically possible.  It's even possible to set a variable in the environment that limits the build to fetching only but I don't think that would be great.

One major issue is the number of builders.  If you have 8 active builders, you wouldn't want to download 8 distfiles simultaneously I don't think.  You'd probably want to limit it to 2 builders for fetching purposes.

I don't know if an equivalent "everything" command makes sense though.  There are very few legitimate users for "everything" and none of them would ever build offline.

**Comment by jrmarino** [comment]
mpetersma, 
This is actually more technically challenging than it appears at first glance.  The main reason is that the "fetch" target may require ports to be built and installed (e.g. any rubygem port requires ruby to be built first).  There are actually a quite a few ports like this.

I'm wondering if it would be acceptable to take the results of "synth status" command (/tmp/synth_status_results.txt) and pipe that into a script at /usr/ports/Tools/scripts/ that would prefetch distfiles (but install ports as needed to do it).

What do you think about accomplishing this request with a generic script located in ports?

**Comment by jrmarino** [comment]
fyi, even that won't be foolproof.
The downloads are based on the /etc/make.conf and selected port options, so there's a decent chance that such an approach would not prefetch the entire set of distfiles necessary.

**Comment by jrmarino** [comment]
If synth were to be able to do this, it would capture the all FETCH_DEPENDS and prebuild those.  Then it could, in theory, run up to the "checksum" target of each port on the list, marking each as "successful" if it gets a good checksum.

That might work, but you can see it's not exactly trivial.

**Comment by jrmarino** [comment]
mpetersma,
Did you see my comment about a ports script to prefetch distfiles instead of synth?  Would that be okay?

**Comment by jrmarino** [comment]
no feedback after several attempts, so let's just quietly close the PR request.
