### ISSUE TITLE
synth install is installing all ports in the repository on the local machine

### ISSUE THREAD

**Issue by dmoutal** [jrmarino/synth#42]
Running `sudo synth install sysutils/tree` on FreeBSD10.2 is installing every package that exists in the local repository and parking all of them as non-automatic installs.

When building the tree with synth and installing it with `sudo pkg install tree` only tree gets installed.

I also tested the `synth install` behaviour with node4 and got the same result (every package in the repository is installed and marked as a non-automatic install).

Any Idea why this is happening?

Thanks

**Comment by jrmarino** [comment]
er, no, this is the first time I've heard "synth install <port>" installs more than just the specied port + dependencies.

Is it possible that "every package in the local repository" is somehow a dependency of sysutils/tree?

**Comment by jrmarino** [comment]
fyi, "sudo pkg install tree" might be using the freeBSD repo.
try "sudo pkg install -r Synth tree" instead

**Comment by dmoutal** [comment]
I should have mentioned that I have disabled the FreeBSD repo, so pkg install was installing from the synth repo. But I will test `sudo pkg install -r Synth tree` later today when I get some time.

Overall I installed almost 200 packages. I know that tree doesn't have that many dependences. And I know that tree doesn't need the multimedia/plexmediaserver package (as an example)

Also since all the packages were set to non-automatic seems to indicate that Synth was installing them as if I told it to install it and not as dependencies.

Thanks

**Comment by jrmarino** [comment]
i haven't experienced this myself and this is the first I've heard of it.  
maybe it's something in pkg.conf ?  do you have that and if so, how did you generate it?  and if so, how does it compare to pkg.conf.sample?

**Comment by dmoutal** [comment]
My pkg.conf was auto generated by the pkg bootstrap but I did do a diff with pkg.conf.sample and they are identical.

I did disable the FreeBSD package repository, could that cause the issue?

**Comment by jrmarino** [comment]
i don't think so.
i don't see how this is happening.  Even if the <one port> was omitted, the "pkg install" command shouldn't install everything.  That's not what it does.

**Comment by dmoutal** [comment]
On my mobile so please excuse the curtness.

When running pkg install tree, only tree and the dependencies get installed. It is only when running synth install tree that all packages in the repo get installed.

I think when running synth install tree, synth is telling pkg to install all packages.

**Comment by jrmarino** [comment]
in order to do that, it would have to gather all the origins from the packages themselves and pass them as a long string to pkg(8).  That would be deliberate and of course synth isn't doing that.

More realistic would be "pkg install" with no argument, but then package would return an error, right?

by the way, what is output of "pkg config conservative_upgrade" ?

**Comment by dmoutal** [comment]
`pkg config conservative_upgrade` returns `yes`

BTW is there a way to get `synth install tree` to do a dry run and print out the list of packages that will be installed without them being installed? Right now it is a pain to remove all the extra packages that get installed and reset all packages to automatic install.

Thanks again for all your help

**Comment by jrmarino** [comment]
the "status" commands are dry-runs (it's even described that way on the help screen and man page)

**Comment by jrmarino** [comment]
FYI, i turned conservative updates off.
Others have fully uninstalled and reinstalled from Synth repository to "functionally" disable conservative upgrades.  I'm not fully sure of the implications, but it appears it's better off.

**Comment by dmoutal** [comment]
I did a pkg upgrade -f   a while back to get everything reinstalled from the Synth repo

I have set conservatives updates to off, but I still have the same issue

I did try the `synth status` command, it correctly tells me that zero packages would be built (the tree package has already been built), but it doesn't tell me what would be installed if a used the `synth install` command.

Any other ideas?

**Comment by jrmarino** [comment]
i guess the only way to know that is run pkg command directly and answer "N" when it asks if you want to do it.

**Comment by dmoutal** [comment]
`pkg install tree` behaves as expected and only installs tree and (the few dependencies)

Is there a way to see what synth is passing to the pkg command when you run `synth install tree`. I suspect something is causing synth to pass all packages in the repo to pkg.

Thanks for all your help (and quick responses)

**Comment by jrmarino** [comment]
there's no way to see the command without modifying the code.
It's basically impossible to "pass all packages" to repo.  It doesn't know them.  You'd have to write code to do that, so there's no way it could be happening accidently.

**Comment by jrmarino** [comment]
i mean pass to pkg.

**Comment by jrmarino** [comment]
hmmm, I may have hit this as well during my testing of signed repos.  Looking into it.

**Comment by jrmarino** [comment]
well, shit, sure enough it sent the entire portlist to pkg (it didn't scan the packages, it's just listing the whole tree).

**Comment by jrmarino** [comment]
at first glance, it appears this bug was introduced with version 1.1 with the new repository algorithm.

**Comment by jrmarino** [comment]
I pushed version 1.20 to ports, so upgrade as soon as you can.  (I hadn't really finished testing my key signing features but this was such a huge regression I had to push it)

**Comment by dmoutal** [comment]
Thanks for fixing this.

I can confirm that `synth install` now works as expected
