### ISSUE TITLE
Errors with 1.22

### ISSUE THREAD

**Issue by kmoore134** [jrmarino/synth#43]
12:11:21 => [04] 00:01:02 Success accessibility/gnome-mag

12:11:32 => [02] 00:01:37 Success hebrew/kde4-l10n

piped_mute_command failure:
 => rm: /usr/obj/synth-live/SL04/construction: Device busy
rm: /usr/obj/synth-live/SL04/usr/local: Device busy
rm: /usr/obj/synth-live/SL04/usr: Directory not empty
rm: /usr/obj/synth-live/SL04: Device busy

12:11:44 => [04] 00:00:11 Success dns/p5-IO-Async-Resolver-DNS
12:11:44 => [06] 00:01:31 Success accessibility/accerciser

12:11:59 => [02] 00:00:12 Success dns/p5-Mozilla-PublicSuffix

12:12:00 => [08] 00:01:11 Success accessibility/kdeaccessibility4

piped_mute_command failure:
 => rm: /usr/obj/synth-live/SL14/construction: Device busy
rm: /usr/obj/synth-live/SL14/usr/local: Device busy
rm: /usr/obj/synth-live/SL14/usr: Directory not empty
rm: /usr/obj/synth-live/SL14: Device busy

Getting a TON of these errors on 1.22 (didnt happen in 1.02)

What other log output do you need?

12:12:04 => [14] 00:01:04 Success accessibility/mousetweaks

piped_mute_command failure:
 => rm: /usr/obj/synth-live/SL04/construction: Device busy
rm: /usr/obj/synth-live/SL04/usr/local: Device busy
rm: /usr/obj/synth-live/SL04/usr: Directory not empty
rm: /usr/obj/synth-live/SL04: Device busy

12:12:10 => [04] 00:00:14 Success dns/p5-Net-DNS-ZoneFile-Fast

12:12:10 => [06] 00:00:15 Success dns/p5-POE-Component-Client-DNS-Recursive

12:12:27 => [02] 00:00:13 Success dns/p5-POE-Component-Client-DNSBL
12:12:27 => [08] 00:00:12 Success dns/p5-POE-Filter-DNS-TCP

piped_mute_command failure:
 => rm: /usr/obj/synth-live/SL14/construction: Device busy
rm: /usr/obj/synth-live/SL14/usr/local: Device busy
rm: /usr/obj/synth-live/SL14/usr: Directory not empty
rm: /usr/obj/synth-live/SL14: Device busy

**Comment by jrmarino** [comment]
i doubt it's repeatable.
Likely a previous port failed and didn't clean up (couldn't dismount).  There are many reasons why a dismounting can fail. then mounts on top of mounts .

this is jail vs. chroot issue I spoke about on the videocast.  The jail can kill all the processes but sometimes chrooted sandboxes can't (although I'm still working on a better watchdog).

I think it's just a coincidence.  It could have happened on 1.02 as well.

**Comment by kmoore134** [comment]
On 03/ 9/16 08:31 PM, jrmarino wrote:
>
> i doubt it's repeatable.
> Likely a previous port failed and didn't clean up (couldn't dismount).
> There are many reasons why a dismounting can fail. then mounts on top
> of mounts .
>
> this is jail vs. chroot issue I spoke about on the videocast. The jail
> can kill all the processes but sometimes chrooted sandboxes can't
> (although I'm still working on a better watchdog).
>
> I think it's just a coincidence. It could have happened on 1.02 as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrmarino/synth/issues/43#issuecomment-194605589>.
>

I dunno, I ran 1.02 across three builders for the past month, never had
this issue. Last night I upgraded them to 1.22 and now all three are
having the exact same issue. (Building the complete ports tree also BTW)

-- 
Kris Moore
PC-BSD Software / iXsystems
Enterprise Storage & Servers Driven By Open Source

**Comment by jrmarino** [comment]
the builders didn't change at all.
What *did* change, what is constantly changing, is the ports tree.
It's probable that there's a port that gone bad (maybe failing due to changing dependencies) and the issue is reproducible (e.g. the bad port is locking up, etc)

If you have the logs of all three, it might be obvious which port(s) aren't finishing cleanly.

**Comment by kmoore134** [comment]
On 03/ 9/16 08:44 PM, jrmarino wrote:
>
> the builders didn't change at all.
> What /did/ change, what is constantly changing, is the ports tree.
> It's probable that there's a port that gone bad (maybe failing due to
> changing dependencies) and the issue is reproducible (e.g. the bad
> port is locking up, etc)
>
> If you have the logs of all three, it might be obvious which port(s)
> aren't finishing cleanly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrmarino/synth/issues/43#issuecomment-194612772>.
>

Gotcha, might just be bad timing then. I'll dig into it, see if I can
find a problematic port/package.


-- 
Kris Moore
PC-BSD Software / iXsystems
Enterprise Storage & Servers Driven By Open Source

**Comment by jrmarino** [comment]
did you discover anything?  e.g. a port that may have failed on all three?

**Comment by jrmarino** [comment]
Hi Kris, just following up.  Is there any new information here?

**Comment by kmoore134** [comment]
Nope, nothing new to report! I'm going to say it can be closed, unless somebody else can replicate it.
