### ISSUE TITLE
Illegal instruction followed by core dump

### ISSUE THREAD

**Issue by chaplina** [jrmarino/synth#47]
Last time I ran synth on Sunday it upgraded my ports OK, including synth to 1.34, and pkg to 1.7.2.

Since then I have run freebsd-update from 10.2-RELEASE-p14 to 10.2-RELEASE-p17, and today I ran a portsnap fetch update.

Any synth command that results in comparing ports to installed ports results in Illegal Instruction and a core dump.

I can provide the core file if needed.

**Comment by jrmarino** [comment]
This is the first report of it's kind.
Maybe you can try deinstalling synth and installing it again from FreeBSD official packages.  If that doesn't work, you can try building it from source (preinstall gcc6-aux from packages first though).

**Comment by chaplina** [comment]
Unfortunately, after taking the following steps, the problem persists (fyi, cmd I'm running is 
'synth status'):

- make -C /usr/ports/devel/gcc6-aux deinstall
- make -C /usr/ports/devel/gcc6-aux reinstall
- make -C /usr/ports/ports-mgmt/synth deinstall
- make -C /usr/ports/ports-mgmt/synth reinstall
- clean out /var/synth/live_packages
- make -C /usr/ports/devel/gcc6-aux deinstall
- make -C /usr/ports/ports-mgmt/synth deinstall
- pkg install synth (installs v1.33)

**Comment by jrmarino** [comment]
why "reinstall"?
It should be "make clean ; make install" right?

why v1.33?  Are you on quarterly branch for official packages?

If so, that's the same synth you've been using all along, so it didn't change -- it doesn't seem to like your new base.

You might try gdb7 and running a backtrace on the core dump but I don't have much hope since surely there are no debug symbols there.  I would guess doesn't even build with them.

**Comment by jrmarino** [comment]
Does the problem still exist?  Even with synth v1.40?

**Comment by chaplina** [comment]
Unfortunately, yes.

I can sometimes successfully run 'synth status' with a specific port.

I've run it with dtruss but I am no expert and it is not clear what is causing it to core.

**Comment by jrmarino** [comment]
This _might_ help diagnose it.
Do a "make clean; make patch" command from ports-mgmt/synth
find the default.gpr file in the working directory
change line 15 from
```
for Default_Switches ("ada") use ("-g", "-O2", "-gnat12", "-gnatyaAbBcdefhiklnOprsSxt");
``` 
to
```
for Default_Switches ("ada") use ("-g", "-O2", "-gnat12", '-fstack-check", "-gnatyaAbBcdefhiklnOprsSxt");
```
(add "-fstack-check" switch to list)

then "make install".

the biggest build dependency is lang/gcc6-aux so you might want to pre-install that from official packages

**Comment by chaplina** [comment]
So something with disk...

I do have compression enabled on ZFS.

root@ic-18338:~ # zfs list
NAME                 USED  AVAIL  REFER  MOUNTPOINT
bootpool            1.63G   300M   551M  /bootpool
zroot                111G   304G    96K  /zroot
zroot/ROOT          22.4G   304G    96K  none
zroot/ROOT/default  22.4G   304G  6.59G  /
zroot/tmp            142M   304G  25.5M  /tmp
zroot/usr           88.0G   304G    96K  /usr
zroot/usr/home      68.1G   304G  26.5G  /usr/home
zroot/usr/ports     17.4G   304G  1.07G  /usr/ports
zroot/usr/src       2.47G   304G  1.10G  /usr/src
zroot/var            204M   304G    96K  /var
zroot/var/audit       96K   304G    96K  /var/audit
zroot/var/crash       96K   304G    96K  /var/crash
zroot/var/log        193M   304G  56.8M  /var/log
zroot/var/mail      5.30M   304G   456K  /var/mail
zroot/var/tmp       4.83M   304G   240K  /var/tmp


root@ic-18338:~ # zpool status
   pool: bootpool
  state: ONLINE
   scan: scrub repaired 0 in 0h0m with 0 errors on Thu Jun 16 03:59:05 2016
config:

	NAME        STATE     READ WRITE CKSUM
	bootpool    ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    ada0p2  ONLINE       0     0     0
	    ada1p2  ONLINE       0     0     0

errors: No known data errors

   pool: zroot
  state: ONLINE
   scan: scrub repaired 0 in 0h28m with 0 errors on Thu Jun 16 04:27:53 2016
config:

	NAME            STATE     READ WRITE CKSUM
	zroot           ONLINE       0     0     0
	  mirror-0      ONLINE       0     0     0
	    ada0p4.eli  ONLINE       0     0     0
	    ada1p4.eli  ONLINE       0     0     0

errors: No known data errors


root@ic-18338:~ # synth status
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.

raised STORAGE_ERROR : s-intman.adb:139 explicit raise
root@ic-18338:~ # df -h
Filesystem                                                                 Size    Used   Avail 
Capacity  Mounted on
zroot/ROOT/default                                                         310G    6.6G    304G 
2%    /
devfs                                                                      1.0K    1.0K      0B 
100%    /dev
bootpool                                                                   851M    551M    300M 
65%    /bootpool
zroot/tmp                                                                  304G     26M    304G 
0%    /tmp
zroot/usr/home                                                             330G     26G    304G 
8%    /usr/home
zroot/usr/ports                                                            305G    1.1G    304G 
0%    /usr/ports
zroot/usr/src                                                              305G    1.1G    304G 
0%    /usr/src
zroot/var/audit                                                            304G     96K    304G 
0%    /var/audit
zroot/var/crash                                                            304G     96K    304G 
0%    /var/crash
zroot/var/log                                                              304G     57M    304G 
0%    /var/log
zroot/var/mail                                                             304G    456K    304G 
0%    /var/mail
zroot/var/tmp                                                              304G    240K    304G 
0%    /var/tmp
zroot                                                                      304G     96K    304G 
0%    /zroot
linprocfs                                                                  4.0K    4.0K      0B 
100%    /compat/linux/proc
filer.canisius.edu:/vol/compcent/chaplina                                  1.3T    953G    378G 
72%    /nfs/filer0-compcent-chaplina
filer.canisius.edu:/vol/compcent/deptlib                                   1.3T    953G    378G 
72%    /nfs/filer0-compcent-deptlib
hogan.canisius.edu:/mnt/promise/promise3/Images                            8.3T    3.4T    4.9T 
41%    /nfs/hogan-images
ss-22735.canisius.edu:/export/ozfssa01_vmdk_32k_nodedupe_limitsnapshots    3.2T    240G    3.0T 
7%    /nfs/ozfssa01_vmdk_32k_nodedupe_limitsnaps
ss-22735.canisius.edu:/export/ozfssa01_vmdk00_32k_nodedupe                 3.4T    380G    3.0T 
11%    /nfs/ozfssa01_vmdk00_32k_nodedupe
ss-20990.canisius.edu:/export/ozfssa00_vmdk_4k_nodedupe                    5.0T    1.8T    3.1T 
37%    /nfs/ozfssa00_vmdk_4k_nodedupe
ss-v1000.canisius.edu:/Q/shares/NFS_Andy                                   1.0T     89G    935G 
9%    /nfs/ss-v1000-Andy
filer.canisius.edu:/vol/web                                                100G     48G     52G 
48%    /nfs/filer0-web
tmpfs                                                                       65G    220K     65G 
0%    /usr/obj/synth-live/SL09
/bin                                                                       310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/bin
/sbin                                                                      310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/sbin
/lib                                                                       310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/lib
/libexec                                                                   310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/libexec
/usr/bin                                                                   310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/usr/bin
/usr/include                                                               310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/usr/include
/usr/lib                                                                   310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/usr/lib
/usr/libdata                                                               310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/usr/libdata
/usr/libexec                                                               310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/usr/libexec
/usr/sbin                                                                  310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/usr/sbin
/usr/share                                                                 310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/usr/share
/usr/ports                                                                 305G    1.1G    304G 
0%    /usr/obj/synth-live/SL09/xports
/var/db/ports                                                              310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/options
/var/synth/live_packages                                                   310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/packages
/usr/ports/distfiles                                                       305G    1.1G    304G 
0%    /usr/obj/synth-live/SL09/distfiles
tmpfs                                                                       12G    4.0K     12G 
0%    /usr/obj/synth-live/SL09/construction
tmpfs                                                                       12G    4.9M     12G 
0%    /usr/obj/synth-live/SL09/usr/local
/usr/lib32                                                                 310G    6.6G    304G 
2%    /usr/obj/synth-live/SL09/usr/lib32
/bootpool/boot                                                             851M    551M    300M 
65%    /usr/obj/synth-live/SL09/boot
tmpfs                                                                      100M    4.0K    100M 
0%    /usr/obj/synth-live/SL09/boot/modules
/usr/src                                                                   305G    1.1G    304G 
0%    /usr/obj/synth-live/SL09/usr/src
devfs                                                                      1.0K    1.0K      0B 
100%    /usr/obj/synth-live/SL09/dev

**Comment by jrmarino** [comment]
how much memory does this machine have?
At least I have a vague idea of what's going on here.

**Comment by chaplina** [comment]
hw.physmem: 17137664000
hw.usermem: 9807261696
hw.realmem: 17180917760
hw.machine: amd64
hw.model: Intel(R) Xeon(R) CPU           E5410  @ 2.33GHz

RAM is ECC.

My PC (HP xw6600) is 8 years old but with some GPU and SSD upgrades it continues to chug along with 
no issues.

The SSDs are 500G Samsung 850 EVOs.

GPU is Nvidia NVS 510.

**Comment by jrmarino** [comment]
16G is more than enough.
I think what's going on here is something I've recently seen somewhere else.  Some structures have type rnages that cover 8 bit integers (for example) and this eats up stack.  The solution is to replace those types with much more constrained version, but I would be randomly shooting in the dark since I can't test any fix.

STORAGE_ERROR doesn't refer to disk if that's your assumption.  it refers to storing data structures during executtion.

Probably the only thing I can do here is look through the code and try to identify types that might cause this and replace those and give you a patch to see if it makes any difference.  I don't know how else to try to fix it.

**Comment by chaplina** [comment]
I'm willing to test as needed, although in some cases there will be delays due to work.

My system is stable and running the latest/greatest is not a need right now so...

**Comment by chaplina** [comment]
And a huge thanks for circling back on this and trying to establish a path to resolution!

**Comment by jrmarino** [comment]
So far the records are already constrained.
How many builders did you set?
You might want to paste the output of "synth configure".
You might try reducing the # of builders to see if that changes anything.

**Comment by chaplina** [comment]
It was at 4:4 for the longest time until the core dumps started.

I've tried different combinations, and even at 1:1 it is still core dumping.

Here's the config:

Synth configuration profile: LiveSystem
===============================================================================
    [A] Ports directory            /usr/ports
    [B] Packages directory         /var/synth/live_packages
    [C] Distfiles directory        /usr/ports/distfiles
    [D] Port options directory     /var/db/ports
    [E] Build logs directory       /var/log/synth
    [F] Build base directory       /usr/obj/synth-live
    [G] System root directory      /
    [H] Compiler cache directory   disabled
    [I] Num. concurrent builders   1
    [J] Max. jobs per builder      1
    [K] Use tmpfs for work area    true
    [L] Use tmpfs for /usr/local   true
    [M] Display using ncurses      true
    [N] Fetch prebuilt packages    false

**Comment by jrmarino** [comment]
well, i guess you can put it back to 4:4 because it's either going to work or it won't.

The problem is that would need to put in print statements to figure out more or less where the storage_error is coming from and right now only your machine can reproduce it.  So I would basically need root access to your machine quickly trace it down.  

Alternatively I could provide a patch with these print statements everywhere and then ask you to rebuilt synth and that could work.

**Comment by jrmarino** [comment]
by the way, how many packages are installed on this system?

**Comment by chaplina** [comment]
Root access would not be possible.

pkg info | wc -l = 939

**Comment by jrmarino** [comment]
i tried to reproduce it.   I only had about 400 packages installed, so I installed a bunch of crap I didn't need and now I'm at 982 packages, but still am not suffering the storage error.  I assume other users have over 900 packages and would have notified me alread if it were strictly affected by number of packages installed.

**Comment by shonjir** [comment]
I spent the day wrestling with this one.  Synth was working fine until I decided to switch from openssl (base) to libressl from ports.

In my case, this was the result of a circular build dependency which synth was unable to handle.  To be fair, it broke portmaster too.

Switching to security/libressl resulted in a build failure for ftp/curl due to an incompatible default build option.  I initially tried changing ftp/curl to require security/gnutls which was already on my system.

Unfortunately, this set up a circular dependency: ftp/curl depends on security/gnutls, which depends on security/trousers, which depends on emulators/tpm-emulator, which depends on devel/cmake, which depends on ftp/curl...

So in my case the combination of the following make.conf settings resulted in a circular dependency breaking synth.

```
DEFAULT_VERSIONS=ssl=libressl
ftp_curl_SET=GSSAPI_NONE GNUTLS
ftp_curl_UNSET=GSSAPI_BASE OPENSSL CA_BUNDLE TLS_SRP
```

**Comment by jrmarino** [comment]
Shonjir, your report seems unrelated to the topic of this issue (illegal instruction + core dump).
as an aside, all tools would broke under a circular dependency.

**Comment by shonjir** [comment]
I failed to mention that the symptoms from synth when the circular dependency was present matched the OPs report precisely - 'synth status' (actually, pretty much any synth comparison operation) faults with an illegal instruction error, followed by a synth core dump.

I suspect that the ports tree update reported by the OP may have resulted in such a circular dependency being created.  Without knowing the full set of installed ports and configured options it may be difficult to track down the specific port that is causing OPs issue.

My report was intended to help you narrow down the operation that may be resulting in the fault.  I think I can reproduce relatively easily if need be.

**Comment by jrmarino** [comment]
ah, ok, I follow now.  You're saying that if I follow your recipe, I can break it myself.

**Comment by jrmarino** [comment]
I've been working under the assumption there was nothing special about OP's tree or [profile]-make.conf.  Chaplina, if you use [profile]-make.conf, you should post it.
You might also try blowing ports tree away and recreating it.

**Comment by jrmarino** [comment]
Yes, I can reproduce this using shonjir's recipe.  With fstack-check on (perhaps I should turn this on by default),
```
raised STORAGE_ERROR : s-intman.adb:139 explicit raise
```

It's obviously caught in an infinite loop and running out of stack.  There's about a 2-second delay before this happens.

So it's clear that needs needs an circular dependency detector.  There's also a decent chance that this is the same issue.  At least the symptoms are identical.

**Comment by jrmarino** [comment]
Hi guys,
I have a fix that both of you can try.
When I run it against shonjir's test case, this is the output:

```
ironwolf# synth just-build ftp/curl

ftp/curl scan aborted because a circular dependency on ftp/curl was detected.
... backtrace devel/cmake
... backtrace emulators/tpm-emulator
... backtrace security/trousers
... backtrace security/gnutls
... backtrace ftp/curl
ironwolf#
```

Here's the patch against the port:
```
--- /usr/ports/ports-mgmt/synth/Makefile        2016-06-12 12:15:21.000000000 +0200
+++ ./Makefile  2016-06-20 15:33:00.000000000 +0200
@@ -18,6 +18,7 @@
 USES=          ada:6 ncurses:port
 USE_GITHUB=    yes
 GH_ACCOUNT=    jrmarino
+GH_TAGNAME=    5e2b4cd

 GPR=           ${LOCALBASE}/lib/gnat

diff -u /usr/ports/ports-mgmt/synth/distinfo ./distinfo
--- /usr/ports/ports-mgmt/synth/distinfo        2016-06-12 11:37:12.000000000 +0200
+++ ./distinfo  2016-06-20 15:33:09.000000000 +0200
@@ -1,3 +1,3 @@
-TIMESTAMP = 1465723186
-SHA256 (jrmarino-synth-v1.40_GH0.tar.gz) = bd7ab4b5d82d80508f68a8f525bc8351cee723aa9c3f3c2c0042d81a78605656
-SIZE (jrmarino-synth-v1.40_GH0.tar.gz) = 101245
+TIMESTAMP = 1466429587
+SHA256 (jrmarino-synth-v1.40-5e2b4cd_GH0.tar.gz) = 2676ba95ef513a438ea1a64a54b5ca9696aa9e273bd51d6fcec5f4f9578d8d0e
+SIZE (jrmarino-synth-v1.40-5e2b4cd_GH0.tar.gz) = 101530
```

I've done pretty much no testing so hopefully there are no regressions.
Please let me know how it works out.

**Comment by chaplina** [comment]
Awesome patch so far!

root@ic-18338:~ # synth status ftp/curl

ftp/curl scan aborted because a circular dependency on ftp/curl was detected.
... backtrace devel/cmake
... backtrace emulators/tpm-emulator
... backtrace security/trousers
... backtrace security/gnutls
... backtrace ftp/curl

root@ic-18338:~ # synth status www/chromium

www/chromium scan aborted because a circular dependency on devel/cmake was detected.
... backtrace emulators/tpm-emulator
... backtrace security/trousers
... backtrace security/gnutls
... backtrace ftp/curl
... backtrace devel/cmake
... backtrace devel/llvm37
... backtrace graphics/gbm
... backtrace graphics/libEGL
... backtrace graphics/cairo
... backtrace www/chromium

It also cleans up the tmpfs mount points (although running synth configure does the same in the 
unpatched version).

I vaguely remember a bug reported about curl and libressl vs openssl but am not sure if it was ever 
resolved.

**Comment by chaplina** [comment]
So I'm an idiot.

The config I had for ftp/curl used GNUTLS for some reason.

I redid the config for ftp/curl to use openssl and should be OK.

Once again, many thanks for taking the time to research and get this resolved!

**Comment by jrmarino** [comment]
chaplina, you never mentioned anything about libressl before now.  Did you switch to it and that's when synth started  core dumping?

**Comment by jrmarino** [comment]
> Once again, many thanks for taking the time to research and get this resolved!

Better yet, we got circular dependency detection out of this exercise.
