### ISSUE TITLE
pkg not found in FreeBSD 11

### ISSUE THREAD

**Issue by utrenkner** [jrmarino/synth#48]
I have a problem with several packages/ports when using synth: They require pkg to be at /usr/local/sbin/pkg. But because in 11 pkg has moved to /usr/sbin/pkg synth tries to solve the issue by (re)installing pkg. Of course, that does not help: There is still no pkg binary at /usr/local/sbin/pkg

What is the best solution for this problem? A symlink (but where does synth expect it)? Or can I configure this additional location of pkg somewhere?

**Comment by jrmarino** [comment]
This doesn't sound correct (and it's the first I heard of it).
the ports-mgmt/pkg port is what installs package, see the package list here:
https://svnweb.freebsd.org/ports/head/ports-mgmt/pkg/pkg-plist?revision=400580&view=co
You can confirm it's still installing at /usr/local/sbin/pkg.

Re-reading your post, I think you may misunderstand what synth is doing.
It's building a new "pkg" package for a jail.  It installs that "pkg" in these jails.  The host system is not affected at all.  Synth doesn't use the host "pkg" executable at all (which is why it has to build it).

are you sure FreeBSD 11 has a base pkg at /usr/sbin/pkg?  This goes against the original philosophy (pkg is kept out of base intentionally, I don't think people would agree to move it back)

**Comment by utrenkner** [comment]
Sorry, you are probably right: The binary under /usr/sbin/pkg which is found by `whereis pkg` is probably the tool which bootstraps the original installation of the pkg package.

I am using synth with `Fetch prebuilt packages` configured to "true". So synth tries to use existing packages first.

And for several packages I get similar errors in the logs, e.g. /var/log/synth/devel___gmake.log
```
...
========================< phase : pkg-depends     >========================
===>   gmake-4.2_1 depends on file: /usr/local/sbin/pkg - not found
===>   Installing existing package /packages/All/pkg-1.8.5_1.txz
Installing pkg-1.8.5_1...
Extracting pkg-1.8.5_1: .......... done
===>   gmake-4.2_1 depends on file: /usr/local/sbin/pkg - not found
*** Error code 1

Stop.
make: stopped in /xports/devel/gmake
==========================================================================
```
I have tried to build from source instead (`Fetch prebuilt packages` configured to "false"). But the result is exactly the same.

**Comment by utrenkner** [comment]
Just for completeness, I was trying to build this: `synth just-build net/samba44`

And /var/log/synth/02_failure_list.log shows
```
00:00:07 net/openldap24-client (skipped 2)
00:00:08 devel/p5-Parse-Yapp (skipped 1)
00:00:08 devel/gmake (skipped 10)
00:00:08 textproc/expat2 (skipped 0)
00:00:08 lang/python27 (skipped 21)
```
The problem is always that it cannot find /usr/local/sbin/pkg.

**Comment by jrmarino** [comment]
if you are using prefetch, your ports tree and package repos have to match.  In other words, both are quarterly or both are HEAD.  It's a common error to have pkg pull Quarterly packages yet have portsnap pull the HEAD ports tree.

You might try removing all "pkg-*" packages in the built package directory to force it to rebuild.  If you made the error above, you might want to blow away the entire directory and start over (after making sure packages and ports match)

**Comment by utrenkner** [comment]
Thank you for the help!

I was using the latest packages (not Quarterly) but apparently even they were just slightly out of sync with my ports tree. I have thus wiped the synth-directories and rebuild everything without pre-fetching. And this worked well.

Only /var/synth/live_packages/meta.txz was not re-created. Would you have an idea why this could be the case? Maybe a permission issue on the manually re-created directory (/var/synth is owned by root:wheel with permissions 755)? In my case this was not a problem as I only needed the package net/samba44 which I could install via `pkg add`.

**Comment by jrmarino** [comment]
did you try "synth rebuild-repository"?

**Comment by jrmarino** [comment]
FYI, starting with synth 1.40, "synth install <port>" will rebuild the repo without removiing any packages, even if those packages are obsolete.

**Comment by utrenkner** [comment]
> did you try "synth rebuild-repository"?

Thanks, that worked... I had assumed this would happen automatically with the building.

> FYI, starting with synth 1.40, "synth install " will rebuild the repo without removiing any packages, even if those packages are obsolete.

Excellent. So "just-build" is not anymore necessary.

> also I assume you are running synth as root. is that a good assumption?

Yes.

**Comment by jrmarino** [comment]
utrenkner, rebuilding a repository can take a long time, up to 20 minutes.  You only want to do it when you are finished building.  So imagine you have a number of ports you want to build manually, (say 10) and you want to do it in 5 batches.  You would build them all first, and finish with rebuilding the repository.

In other words, you wouldn't do 5 sets of "synth build <port1> <port2>" followed by "yes" to rebuild repository question.  You would do 5 sets of "synth just-build" followed by "synth rebuild-repository" or alternatively only say "yes" rebuild repo question on fifth and final build command.

just-build is actually probably the most used command, at least for me.

**Comment by jrmarino** [comment]
To clarify, the "synth build" and "synth force" commands ask you if you want to build the repository or not.  It's never automatic, but those command versions will do it if you say yes to a question.
