### ISSUE TITLE
How can I make synth a bit more verbose?

### ISSUE THREAD

**Issue by kworr** [jrmarino/synth#5]
Right now I'm trying to rebuild synth but it just silently exits without saying what's wrong, mounting partitions or updating log files:

    # time synth force ports-mgmt/portmaster
    0.031u 0.023s 0:00.06 83.3%     670+3924k 0+0io 0pf+0w

How can I debug it or make it more verbose to find out what was the cause?

**Comment by jrmarino** [comment]
it generally says what the problem is.  There's some debugging code for options/dependency checks, but that's not in play here.

btw, synth force ports-mgmt/portmaster works just fine for me (using the latest version)

**Comment by kworr** [comment]
0k, I still have FS problems, this could be it...
