### ISSUE TITLE
command to build without curses / specific profile

### ISSUE THREAD

**Issue by bax-** [jrmarino/synth#55]
Hi!

It would be great to specify non-curses mode or the wanted profile in the command. 
That would make it easier to use curses-mode when in terminal and non-curses mode when calling Synth from cron.

**Comment by jrmarino** [comment]
It already exists and has been in place practically from the beginning.
please see the man page, environment variables, SYNTHPROFILE
There's no need to override curses mode because it's part of the profile you'd call.

**Comment by bax-** [comment]
adding an environment variable for ncurses would be great…

**Comment by jrmarino** [comment]
As I said, there's not need.  You would duplicate the main profile with a second profile that would difference by the ncurses setting and call that second profile at will.  Otherwise I'd have to check for env variables for anything that is covered by a profile.

**Comment by bax-** [comment]
I totally understand. It would solely be a convenience feature so I wouldn't have to update the "cron" profile when I change anything in the makefile. Thanks though.
