### ISSUE TITLE
Text mode: announce builder starting port

### ISSUE THREAD

**Issue by kevans91** [jrmarino/synth#59]
Hello!

Firstly, the 1.52 release of Synth has me pretty happy on all of my machines, thanks! =)

The only nit that I have remaining is that while building in text mode, I generally have to run synth (upgrade-system or install) and then tail -f /var/log/synth/00_last_results.log for the sole purpose of keeping up with what the builders are currently working on, with the occasional switching to watching specific build logs if something seems to be taking a bit too long.

Would you consider having the text mode announce the ports it begins to build? I've been running recently with this change: https://github.com/jrmarino/synth/compare/master...kevans91:portname_announce -- but I don't like the formatting that I've used. This takes a standard run from something along the lines of:

    00:01:08 => [01] Builder launched
    00:01:08 => [02] Builder launched
    00:04:11 =>      Left: 4  Succ: 0  Fail: 0  Skip: 0   Ign: 0
    00:04:38 => [01] 00:03:24 Success graphics/opencv-core
    00:05:36 => [02] 00:04:24 Success editors/vim-lite
    00:05:36 => [02]          Shutting down
    00:07:15 =>      Left: 2  Succ: 2  Fail: 0  Skip: 0   Ign: 0
    00:10:18 =>      Left: 2  Succ: 2  Fail: 0  Skip: 0   Ign: 0
    00:10:19 => [01] 00:05:38 Success multimedia/ffmpeg
    00:11:32 => [01] 00:01:10 Success net/freerdp
    00:11:32 => [01]          Shutting down

into

    00:01:08 => [01] Builder launched
    00:01:08 => [02] Builder launched
    00:01:08 => [01] graphics/opencv-core
    00:01:08 => [02] editors/vim-lite
    00:04:11 =>      Left: 4  Succ: 0  Fail: 0  Skip: 0   Ign: 0
    00:04:38 => [01] 00:03:24 Success graphics/opencv-core
    00:04:38 => [01] multimedia/ffmpeg
    00:05:36 => [02] 00:04:24 Success editors/vim-lite
    00:05:36 => [02]          Shutting down
    00:07:15 =>      Left: 2  Succ: 2  Fail: 0  Skip: 0   Ign: 0
    00:10:18 =>      Left: 2  Succ: 2  Fail: 0  Skip: 0   Ign: 0
    00:10:19 => [01] 00:05:38 Success multimedia/ffmpeg
    00:10:20 => [01] net/freerdp
    00:11:32 => [01] 00:01:10 Success net/freerdp
    00:11:32 => [01]          Shutting down

I did consider using the spacing-padded line format that the 'Shutting down' messages use, but that would seem to cause me more parsing when quickly scanning lines to get an idea of the status.

**Comment by jrmarino** [comment]
> with the occasional switching to watching specific build logs if something seems to be taking a bit too long.

That shouldn't be required; it's what the watchdog is doing

The text mode is basically a developer test mode that I left in place because it was sort of useful.  I'm not really looking to beef it up because it's basic use case is set and forget.  What you're really asking for is the "web interface" (on the to-do list) or a way to query synth about the current state (something I added to DragonFly poudriere that never made it to FreeBSD version)

**Comment by jrmarino** [comment]
I'm considering this, but I would pad the starting lines to maintain pseudo columns.

**Comment by jrmarino** [comment]
enhancement published.
