### ISSUE TITLE
worker configuration is a bit incomplete

### ISSUE THREAD

**Issue by kworr** [jrmarino/synth#6]
For example I'd like to get weird and use clang37 as a compiler. This results in:

    --- libbsd_compat_la-closefrom.lo ---
    .: cannot open /etc/defaults/compilers.conf: No such file or directory
    --- libbsd_compat_la-basename.lo ---
    .: cannot open /etc/defaults/compilers.conf: No such file or directory

Wouldn't it be better to instead of using customized make.conf only create a full directory like /usr/local/etc/synth/<profile>-etc for user to populate and to mock with?

**Comment by kworr** [comment]
I've mean if I override `CCVER` in `make.conf`.

**Comment by jrmarino** [comment]
I guess it depends on how many files we are talking about.  
We can't "replace" etc with a custom version, but we can import into it.
if the only identified shortcoming is compilers.conf and default/compilers.conf, that can be specifically handled similarly to the custom make.conf (e.g. /usr/local/etc/synth/LiveSystem-compilers.conf)

**Comment by jrmarino** [comment]
Thinking about this more, I don't think dports is set up to use alternative compilers in any case.   It might even hard set to base gcc (and ports gcc/clang when the port dictates it)

**Comment by jrmarino** [comment]
by the way, synth was created with "ports compiler" use in mind.
What you could do is create a new root (e.g. make installworld DESTDIR=) and replace ROOT/usr/bin/cc and friends to whatever you want.  You also get a like 4x the performance of custom-cc method.  This will work on freebsd and dragonfly.  (use a new profile ofc)

**Comment by jrmarino** [comment]
I'll close this since the intent has always been to use custom system roots and profiles to handle the scenario.
