### ISSUE TITLE
Synth status doesn't do what it says, issues with PHP 7

### ISSUE THREAD

**Issue by ooglek** [jrmarino/synth#60]
I was trying to get up to date on a few packages that were out of date. I've had problems with synth and php7, and despite LiveSystem-make.conf having `DEFAULT_VERSIONS+= php=7.0` either www/smarty3, devel/phpunit or databases/adodb5 continue to revert everything to PHP 5.6 despite my best efforts.

And tonight, I tried doing a status, to see what would be done, and it broke everything again! Though this may be a problem with the ports themselves, I seem to be able to satisfy requirements just fine when I `make install` from the ports tree directly. 

`synth status` told me it was going to just update/install 5 ports:

> (root) web2 : ~ --> synth status
> Querying system about current package installations.
> Stand by, comparing installed packages against the ports tree.
> Stand by, building pkg(8) first ... done!
> Scan of security/letsencrypt.sh failed (port deleted), it will not be considered.
> Scan of databases/db42 failed (port deleted), it will not be considered.
> Scan of lang/lua failed (port deleted), it will not be considered.
> Scanning existing packages.
> npm-3.9.2.txz failed dependency check.
> These are the ports that would be built ([N]ew, [R]ebuild, [U]pgrade):
>   U => www/node (6.7.0 => 6.8.0)
>   N => devel/ruby-date2
>   U => editors/vim-lite (8.0.0022 => 8.0.0035)
>   U => ports-mgmt/synth (1.54_1 => 1.60)
>   R => www/npm
> Total packages that would be built: 5
> The complete build list can also be found at:
> /tmp/synth_status_results.txt

But when I did a `synth upgrade-system` it did some other things too, which is NOT what I wanted.

> Querying system about current package installations.
> Stand by, comparing installed packages against the ports tree.
> Scan of security/letsencrypt.sh failed (port deleted), it will not be considered.
> Scan of databases/db42 failed (port deleted), it will not be considered.
> Scan of lang/lua failed (port deleted), it will not be considered.
> Scanning existing packages.
> npm-3.9.2.txz failed dependency check.
> 
> The task is complete.  Final tally:
> Initial queue size: 5
>     packages built: 4
>            ignored: 1
>            skipped: 0
>             failed: 0
> 
> Duration: 00:08:00
> The build logs can be found at: /var/log/synth
> Removed: vim-lite-8.0.0022.txz
> Stand by, prescanning existing packages.
> Removed: pkg-1.8.7_3.txz
> Removed: node-6.7.0.txz
> Removed: synth-1.54_1.txz
> Stand by, recursively scanning 224 ports serially.
> Scan of databases/db42 failed (port deleted), it will not be considered.
> Scan of security/letsencrypt.sh failed (port deleted), it will not be considered.
> Scan of lang/lua failed (port deleted), it will not be considered.
> Scanning existing packages.
> Packages validated, rebuilding local repository.
> Local repository successfully rebuilt
> Updating Synth repository catalogue...
> Fetching meta.txz: 100%    260 B   0.3kB/s    00:01
> Fetching packagesite.txz: 100%   59 KiB  60.0kB/s    00:01
> Processing entries: 100%
> Synth repository update completed. 220 packages processed.
> Updating database digests format: 100%
> New version of pkg detected; it needs to be installed first.
> Checking integrity... done (0 conflicting)
> The following 1 package(s) will be affected (of 0 checked):
> 
> Installed packages to be UPGRADED:
>         pkg: 1.8.7_3 -> 1.9.1 [Synth]
> 
> Number of packages to be upgraded: 1
> [1/1] Upgrading pkg from 1.8.7_3 to 1.9.1...
> [1/1] Extracting pkg-1.9.1: 100%
> Updating Synth repository catalogue...
> Synth repository is up-to-date.
> All repositories are up-to-date.
> Checking for upgrades (6 candidates): 100%
> Processing candidates (6 candidates): 100%
> Checking integrity... done (5 conflicting)
>   - php56-5.6.26 [Synth] conflicts with php70-7.0.11 [installed] on /usr/local/bin/php
>   - php56-json-5.6.26 [Synth] conflicts with php70-json-7.0.11 [installed] on /usr/local/include/php/ext/json/php_json.h
>   - php56-phar-5.6.26 [Synth] conflicts with php70-phar-7.0.11 [installed] on /usr/local/include/php/ext/phar/func_interceptors.h
>   - php56-hash-5.6.26 [Synth] conflicts with php70-hash-7.0.11 [installed] on /usr/local/include/php/ext/hash/php_hash_crc32_tables.h
>   - php56-dom-5.6.26 [Synth] conflicts with php70-dom-7.0.11 [installed] on /usr/local/include/php/ext/dom/dom_ce.h
> Checking integrity... done (0 conflicting)
> The following 40 package(s) will be affected (of 0 checked):
> 
> Installed packages to be REMOVED:
>         php70-7.0.11
>         php70-curl-7.0.11
>         php70-iconv-7.0.11
>         php70-pdo_sqlite-7.0.11
>         php70-pdo-7.0.11
>         php70-pdo_mysql-7.0.11
>         php70-sqlite3-7.0.11
>         php70-gd-7.0.11_1
>         php70-mysqli-7.0.11
>         php70-bcmath-7.0.11
>         php70-dom-7.0.11
>         php70-xmlreader-7.0.11
>         php70-zlib-7.0.11
>         php70-soap-7.0.11
>         php70-openssl-7.0.11
>         php70-hash-7.0.11
>         php70-phar-7.0.11
>         php70-opcache-7.0.11
>         php70-posix-7.0.11
>         php70-xmlwriter-7.0.11
>         php70-session-7.0.11
>         php70-xml-7.0.11
>         php70-tokenizer-7.0.11
>         php70-mcrypt-7.0.11
>         php70-ctype-7.0.11
>         php70-mbstring-7.0.11
>         php70-json-7.0.11
>         php70-simplexml-7.0.11
>         php70-filter-7.0.11
> 
> New packages to be INSTALLED:
>         php56: 5.6.26 [Synth]
>         php56-json: 5.6.26 [Synth]
>         php56-phar: 5.6.26 [Synth]
>         php56-hash: 5.6.26 [Synth]
>         php56-dom: 5.6.26 [Synth]
> 
> Installed packages to be UPGRADED:
>         vim-lite: 8.0.0022 -> 8.0.0035 [Synth]
>         synth: 1.54_1 -> 1.60 [Synth]
>         node: 6.7.0 -> 6.8.0 [Synth]
> 
> Installed packages to be REINSTALLED:
>         smarty3-3.1.29 [Synth] (direct dependency changed: php56)
>         phpunit-5.5.5 [Synth] (direct dependency changed: php56)
>         adodb5-5.20.6 [Synth] (direct dependency changed: php56)
> 
> Number of packages to be removed: 29
> Number of packages to be installed: 5
> Number of packages to be upgraded: 3
> Number of packages to be reinstalled: 3

Synth issue or ports tree issue?

**Comment by jrmarino** [comment]
You're getting two things mixed up.
"synth status" forecasts the changes to the repository.

"synth upgrade-system" implements those changes and then tells pkg(8) to update the system using that repository.   The message you are getting is coming from pkg(8), not synth.

You shouldn't use "upgrade-system" unless you are really comfortable with it.
Instead you should use "synth prepare-system" followed by either "synth upgrade-system" (after confirming no build failures from the previous command) or "pkg upgrade -r Synth" to run package directly.

As to your actual problem, you might not have set CONSERVATIVE_UPGRADE=False on pkg.conf, or more likely, you need to rebuild everything that requires php70.  I would confirm by looking at a build log that the PHP default version is actually being set because either it's not or you have packages needing php5.6 that haven't been rebuilt getting installed.

The "nuke it from orbit" way to be sure is just delete all the synth packages and rebuild all from scratch (after verifying profile make.conf is correctly named and getting pulled in)

**Comment by ooglek** [comment]
OK, I'll start back with pkg and the ports tree. I suspect there is an issue with the `USE_PHP = xxx` lines in the port Makefiles that aren't respecting the PHP 7 version. It also looks like `USE_PHP` is deprecated, and something is going batty looking for the `spl` PHP package, which hasn't existed since 5.2. 

I'll take a look at the `CONSERVATIVE_UPGRADE` flag in pkg.conf and try and "nuke" my synth repository -- is there a simple proscribed way to do that?

Thanks for responding to what likely is not an issue with synth. So many layers in these onions... :-)

**Comment by jrmarino** [comment]
it's easy to nuke the repo, just rm -rf <path-to-synth-packages>/all (e.g. rm -rf /var/synth/packages/All).

If you're talking about a "stock" ports tree, it should be configured correctly.  If it's some kind of custom maintained hybrid ports tree, then chances are the tree is broken.

**Comment by jrmarino** [comment]
I'm not sure where you are on this, but you might try v1.61 *IF* you use the "fetch prebuilt packages" option.

If you solved the problem already, you can close the issue.

**Comment by jrmarino** [comment]
I'll assume any issue is now resolved.  If there's additional information, re-open this.
