### ISSUE TITLE
"local" port is not honoured

### ISSUE THREAD

**Issue by ArminGruner** [jrmarino/synth#62]
I have some local defined ports in /usr/ports/local (more or less slave ports into other ports, but with more than just some options tweaked, e.g. more patches applied).

When some of these ports are installed in the system, and synth tries to check which ports to build for a  "prepare-system", it fails for those ports:

Scan of local/XXXX failed, it will not be considered (when the installed ports lists its origin as local/XXXX).

Unfortunately, there is no detailled description even in the log files WHY the scan "failed".

Both "make" in those subdirs, and a portupgrade works fine with these local ports.

Any idea?
Thanks!

Armin

**Comment by jrmarino** [comment]
did you define local as a valid category in the custom makefile?

**Comment by jrmarino** [comment]
also, you might need **local/Makefile** to be created where all the SUBDIRS are defined.

**Comment by ArminGruner** [comment]
Yes, both "local" is defined as a valid category, and there is /usr/ports/local Makefile which lists the ports subdir. Unfortunately, synth keeps saying

"Scan of local/XXX failed, ...".

Some switch for more verbosity may help tracking down the problem.. I've tried to dig into the source, but I'm not much familary with ADA :-/

**Comment by jrmarino** [comment]
It's not a question of verbosity.  If synth knows the problem, it will say so.  It has a number of obvious things to check.  

In this case, I think /usr/bin/make is returning an error after trying to read the file.

What you can do is this (picking a random port):
```
> env ENTERAFTER=extract synth devel/gmake
(wait until you get a prompt)
> cd /xports/local/<portname>
> make -V PKGNAME
```

You should see the error

**Comment by ArminGruner** [comment]
Unfortunately, not:

`# env ENTERAFTER=extract synth test local/tmda
Scan of local/tmda failed, it will not be considered.
There are no valid ports to build.  (Synth must exit)
`
I have no indication why "scan failed"..

**Comment by ArminGruner** [comment]
Sorry for the confusion.

I just ran "synth" under "truss" and analyzed the output.

I'm making heavy use of ZFS filesystems here, and I've forgotten that /usr/ports/local is a separate filesystem. So nullfs-mounting /usr/ports does not pick up the sub-filesystem and thus, /usr/ports/local is not visible in the workers shadow filesystem mounts..

Never mind :)  I will have to find a way how I can fix this.

**Comment by jrmarino** [comment]
To follow up, you didn't follow my suggestion correct.
I didn't want you to "synth test local/tmda", I wanted "synth test devel/gmake" which is a known good port.  After the break, you cd to local/tmda.  devel/gmake was just a doorway to an interactive prompt.

**Comment by jrmarino** [comment]
(you would have then realized that /exports/local didn't exist)
