### ISSUE TITLE
Synth does not like port that install files on /home

### ISSUE THREAD

**Issue by monwarez** [jrmarino/synth#64]
I don't really know if port should have the possibility of create user and installing things on `/home`, but in the case of port that depend on `sysutils/slurm-wlm` , since `slurm-wlm` create the user `slurm` and then try to `mkdir install /home/slurm` when installing. Any port that depend on `slurm-wlm` will fail because of file permission
`install: mkdir /home/slurm: Operation not permitted`
A workaround would be to make a temporary `/home` directory, but I am not sure that it is a correct solution.

**Comment by jrmarino** [comment]
Ports are not allowed to write to /home, period.  Any port that does this must be fixed.  You should open a PR against slurm to document this file system violation.

**Comment by monwarez** [comment]
Thanks , I made a BR https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214268
