### ISSUE TITLE
Port built with Cargo fails to build

### ISSUE THREAD

**Issue by pvalkone** [jrmarino/synth#65]
I'm writing a [port](https://github.com/pvalkone/freebsd-ports/blob/master/textproc/ripgrep/Makefile) of [ripgrep](https://github.com/BurntSushi/ripgrep) for FreeBSD. The application is written in Rust and built using Cargo.

The port builds fine without Synth, but fails on Synth 1.65 because of an apparent issue with permissions ([full build log](https://gist.github.com/pvalkone/cd74efd538a4763c2818074a0ebf9cdf)). Unfortunately, running Cargo with the `--verbose` switch doesn't yield any useful additional information.

    --------------------------------------------------------------------------------
    --  Phase: build
    --------------------------------------------------------------------------------
    ===>  Building for ripgrep-0.2.9
    cd /construction/xports/textproc/ripgrep/work/ripgrep-0.2.9 && cargo build --verbose --release
    error: Operation not permitted (os error 1)
    *** Error code 101

    Stop.
    make: stopped in /xports/textproc/ripgrep

Is there an easy way to debug this further?

**Comment by jrmarino** [comment]
you can use **env ENTERAFTER=build synth test <myport>** to interact with the build after after.

Other than that, you need to figure out what's getting violated.  Ports are not allowed to write to many areas during building (e.g. HOME, /usr/local, etc).  writing isn't the only thing that triggers "operation not permitted", it's a generic error.

That being said, "cargo --verbose" seems to not to be working.  There's no output.

**Comment by pvalkone** [comment]
OK, seems this was, in fact, a permissions issue.

In case someone else stumbles upon the same problem, `cargo(1)` states:

    FILES
       ~/.cargo
              Directory in which Cargo stores repository data.  Cargo can be
              instructed to use a .cargo subdirectory in a different location
              by setting the CARGO_HOME environment variable.

And as you said, `HOME` is not writable. Setting `CARGO_HOME` to point to a writable directory (`${WRKDIR}/.cargo`) solved the problem.

Thanks!
