### ISSUE TITLE
feature request: separation between server and client.

### ISSUE THREAD

**Issue by lebarondemerde** [jrmarino/synth#66]
Hello,

It may be out of the scope of the project, but I do not know indeed. But please, consider this model.

The idea is to separate all the process between a server, what basically would be the responsible to build and store the ports/pkgs per client, and a client what could be installed on several hosts/jails and hold all the options selected for that specific client.

This would be more or less what already can be made with profiles, but a lot of more practical and scalable.

Thank you.

**Comment by jrmarino** [comment]
repositories are not 1:1 (1 repository per 1 user).
They are 1:many (1 repository for many users).
The "client/server" model doesn't make sense to me in the context of a repository.

**Comment by lebarondemerde** [comment]
Yes exactly, it would not be 1:1, but many internal repositories as clients, or group of clients.

In practice, someone whom have several small or very busy machines where he/she want/need to use custom packages, could use a powerful, or eventually a dedicated one, to build pkgs for the entire infrastructure using a automated process.

On the server side, it would receive the request from the clients with its specifics configurations, and maybe "CPUTYPE?" too, build them and store in the directory of that client or group (clients with identical needs). One time the request from a client be done, the server send a message to the client to it download and make the upgrade. So, the server would act more like a build agent who also store the packages.

I usually do not do this kind of feature request because I do not code, and so I could not help to make the things happen, but I think something like this would be very handy for sysadmins with several installations/jails.

Thank you.

**Comment by jrmarino** [comment]
As you guess, you're describing profiles.
Each repository can be individually customized, and that's done with unique *-make.conf files and options directories and obviously unique package directories for output.

There is nothing "more efficient" then this.  Each repository requires every desired package and their dependencies to be built.

I can't envision what you are asking for because you already have the most efficient method available.

**Comment by lebarondemerde** [comment]
Yes, same thing but with remote request capabilities. A remote machine, with the hypothetical "synth-client" could request ports to be built on another machine, the hypothetical "synth-server". When those packages were built, automatically download and install it like we can do locally today.

Basically the same behavior we have today, but could also be done remotely.

Thank you.

**Comment by jrmarino** [comment]
What's stopping you now?
It's not like synth can't be run under a cron job.  Anything that can dispatch shell commands could do this.

**Comment by lebarondemerde** [comment]
Ok, I will look how to do this like you say.

Thank you.

**Comment by jrmarino** [comment]
Look at the SYNTHPROFILE environment variable on the synth man page.
You can execute synth with any profile and any build list.  You just need to have the mechanism for issuing those commands.  It's definitely out of scope for Synth, especially given how easy it is to command (even remotely).
