### ISSUE TITLE
Synth try update to a previous version

### ISSUE THREAD

**Issue by monwarez** [jrmarino/synth#69]
It's happening with irssi ` U => irc/irssi (1.0.0 => 0.8.21,1)`
Not sure if it is synth fault or pkg fault. While here , is there a way to have synth repository that match the current software installed (like not recompiling software that was deleted with pkg delete for example) ?

**Comment by jrmarino** [comment]
For the latter, that's what 

> synth prepare-system

or

> synth upgrade-system

does.  The build list comes from what is installed on the system.  Using **pkg delete** changes the build list.

For the former, neither is at fault.  The port was downgraded for everyone.  See:
http://www.freshports.org/irc/irssi
commit log

**Comment by monwarez** [comment]
Thanks, I didn't see that the port was downgrade
