### ISSUE TITLE
synth purge-distfiles opens a LOT of file-descriptors

### ISSUE THREAD

**Issue by daemonblade** [jrmarino/synth#70]
*synth purge-distfiles* on my system requires me to bump kern.maxfiles from 12328 to 36984 in order for it to succeed. A small script on my system using fstat(1) to count open files by root indicated that there were more than 20K open descriptors when running purge-distfiles.

Is this intentional?

**Comment by jrmarino** [comment]
It's not intentional.  It looks like there may be a missing file close in a loop.  
I'd get you to test a patch but I'm guess you already deleted the files.

**Comment by daemonblade** [comment]
Send me the patch anyway, I'll see if I can put in a couple of thousand empty files in my distfile directory to test the fix.

**Comment by jrmarino** [comment]
okay, try applying this patch to the port makefile.  I think it will fix the issue.

```
--- a/ports-mgmt/synth/Makefile
+++ b/ports-mgmt/synth/Makefile
@@ -3,6 +3,7 @@

 PORTNAME=      synth
 PORTVERSION=   1.66
+PORTREVISION=  1
 DISTVERSIONPREFIX=     v
 CATEGORIES=    ports-mgmt

@@ -19,6 +20,7 @@ BUILD_DEPENDS=        ${LOCALBASE}/lib/libncurses.a:devel/ncurses \
 USES=          ada:6
 USE_GITHUB=    yes
 GH_ACCOUNT=    jrmarino
+GH_TAGNAME=    4d9f5ea

 GPR=           ${LOCALBASE}/lib/gnat
 MAKE_ENV=      NCURSES_LINK=static
diff --git a/ports-mgmt/synth/distinfo b/ports-mgmt/synth/distinfo
index fadadddc63..8fb6f67795 100644
--- a/ports-mgmt/synth/distinfo
+++ b/ports-mgmt/synth/distinfo
@@ -1,3 +1,3 @@
-TIMESTAMP = 1481720544
-SHA256 (jrmarino-synth-v1.66_GH0.tar.gz) = 4edd974e5ed091a1b629e4c9ff7507923156aa749b9664ca7f727e220931bc2b
-SIZE (jrmarino-synth-v1.66_GH0.tar.gz) = 137564
+TIMESTAMP = 1484855429
+SHA256 (jrmarino-synth-v1.66-4d9f5ea_GH0.tar.gz) = 7b3eba1c84b9f10db9d82b61fd29d217d17edb5da51f747b07a4daf17214b56e
+SIZE (jrmarino-synth-v1.66-4d9f5ea_GH0.tar.gz) = 137605
```

**Comment by jrmarino** [comment]
relates to 4d9f5ea

**Comment by daemonblade** [comment]
I had to do a manual patch, but the code change works as expected.

Thanks!

**Comment by jrmarino** [comment]
Thanks for the report and the fix testing.  I've pushed it to FreeBSD ports.
