### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by mfoacs** [jrmarino/synth#71]
Hi there,

I have been poking around with synth and being pretty satisfied so far, I wonder what is the current status of the web interface? I can make mine to work in spite of configuring nginx for serving the Report directory. 

That could be entirely my fault:

nginx.conf:

listen       80 default;
        server_name myservername;
        root /var/log/synth/Report;
        location / {
            root   /var/log/synth/Report;
            index  index.html;
        }
        location /data {
            alias /var/log/synth;
            autoindex on;
        }
        location /packages {
            root /opt/synth/live_packages;
            autoindex on;
        }

The last declaration is intended to serve packages to my other servers (home based network) but I haven't tested yet.

nginx logs don't have anything to work on either so I am a bit lost. It might be a nginx issue but a similar setup was working with poudriere before so it makes me wonder what am I missing here?

**Comment by jrmarino** [comment]
The web interface is fully functional and complete.  You just have to expose it.
You don't even need a web server if the system is a desktop.  You can just use your browser and the file:/// url that points to report.

You need to expose /var/log/synth (not only /var/log/synth/Report) though, otherwise you won't be able to view the logs.

**Comment by mfoacs** [comment]
Yes, I can see the raw logs if I expose the /var/log/synth directory but I won't have the html reporting. The machine running synth doesn't have a desktop or X server running. Not an option. Would you have an example of a http server (apache, nginx, ligthttpd, etc) configuration that one could use?

**Comment by jrmarino** [comment]
If you see the raw logs, then navigate to "Report" directory.  It should be first one in the directory.
If you click on it, the reporting just works.

http server configuration is out of scope here.

**Comment by mfoacs** [comment]
Fair enough, the http server conf was for control purposes only. However the Report is a nice static and blank html page. Nothing happening there. What I am missing?

**Comment by jrmarino** [comment]
did you actually build anything?
The only reason it would be blank is if you issued a build command and it just exited (nothing was left in queue to build).

Start the build command, then go to the page.

**Comment by mfoacs** [comment]
yes I am building around 700 packages now.

**Comment by jrmarino** [comment]
ls anything changing inside the Report directory?

**Comment by jrmarino** [comment]
The last xx_history.json should change every 8 seconds or so.

**Comment by mfoacs** [comment]
No, not inside the report directory. The logs are being updated and the packages are being built though...

**Comment by jrmarino** [comment]
That's not possible.
Those .json files are written throughout the build, every few seconds.  If it's static, you're not looking in the correct directory.  DId you change the location in the configuration?

**Comment by mfoacs** [comment]
I change a couple of locations in the configuration but not those. There is one file, 01_history.json being updated indeed but it seems like the script is not picking it up.

**Comment by jrmarino** [comment]
sounds like an http server issue then.
Maybe you can use chromium dev tools to figure out why the page isn't displaying.

**Comment by jrmarino** [comment]
you can also try to display 01_history.json directly via its url and see if server is serving it.

**Comment by mfoacs** [comment]
Right I just launched a synth prepare-system and the json file is gone.

**Comment by mfoacs** [comment]
Solved: its a Firefox issue. Chrome shows it nicely.

**Comment by jrmarino** [comment]
okay, thanks for following up.
Nobody has complained about Firefox not showing it before.

**Comment by mfoacs** [comment]
Sure. Unfortunately that doesn't prove anything. Thanks for you help. Great
support.

**Comment by jrmarino** [comment]
well, the four conclusions you can draw are:

1.  nobody uses firefox
1.  nobody uses firefox -and- views synth reports
1.  nobody that uses firefox and synth has bothered to report it
1.  firefox works with synth reports for everyone except you, for some reason

**Comment by jrmarino** [comment]
can you see this page with firefox? 
http://muscles.dragonflybsd.org/synth/snap-failures/Report/

**Comment by jrmarino** [comment]
I asked on DF irc and somebody with firefox can see that report. (arch linux)

**Comment by mfoacs** [comment]
interestingly enough I see it just like mine: [image: pasted1]
FF 51.0.1 x64 on SuSE Leap 42.1

**Comment by jrmarino** [comment]
The image didn't come through.
I don't know if you mean you can see it correctly or if it's blank.
If the latter, that seems to be a SuSE FF issue then.

**Comment by mfoacs** [comment]
I can see the headers, placeholders, page structure and layout, I can get
the css, the .js and the json parsed in the browser. I don't know how
pertinent it might be but it works with poudriere. I am testing now with
another FF (Mac OS) and I see the same issue. I will investigate further
and let you know.

**Comment by jrmarino** [comment]
You don't have NO_SCRIPT set do you?

**Comment by mfoacs** [comment]
Nope but I've found the culprit: it's called Privacy Badger. I disabled the bugger and voilà, works like a charm!

**Comment by mfoacs** [comment]
Basically because one of the scripts is downloaded from cdn.datatables.net.
