### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by rickroberts** [jrmarino/synth#74]
synth status
Builder mounts detected; attempting to remove them automatically ...
Dismounting successful!
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.

raised REPLICANT.SCENARIO_UNEXPECTED : /usr/sbin/mtree -p /usr/obj/synth-live/SL09/var -f /etc/mtree/BSD.var.dist -deqU => failed (exit code not 0)

**Comment by jrmarino** [comment]
it might be a mistake.
The mtree program is known to return non-zero codes nominally.  Usually the return code is ignored but it seems not in this case.

you can run the command:
```
/usr/sbin/mtree -p /usr/obj/synth-live/SL09/var -f /etc/mtree/BSD.var.dist -deqU
```
after you get the error to see what the problem really is.  Maybe you're missing /etc/mtree/BSD.var.dist.   Even if it's a mistake to check the exit code, nobody else has reported this so it might be a real problem on your self.

**Comment by rickroberts** [comment]
My colleague fixed it: “I believe it is failing because of an unbound user designation.
I believe I have fixed the issue by forcing an update of the /etc/pwd.db and spwd.db files which are byproducts of the passwd and master.passwd system.“
