### ISSUE TITLE
WHYFAIL has no appreciable affect on final output

### ISSUE THREAD

**Issue by bsdforge** [jrmarino/synth#79]
Hello, John.
When synth works; it works fan-tastic. But when things seem amiss, it's super frustrating!
To the point; I'm chasing -CURRENT on FBSD. This is my second update to the box. So I'm
utilizing synth to create a repo I can leverage to update the ports on it -- ~670. So I use
the following schema:
synth configure
synth status
synth prepare-system

All work much as anticipated. 22 ports are skipped due to 3 failures. I investigate the
skipped log to find the culprit(s). I then cd to those directories and attempt to build
the offending ports. They all build w/o failure. So I'm left to wonder _why_ synth "bailed"
on them. I investigate further; I discover WHYFAIL. So I issue
env WHYFAIL=true synth prepare-system
Again, synth fails on the same ports, and skips the dependent ports. I attempt to
discover _why_ synth bailed on them. But I can find no more info in the logs that I
had available to me prior to using WHYFAIL. Perhaps I simply don't know _where_
to look.
FWIW I have no trouble building the offending ports, nor do I have any trouble
creating the package (pkg) for them. But synth rejects the packages, and insists
that they need to be rebuilt, due to dependency failure.
Any insight on this would be GREATLY appreciated!

Thanks!

--Chris

**Comment by jrmarino** [comment]
did you check the 06_* log?

generally bails like that are because the port is set to IGNORE.  so you might see them in the ignore log too (02_* I think)

**Comment by bsdforge** [comment]
**JACKPOT!**
Case closed.
The results were _indeed_ in the 06_ log.
Sorry for the noise. I could have _sworn_ I checked **all** the logs. :(

Thanks for the help, _and_ for synth.

--Chris
