### ISSUE TITLE
pkg update yields "pkg: file:///var/synth/live_packages/meta.txz: No such file or directory" after running synth

### ISSUE THREAD

**Issue by Rolinh** [jrmarino/synth#8]
After running `synth` (probably `synth upgrade-system` or `synth status`), `pkg update` yields errors regarding repository files belonging to `synth`.
```
$ pkg update
Updating Synth repository catalogue...
pkg: file:///var/synth/live_packages/meta.txz: No such file or directory
repository Synth has no meta file, using default settings
pkg: file:///var/synth/live_packages/packagesite.txz: No such file or directory
Unable to update repository Synth
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
```

This is on a FreeBSD 10.1 hosts.

**Comment by jrmarino** [comment]
try "synth rebuild-repository" so you can see why the repository isn't getting built.
(probably related to the issue with a failed tree scan)

**Comment by Rolinh** [comment]
I haven't seen this issue again after rebuilding the repository. Not exactly sure what happened.
