### ISSUE TITLE
synth just-build insists on building more than is in the list

### ISSUE THREAD

**Issue by bsdforge** [jrmarino/synth#80]
OK. Maybe this is intentional. But I could find no evidence in the man file
that indicates that synth will build any more, than what is in the file.list.
eg; synth just-build ./build.list
where "build.list" contains
textproc/libxslt
x11/libxcb
x11/libX11
x11/libXext
x11/libXfixes
x11/libXv
graphics/libdrm
x11/libXdamage
x11/libXvMC

My list file is much bigger. But my issue is, that when synth is passed my list, it insists upon
adding devel/llvm39 && devel/llvm40. Both of which are already installed on the system _and_
are _not_ in the build.list file.

What am I missing. Should I have _assumed_ synth would automatically include any
dependency it felt it needed? If so, I would have rather thought that synth would simply
"dismiss" files it felt it couldn't build w/o additional files. Much as it does when it finds
other conflicts.

Thanks, John, and sorry if this somehow seems a stupid question, with an obvious answer.

--Chris

**Comment by jrmarino** [comment]
>  Both of which are already installed on the system
What is installed on your system is irrelevant.
> are not in the build.list file.
The build list are the packages you want.  It's implicit that if those packages have dependencies, those dependencies will be built in order to accomplish the list.

Extreme example:
Your build list contains two ports on it: libreoffice and kde4
Obviously hundreds of packages have to be built to accomplish that.

So by now it should be obvious that some requirement of your build list has a requirement on llvm39 and llvm40, maybe 2 or 3 levels deep.  And it's probably graphics related.

**Comment by bsdforge** [comment]
Huge thanks for the reply, John.
Indeed. I _do_ understand that in order to fulfill/complete (the building of) the list. That
dependencies _must_ **also** be fulfilled. But, as I also noted; it seemed that it may
well be possible to simply _dismiss_ those within the list that don't also include their dependencies
within the list. Much as it already does when asking it to "prepare-system", and there is some
problem encountered that prevents it from building some, or one of the ports.
No matter. I didn't see a conclusive answer within the man pages. So I simply asked.
Now I understand. :-)

Thanks John, for taking the time to answer -- greatly appreciated!
Have a nice weekend!

--Chris

**Comment by jrmarino** [comment]
it's a recursive list.  For every package that isn't already built adds its dependencies to the list, and each of of those can to.  Nothing can be removed off the list; they are all necessary.

For a system that's only served by synth, there are no build dependencies installed.  Thus the build list could *easily* exceed the installed list of a given system.  That's normal.

**Comment by bsdforge** [comment]
Thanks again, John.
I get what it's intent is. I just wasn't sure which way it would turn. IOW
If I tell it to prepare-system. It builds a list, and attempts to fulfill that list, creating every item in it.
_But_ if for some reason, it encounters a problem building one of the ports in that list; it returns
Failure, which in turn cascades to those that depend ON it. Resulting in a list of Skipped.
THIS is why I wasn't sure what would be my results feeding it a build.list. You see, it could
have gone either way. But you decided it best to _ensure_ satisfaction of the dependencies.
I understand, and that makes plenty of sense. :-)
But in _this_ case. I was hoping it would have chosen to simply Fail, and only build those
whose dependencies _were_ met.
Not a big deal. I appreciate you taking the time to help. I hope to give synth a real workout.
It is my intent to make this box it's working on, a build-box. Which synth will largely be
responsible for.

--Chris

**Comment by bsdforge** [comment]
Oh, and just for the record. I am NOT complaining about the direction you chose
for dealing with the build.list. I just wasn't sure, and I needed it to do the "wrong"
thing, in this ONE case. :-)

Thanks again!

--Chris

**Comment by jrmarino** [comment]
> But in this case. I was hoping it would have chosen to simply Fail, and only build those
whose dependencies were met.

It does build everything it can.
The fail cascades to a number of skips.  Whatever is still left in the queue will build (unless another failure causes it to skip of course).

**Comment by jrmarino** [comment]
Chris, have you noticed a triad of new repositories in my github account?
https://github.com/jrmarino/Ravenports
https://github.com/jrmarino/ravenadm
https://github.com/jrmarino/ravensource

**Comment by bsdforge** [comment]
Umm. How can I say this... **WOW!**
Mind you; I've mostly just grabbed the gist of it. But if my further reading concurs with my
initial impression. Count me in. I love it!
It's funny. I've been working on a large scale project with someone over the last few months.
I *also* needed to deal with managing ports/software that would need to built on a regular basis,
and had been building a model in my mind to best accomplish that task. Yours, I must say, is
quite a different direction than I was taking -- not that I disagree with it (your direction). I'm just
appreciating the difference. That's all. :-)
OK I just spent some more time reading the source. Being an old Perl hack made it quite simple. ;-)
It seems a combination of Perl, C &&sh. Simple, and easy to follow. Easy reading. Tho it doesn't
hurt to have some background with the FreeBSD ports framework -- thanks John!
Oh, and I love the "conspiracy" label/term you coined for this. :-)
What's the status? How far out is it, would you estimate?
As soon as I can [finally] get my development system fully up'd (see next comment in this thread)
I'd love to help with this.

Thanks for pointing this out!

--Chris

**Comment by bsdforge** [comment]
OK I've struggled with this for ~72hrs. now, and I'm out of thoughts. This system tracks FreeBSD 12
current. Has now had 2 new worlds/kernels (both custom). I (initially) built all the ports from the tree.
I upped the src && ports together. So they're in sync. World && kernel built/installed w/o incident.
Synth will get me a complete repo, minus 17 ports. It all involves a cascade from a 3 port apex.
The 3 culprits are:
```
devel/libnotify (skipped 8)
textproc/libxml++26 (skipped 6)
devel/gnome-vfsmm
```
The complete list of skipped:
```
sysutils/gnome-mount by devel/libnotify
devel/gvfs by devel/libnotify
sysutils/xfce4-settings by devel/libnotify
x11-fm/thunar by devel/libnotify
deskutils/xfce4-notifyd by devel/libnotify
x11-wm/xfce4 by devel/libnotify
x11-wm/xfce4-desktop by devel/libnotify
www/firefox-esr by devel/libnotify
graphics/gx by textproc/libxml++26
graphics/cairomm by textproc/libxml++26
graphics/gimmage by textproc/libxml++26
x11-toolkits/gtkmm24 by textproc/libxml++26
x11-toolkits/pangomm by textproc/libxml++26
devel/gconfmm26 by textproc/libxml++26
```
I've attempted to singly target any one of the three culprits. But haven't managed to get
any of them to build (within synth). Regarding: textproc/libxml++26
attempting to build it within synth _seemed_ to fail based (according to synth) on the fact that
a dependency on devel/glib20, and that devel/glib20 is one revision too new -- it wants
revision 1. But glib20 is at revision 2. I can't understand this. Everything comes from the
same local ports tree.
Any way to get around this sort of thing within synth?

Thanks, John!

--Chris

**Comment by jrmarino** [comment]
> It seems a combination of Perl, C &&sh. Simple, and easy to follow. Easy reading. Tho it doesn't hurt to have some background with the FreeBSD ports framework -- thanks John!

Well, there's no C or Perl in it at all.
Everything runs through ravenadm, which is essentially "synth 2.0".  The "ports" are single file "buildsheets" that ravenadm processes.  the "make" program is not involved at the user level.

There is a "make" framework that is based on ports but completely re-written. That is make + shell scripts only though.  It's pure Ada other than about 1% C objects used in ravenadm/ravenexec.

> conspiracy

A flock of ravens is known as an "unkindness", "conspiracy" or a "constable".  But yes, there's a double-entendre there.

**Comment by jrmarino** [comment]
portsnap may have failed on you (assuming you are using portsnap and not svn).

If you are using portsnap, I suggest blowing the tree away and repulling it.

**Comment by bsdforge** [comment]
> > It seems a combination of Perl, C &&sh...
> 
> Well, there's no C or Perl in it at all.
> Everything runs through ravenadm, which is essentially "synth 2.0". The "ports" are single file "buildsheets" that ravenadm processes. the "make" program is not involved at the user level.
> 
> There is a "make" framework that is based on ports but completely re-written. That is make + shell scripts only though. It's pure Ada other than about 1% C objects used in ravenadm/ravenexec.

Indeed. I was trying to get up to speed too quickly. It just _felt_ that way, I guess. Still. I
found it easy reading. Tho much of that also speaks to your organization. Well conceived!

> > conspiracy
> 
> A flock of ravens is known as an "unkindness", "conspiracy" or a "constable". But yes, there's a double-entendre there.

I always thought a flock of ravens were referred to as Murders. No?

Thanks John.

**Comment by jrmarino** [comment]
a flock of crows are a "murder".
Ravens are cousins to crows but not the same.

FYI, a porter's guide I'm slowing writing: https://github.com/jrmarino/Ravenports/wiki/Ravenporters_Guide

**Comment by bsdforge** [comment]
> portsnap may have failed on you (assuming you are using portsnap and not svn).
> 
> If you are using portsnap, I suggest blowing the tree away and repulling it.

Hmm. No portsnap involved here. Never use it.
I'l have to figure some way to coerce it into a package. I'm confident that a 1 point revision
won't give too much grief, if any.
Back to the think tank...

Thanks for trying, John.

--Chris

**Comment by bsdforge** [comment]
> a flock of crows are a "murder".
> Ravens are cousins to crows but not the same.

Heh. Funny how crows, and ravens were given such _dubious_ names. It might be interesting to look further into that, some time.

Thanks for the clarification!

--Chris

**Comment by jrmarino** [comment]
the point is that the ports tree you are using is disintegrated.
Or at least that's the theory based on what you are seeing.

If the tree is good, then *everyone* would see what you are seeing.  I assume if's a "just me" situation so suspect either make.conf or your tree.

**Comment by bsdforge** [comment]
P.S.
I wish your Triad was complete, and the [ports] repo was full right now. I kick all this
mess I'm currently working on, to the curb, and start using immediately!
The more I read in your wiki. The more I'm liking it.

Thanks!

--Chris

**Comment by bsdforge** [comment]
> the point is that the ports tree you are using is disintegrated.
> Or at least that's the theory based on what you are seeing.
> 
> If the tree is good, then everyone would see what you are seeing. I assume if's a "just me" situation so suspect either make.conf or your tree.

That'd be odd. I haven't done anything but svn up, on both trees.
This is the extent of my make.conf
`DEFAULT_VERSIONS+=perl5=5.24 pgsql=9.6 python3=3.4 python2=2.7 ruby=2.3 linux=c7 tcl=87 tk=86`

Not really arguing with you. Just having a bit of trouble _explaining_ to myself how that it's
even possible. I've been on *BSD for ~35yrs. and don't ever recall running into a
corrupted tree, via cvs, or svn.

But in the end. You're probably right. The only _reasonable_ answer is to blow it (the tree) away,
and start afresh. :-(

Thanks for the reply, John.

--Chris

**Comment by jrmarino** [comment]
what about libnotify?  what's causing that to fail?

**Comment by jrmarino** [comment]
by the way, IIRC you are using "upgrade-system" rather than using your own buildlists

**Comment by jrmarino** [comment]
meaning what is installed on your system could be given bad instructions to synth.

**Comment by jrmarino** [comment]
try this:
```
pkg query -e '%a=0' '%o' > my.list
```
The check UPDATING for libnotify and modify list as needed.

**Comment by jrmarino** [comment]
(and obviously give my.list to synth instead of using update-system)

**Comment by bsdforge** [comment]
Thanks, John!
I really appreciate your taking so much time for this!
OK followed your advice, and fed the list pkg generated. But, of course, only 3 of the build slots got
populated, and they were those same 3 ports. Which ultimately failed, as before.
So, at this point. I've decided to use as much as I've managed to get synth to build for me, and
issued
`pkg upgrade -r Synth`
I'm now going to bounce the box, query synth && feed it that list again. If failure ensues. I'm
just going to cd to those 3 port directories and issu a
`make package install clean`
Ask synth what it then thinks. If all looks good, synth will complete building the dependent
ports, and life is good; else
`cd /usr/ports; svn up .`
followed by
`synth rebuild-repository`
&&
`synth prepare-system`

Wish me luck, and have a wonderful weekend!

--Chris

P.S.
There was nothing in UPDATING regarding libnotify
my ports tree is at 437523

**Comment by bsdforge** [comment]
Well. That flushed out the problem. Well, one of them;
After allowing pkg to upgrade the system, and bouncing the box. I took a stab at
```
cd /usr/ports/textproc/libxml++26
make package install clean
```
The build of which, failed. Seems the addition of llvm39 && llvm40, from the ports
tree revealed a problem with textproc/libxml++26, that my base install of llvm40 did not.
So synth was spot on, about there being a problem. It just couldn't tell me _what_ exactly.
Anyway. Looks like it's time to up the ports tree, and see if I can get a buildable version.

Take care!

--Chris out...
