### ISSUE TITLE
size mismatch error

### ISSUE THREAD

**Issue by metsuke0** [jrmarino/synth#81]
OS: 11.0-RELEASE-p9
Synth is building packages successfully in a jail and /var/synth/live_packages is exposed via nginx on port 80.

I created another jail to test the repo, which is the only one listed after a `pkg -vv`.  This is the output from the test jail.

```
root@dev2:~ # pkg install nginx
Updating synth repository catalogue...
synth repository is up to date.
All repositories are up to date.
The following 2 package(s) will be affected (of 0 checked):
New packages to be INSTALLED:
        nginx: 1.10.3_1,2
        pcre: 8.40
Number of packages to be installed: 2
The process will require 6 MiB more space.
1 MiB to be downloaded.
Proceed with this action? [y/N]: y
[dev2] [1/2] Fetching nginx-1.10.3_1,2.txz: 100%  342 KiB 349.9kB/s    00:01
pkg: cached package nginx-1.10.3_1,2: size mismatch, fetching from remote
[dev2] [2/2] Fetching nginx-1.10.3_1,2.txz: 100%  342 KiB 349.9kB/s    00:01
pkg: cached package nginx-1.10.3_1,2: size mismatch, cannot continue
```

Here is the repo config I used on the test jail in /usr/local/etc/pkg/repos/pkg.conf.
```
synth: {
URL:    "http://synth.localdomain.com/pkg"
ENABLED: true
MIRROR_TYPE:    "none"
}
```

**Comment by jrmarino** [comment]
isn't that a local issue with the packages you have cached?
Make pkg clear the cached packages.
In any case, it's out of scope of synth.  
FWIW, I don't think the issue is with the webserver, I think the local machine's cache is confusing pkg(8).  It might also be trying to combine pkg.freebsd.org with your new repository, so remove pkg.freebsd.org from the configuration temporarily.

**Comment by metsuke0** [comment]
This can be closed then, since it is out of the scope of the project.  Thanks for the pointers.

**Comment by metsuke0** [comment]
FYI - the issue was that `synth rebuild-repository` was failing.  After recreating the synth jail without experimental modifications, everything worked, thanks!
