### ISSUE TITLE
Error opening terminal: xterm

### ISSUE THREAD

**Issue by mexas** [jrmarino/synth#85]
```
# synth build net/mpich
Error opening terminal: xterm.
```
I already allowed root to use X, by adding the user's
.Xauthority to /root/.Xauthority. So I can launch xterm as root.

I also tried
```
# env TERM=xterm synth build net/mpich
Error opening terminal: xterm.
```
which I saw in some forums.

Please advise

Thanks

Anton

**Comment by mexas** [comment]
Forgot to say - this is FreeBSD 11.0-RELEASE-p9 with
```
# pkg info -xo synth
synth-1.69                     ports-mgmt/synth
```

**Comment by jrmarino** [comment]
It looks like an issue with your specific FreeBSD.
"X" has nothing to do with this though.
It looks like your terminal support or termcap database or something like that is broken.

**Comment by jrmarino** [comment]
FYI: don't confirm "xterm" with a program named "xterminal" or something like that.

**Comment by mexas** [comment]
Any advice on debugging this?
Do you know at what point this error message is issued?
Is it even issued by synth itself? Or some program launched by synth?

**Comment by mexas** [comment]
I can't remember when I last had trouble with termcap.
Here's what I have in /etc/termcap.small:
```
# $XTermId: termcap,v 1.78 2009/11/09 00:24:26 tom Exp $
#    
xterm-new|modern xterm:\
        :@7=\EOF:@8=\EOM:F1=\E[23~:F2=\E[24~:K2=\EOE:Km=\E[M:\
        :k1=\EOP:k2=\EOQ:k3=\EOR:k4=\EOS:k5=\E[15~:k6=\E[17~:\
        :k7=\E[18~:k8=\E[19~:k9=\E[20~:k;=\E[21~:kI=\E[2~:\
        :kN=\E[6~:kP=\E[5~:kd=\EOB:kh=\EOH:kl=\EOD:kr=\EOC:ku=\EOA:\
        :tc=xterm-basic:
#    
# This chunk is used for building the VT220/Sun/PC keyboard variants.
xterm-basic|modern xterm common:\
        :am:bs:km:mi:ms:ut:xn:AX:\
        :Co#8:co#80:kn#12:li#24:pa#64:\
        :AB=\E[4%dm:AF=\E[3%dm:AL=\E[%dL:DC=\E[%dP:DL=\E[%dM:\
        :DO=\E[%dB:LE=\E[%dD:RI=\E[%dC:UP=\E[%dA:ae=\E(B:al=\E[L:\
        :as=\E(0:bl=^G:cd=\E[J:ce=\E[K:cl=\E[H\E[2J:\
        :cm=\E[%i%d;%dH:cs=\E[%i%d;%dr:ct=\E[3g:dc=\E[P:dl=\E[M:\
        :ei=\E[4l:ho=\E[H:im=\E[4h:is=\E[!p\E[?3;4l\E[4l\E>:\
        :kD=\E[3~:kb=^H:ke=\E[?1l\E>:ks=\E[?1h\E=:le=^H:md=\E[1m:\
        :me=\E[m:ml=\El:mr=\E[7m:mu=\Em:nd=\E[C:op=\E[39;49m:\
        :rc=\E8:rs=\E[!p\E[?3;4l\E[4l\E>:sc=\E7:se=\E[27m:sf=^J:\
        :so=\E[7m:sr=\EM:st=\EH:\
        :ue=\E[24m:up=\E[A:us=\E[4m:ve=\E[?12l\E[?25h:vi=\E[?25l:vs=\E[?12;25h:
#
# This is the only entry which you should have to customize, since "xterm"
# is widely used for a variety of incompatible terminal emulations including
# color_xterm and rxvt.
xterm|X11 terminal emulator:\
        :tc=xterm-new:
```
I think this is the default install.

**Comment by jrmarino** [comment]
You have the option to turn off ncurses display.
```
synth configure
```
set ncurses to false.
That should at least allow you to use synth.
You can point a browser to the logs directory to see the web-based real-time display.

**Comment by mexas** [comment]
Thanks. That works.
I also checked on another box, and synth works fine with default settings.
So yes, something is wrong with my FreeBSD config, perhaps with ncurses.

**Comment by jrmarino** [comment]
There's nothing wrong with ncurses.
That setting just avoids ncurses which invokes xterm.
Several people have commented that you're not running xterm with the correct permissions.  You should read what they say.  Blaming it on ncurses is the wrong path.

**Comment by mexas** [comment]
I found out that on another box, where synth with ncurses works fine I had
a soft link:
```
# ls -al /etc/termcap
lrwxr-xr-x  1 root  wheel  23 Dec  4  2012 /etc/termcap -> /usr/share/misc/termcap
```
which was missing on the problem box. Now works fine.
Thanks for your time!

**Comment by jrmarino** [comment]
ok.  looks like my original comment was correct then:
> It looks like your terminal support or termcap database or something like that is broken.
IIRC that symlink comes installed on new systems.
