### ISSUE TITLE
/etc/make.conf not sourced

### ISSUE THREAD

**Issue by mexas** [jrmarino/synth#88]
I understood from the synth man page and from github description
that /etc/make.conf is read in all cases. And if there are extra
conf files, e.g.
```
/usr/local/etc/synth/LiveSystem-make.conf
```
then these are added to /etc/make.conf.

Did I get this right?

It seems /etc/make.conf is not honoured by my synth builds.
I have:
```
# cat /etc/make.conf 
DEVELOPER=yes
DEFAULT_VERSIONS=gcc=8
FFLAGS+= -O2 -pipe -march=bdver2 -mtune=bdver2
FFLAGS+= -funroll-loops --param max-unroll-times=4 -ftree-vectorize
FFLAGS+= -g
```
I then force build net/mpich, but see that it's still built with
the default GCC 5.4.0, not GCC8, as requested in /etc/make.conf:
```
# which mpif90
/usr/local/bin/mpif90
# mpif90 --version
GNU Fortran (FreeBSD Ports Collection) 5.4.0
```

Did I misread the synth man page?
Shall I put what is currently in /etc/make.conf into e.g.
```
/usr/local/etc/synth/LiveSystem-make.conf
```

Thanks

Anton

**Comment by jrmarino** [comment]
no.  Apparently people interpret man page incorrectly.
Synth internally generates a make.conf file.  People think when the man page references the generated make.conf, it means "/etc/make.conf".  That's incorrect.  /etc/make.conf is never used.

**Comment by mexas** [comment]
Got it. Thanks!
