### ISSUE TITLE
Minor log file path error

### ISSUE THREAD

**Issue by qcybb** [jrmarino/synth#91]
In the port log file, the paths to "PKG_CACHEDIR" and "PKG_DBDIR" are incorrect.

It should be "pkg", not "pkg8".

```
--------------------------------------------------
--  Environment
--------------------------------------------------
UNAME_r=10.3-SYNTH
UNAME_m=amd64
UNAME_p=amd64
UNAME_v=FreeBSD 10.3-SYNTH
UNAME_s=FreeBSD
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
SSL_NO_VERIFY_PEER=1
TERM=dumb
PKG_CACHEDIR=/var/cache/pkg8
PKG_DBDIR=/var/db/pkg8
PORTSDIR=/xports
LANG=C
HOME=/root
USER=root
```

**Comment by jrmarino** [comment]
it can be anything.
This refers to the internal build environment, *NOT* the localhost.
I could have called it /var/db/cinderella and it would work just as well.  What the localhost uses by default is irrelevant.

**Comment by qcybb** [comment]
My apologies, I did not realize this was the internal build environment variables.

**Comment by jrmarino** [comment]
no problem.
