### ISSUE TITLE
When interrupted synth does not unmount file systems properly

### ISSUE THREAD

**Issue by yasuhirokimura** [jrmarino/synth#95]
When building ports synth mount some  file systems to create workplace for each builders. In normal case these file systems are properly unmounted after builders are shutdown. But if you interrupt synth by typing Ctrl-C while building ports, they are left unmounted.

**Comment by jrmarino** [comment]
so the next command cleans them up.
e.g.
```
synth configure
```
And don't use control-C during the build.  Use ctrl-q and let synth shut down gracefully.

**Comment by yasuhirokimura** [comment]
Thank you for quick reply. I will use Ctrl-q next time.
