### ISSUE TITLE
Fails to test proposed update of mail/postfix-policyd-spf-python

### ISSUE THREAD

**Issue by yasuhirokimura** [jrmarino/synth#96]
I submitted following bug report to FreeBSD Bugzilla.

Bug 222389 - ports-mgmt/synth: Fails to test proposed update of mail/postfix-policyd-spf-python
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222389

Please check it and consider fixing the issue described there.

**Comment by jrmarino** [comment]
The "solution" provided is just a giant hack.  It's supposed to be provisional.  the correct fix requires flavor support to be imported.  It's a tremendous amount of work to implement a hack to fix a questionable build technique that's all going away sometime in the (near?) future ... 

so it probably won't happen

**Comment by jrmarino** [comment]
by the way, if you want to add this port to Ravenports, there's no issue with multiple python versions there:
http://ravenports.ironwolf.systems/

It has flavors and subpackages out of the box, which implements "multiversion" similar to pkgsrc.  So this issue doesn't exist there.

**Comment by jrmarino** [comment]
With the introduction of flavors (and support of flavors by Synth), this issue is now obsolete.
